import { IQuestion } from '../../models/Quiz.js';

export interface IJobQuestionItem extends IQuestion {
  subject: string;
  topic: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export const banglaQuestions: IJobQuestionItem[] = [
  // 1-10: বাংলা ব্যাকরণ - ধ্বনি ও বর্ণ, ণ-ত্ব ও ষ-ত্ব বিধান
  {
    questionText: 'বাংলা বর্ণমালায় মোট কতটি বর্ণ রয়েছে?',
    type: 'multiple-choice',
    options: ['৪৫টি', '৪৮টি', '৫০টি', '৫২টি'],
    correctAnswer: '৫০টি',
    explanation: 'বাংলা বর্ণমালায় মোট ৫০টি বর্ণ রয়েছে; যার মধ্যে স্বরবর্ণ ১১টি এবং ব্যঞ্জনবর্ণ ৩৯টি। (বিসিএস ও প্রাইমারি শিক্ষক নিয়োগে বহুবার এসেছে)',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা বর্ণমালায় মাত্রাহীন বর্ণের সংখ্যা কতটি?',
    type: 'multiple-choice',
    options: ['৮টি', '৯টি', '১০টি', '১২টি'],
    correctAnswer: '১০টি',
    explanation: 'বাংলা বর্ণমালায় মাত্রাহীন বর্ণ ১০টি (স্বরবর্ণে ৪টি: এ, ঐ, ও, ঔ এবং ব্যঞ্জনবর্ণে ৬টি: ঙ, ঞ, ৎ, ং, ঃ, ঁ)। পূর্ণমাত্রা ৩২টি, অর্ধমাত্রা ৮টি।',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন দুটি বর্ণের নিজস্ব কোনো ধ্বনি নেই?',
    type: 'multiple-choice',
    options: ['ং এবং ঃ', 'ঞ এবং ণ', 'য এবং ড়', 'শ এবং স'],
    correctAnswer: 'ং এবং ঃ',
    explanation: 'অনুস্বার (ং) ও বিসর্গ (ঃ) বর্ণ দুটি পরাশ্রয়ী বর্ণ এবং এদের নিজস্ব কোনো উচ্চারণ ধ্বনি নেই।',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘ষ্ণ’ যুক্তবর্ণটি কোন কোন বর্ণের সমন্বয়ে গঠিত?',
    type: 'multiple-choice',
    options: ['ষ + ণ', 'ষ + ন', 'স + ণ', 'শ + ন'],
    correctAnswer: 'ষ + ণ',
    explanation: 'মোর্ধন্য-ষ এবং মূর্ধন্য-ণ এর যুক্ত রূপ হলো ‘ষ্ণ’ (যেমন: কৃষ্ণ, উষ্ণ, তৃষ্ণা)।',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'স্বভাবতই মূর্ধন্য-ণ হয়েছে এমন উদাহরণ কোনটি?',
    type: 'multiple-choice',
    options: ['লবণ', 'কারণ', 'তৃণ', 'বর্ণ'],
    correctAnswer: 'লবণ',
    explanation: 'চাণক্য মাণিক্য গণ বাণিজ্য লবণ মণ—নিয়ম ছাড়া স্বাভাবিকভাবেই ‘লবণ’ শব্দে মূর্ধন্য-ণ ব্যবহৃত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ণ-ত্ব ও ষ-ত্ব বিধান',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন শব্দে স্বভাবতই মূর্ধন্য-ষ ব্যবহৃত হয়েছে?',
    type: 'multiple-choice',
    options: ['আষাঢ়', 'বৃষ্টি', 'কষ্ট', 'দৃষ্টি'],
    correctAnswer: 'আষাঢ়',
    explanation: 'আষাঢ়, ঊষা, পাষাণ, ঔষধ প্রভৃতি শব্দে কোনো নিয়ম ছাড়াই স্বভাবতই মূর্ধন্য-ষ হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ণ-ত্ব ও ষ-ত্ব বিধান',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কোন জাতীয় শব্দে ‘ষ’ এর ব্যবহার হয় না?',
    type: 'multiple-choice',
    options: ['তৎসম শব্দে', 'বিদেশি শব্দে', 'তদ্ভব শব্দে', 'দেশি শব্দে'],
    correctAnswer: 'বিদেশি শব্দে',
    explanation: 'বিদেশি বা আরবি, ফারসি, ইংরেজি শব্দে কখনো মূর্ধন্য-ষ ব্যবহৃত হয় না (যেমন: পোস্ট, মাস্টার, জিনিস, পোশাক)।',
    points: 1,
    subject: 'Bangla',
    topic: 'ণ-ত্ব ও ষ-ত্ব বিধান',
    difficulty: 'beginner',
  },
  {
    questionText: '‘নথী’ বা ‘পোস্টমাস্টার’ শব্দে কোন ‘স’ ব্যবহৃত হবে?',
    type: 'multiple-choice',
    options: ['দন্ত্য-স', 'মূর্ধন্য-ষ', 'তালব্য-শ', 'যেকোনো একটি'],
    correctAnswer: 'দন্ত্য-স',
    explanation: 'ইংরেজি ও বিদেশি শব্দে ‘st’ এর বাংলা রূপান্তর সর্বদা ‘স্ট’ (দন্ত্য-স + ট) হবে, মূর্ধন্য-ষ নয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ণ-ত্ব ও ষ-ত্ব বিধান',
    difficulty: 'beginner',
  },
  {
    questionText: '‘ধ্বনি’ নির্দেশক সাংকেতিক চিহ্নকে কী বলা হয়?',
    type: 'multiple-choice',
    options: ['বর্ণ', 'শব্দ', 'অক্ষর', 'বাক্য'],
    correctAnswer: 'বর্ণ',
    explanation: 'মানুষের উচ্চারিত ধ্বনির লিখিত রূপ বা সাংকেতিক রূপকে ‘বর্ণ’ বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'beginner',
  },
  {
    questionText: 'কন্ঠ্য বা জিহ্বামূলীয় ধ্বনি কোনগুলো?',
    type: 'multiple-choice',
    options: ['ক, খ, গ, ঘ, ঙ', 'চ, ছ, জ, ঝ, ঞ', 'ট, ঠ, ড, ঢ, ণ', 'ত, থ, দ, ধ, ন'],
    correctAnswer: 'ক, খ, গ, ঘ, ঙ',
    explanation: 'ক-বর্গীয় বর্ণসমূহ জিহ্বামূল বা কন্ঠ থেকে উচ্চারিত হয় বলে এদের কন্ঠ্য ধ্বনি বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ধ্বনি ও বর্ণ',
    difficulty: 'beginner',
  },

  // 11-25: সন্ধি ও সমাস
  {
    questionText: '‘গায়ক’ শব্দের সঠিক সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['গৈ + অক', 'গা + য়ক', 'গো + অক', 'গে + অক'],
    correctAnswer: 'গৈ + অক',
    explanation: 'ঐ-কারের পর অন্য স্বরবর্ণ থাকলে ‘ঐ’ স্থলে ‘আয়’ হয়। তাই গৈ + অক = গায়ক। নায়ক = নৈ + অক।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘পাবক’ শব্দের সঠিক সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['পৌ + অক', 'পো + অক', 'পা + বক', 'পব + অক'],
    correctAnswer: 'পৌ + অক',
    explanation: 'ঔ-কারের পর অন্য স্বরধ্বনি থাকলে ‘ঔ’ স্থলে ‘আব’ হয়। পৌ + অক = পাবক। পো + অন = পবন।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘ষোড়শ’ এর সঠিক সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['ষট্ + দশ', 'ষষ্ + দশ', 'ষোড় + শ', 'ষো + দশ'],
    correctAnswer: 'ষট্ + দশ',
    explanation: 'নিপাতনে সিদ্ধ ব্যঞ্জনসন্ধির উদাহরণ: ষট্ + দশ = ষোড়শ।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘বৃষ্টি’ শব্দের সঠিক সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['বৃষ্ + তি', 'বৃষ + তি', 'বৃ + বৃষ্টি', 'বৃষ্ + টি'],
    correctAnswer: 'বৃষ্ + তি',
    explanation: 'ষ-এর পরে ত বা থ থাকলে তা যথাক্রমে ট ও ঠ হয়। যেমন: বৃষ্ + তি = বৃষ্টি; কৃষ্ + তি = কৃষ্টি।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘পরস্পর’ শব্দের সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['পার + পর', 'পর + পর', 'পরা + পর', 'পরঃ + পর'],
    correctAnswer: 'পর + পর',
    explanation: 'নিপাতনে সিদ্ধ ব্যঞ্জনসন্ধি: পর + পর = পরস্পর।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘মনীষা’ শব্দের সন্ধি বিচ্ছেদ কী?',
    type: 'multiple-choice',
    options: ['মনস্ + ঈষা', 'মন + ঈষা', 'মণি + ঈষা', 'মনো + ঈষা'],
    correctAnswer: 'মনস্ + ঈষা',
    explanation: 'মনস্ + ঈষা = মনীষা (নিপাতনে সিদ্ধ সন্ধি)। পতৎ + অঞ্জলি = পতঞ্জলি।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'advanced',
  },
  {
    questionText: '‘সমাস’ শব্দের অর্থ কী?',
    type: 'multiple-choice',
    options: ['সংক্ষেপ বা মিলন', 'শব্দের বিস্তার', 'বাক্যের রূপান্তর', 'ধ্বনির পরিবর্তন'],
    correctAnswer: 'সংক্ষেপ বা মিলন',
    explanation: 'সমাস শব্দের অর্থ সংক্ষেপণ, মিলন বা একাধিক পদের একপদীকরণ।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },
  {
    questionText: '‘সিংহ চিহ্নিত আসন = সিংহাসন’ এটি কোন সমাসের উদাহরণ?',
    type: 'multiple-choice',
    options: ['মধ্যপদলোপী কর্মধারয়', 'উপমিত কর্মধারয়', 'রূপক কর্মধারয়', 'তৎপুরুষ সমাস'],
    correctAnswer: 'মধ্যপদলোপী কর্মধারয়',
    explanation: 'যে কর্মধারয় সমাসে ব্যাসবাক্যের মধ্যস্থিত পদ লোপ পায় তাকে মধ্যপদলোপী কর্মধারয় সমাস বলে।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },
  {
    questionText: '‘চাঁদমুখ’ এর সঠিক ব্যাসবাক্য কোনটি?',
    type: 'multiple-choice',
    options: ['মুখ চাঁদের ন্যায়', 'চাঁদ মুখের ন্যায়', 'চাঁদের মতো মুখ রূপ', 'চাঁদ ও মুখ'],
    correctAnswer: 'মুখ চাঁদের ন্যায়',
    explanation: 'উপমেয় ও উপমানের মধ্যে উপমিত কর্মধারয় সমাস: মুখ চাঁদের ন্যায় = চাঁদমুখ।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘ক্রোধরূপ অনল = ক্রোধানল’ কোন সমাস?',
    type: 'multiple-choice',
    options: ['রূপক কর্মধারয়', 'উপমান কর্মধারয়', 'উপমিত কর্মধারয়', 'বহুব্রীহি সমাস'],
    correctAnswer: 'রূপক কর্মধারয়',
    explanation: 'উপমেয় ও উপমানের মধ্যে অভিন্নতা কল্পনা করা হলে তাকে রূপক কর্মধারয় সমাস বলে (যেমন: বিশাদসিন্ধু, মনমাঝি)।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },
  {
    questionText: '‘দম্পতি’ কোন সমাসের উদাহরণ?',
    type: 'multiple-choice',
    options: ['দ্বন্দ্ব সমাস', 'কর্মধারয় সমাস', 'দ্বিগু সমাস', 'তৎপুরুষ সমাস'],
    correctAnswer: 'দ্বন্দ্ব সমাস',
    explanation: 'জায়া ও পতি = দম্পতি (দ্বন্দ্ব সমাস)।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'পূর্বপদের বিভক্তি লোপ না পেয়ে যে সমাস হয় তাকে কী বলে?',
    type: 'multiple-choice',
    options: ['অলুক সমাস', 'নিত্য সমাস', 'প্রাদি সমাস', 'উপপদ সমাস'],
    correctAnswer: 'অলুক সমাস',
    explanation: 'যে সমাসে পূর্বপদের বিভক্তি অক্ষুণ্ণ থাকে তাকে অলুক সমাস বলে (যেমন: মুখেভাত, ঘিয়েভাজা)।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘দশ আনন যার = দশানন’ কোন সমাসের উদাহরণ?',
    type: 'multiple-choice',
    options: ['বহুব্রীহি সমাস', 'দ্বিগু সমাস', 'কর্মধারয় সমাস', 'তৎপুরুষ সমাস'],
    correctAnswer: 'বহুব্রীহি সমাস',
    explanation: 'সংখ্যাবাচক শব্দ পূর্বপদে বসে অন্য কোনো অর্থ (রাবণ) প্রকাশ করলে তা সংখ্যাবাচক বহুব্রীহি সমাস হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘উপকূল’ কোন সমাসের উদাহরণ?',
    type: 'multiple-choice',
    options: ['অব্যয়ীভাব সমাস', 'তৎপুরুষ সমাস', 'কর্মধারয় সমাস', 'দ্বিগু সমাস'],
    correctAnswer: 'অব্যয়ীভাব সমাস',
    explanation: 'কূলের সমীপে = উপকূল। পূর্বপদে অব্যয় যুক্ত হয়ে অব্যয়ের অর্থ প্রাধান্য পেলে তাকে অব্যয়ীভাব সমাস বলে।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },
  {
    questionText: '‘তেপান্তর’ কোন সমাস?',
    type: 'multiple-choice',
    options: ['দ্বিগু সমাস', 'কর্মধারয় সমাস', 'বহুব্রীহি সমাস', 'দ্বন্দ্ব সমাস'],
    correctAnswer: 'দ্বিগু সমাস',
    explanation: 'তিন প্রান্তরের সমাহার = তেপান্তর। সংখ্যাবাচক শব্দ পূর্বে বসে সমাহার বোঝালে দ্বিগু সমাস হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমাস',
    difficulty: 'beginner',
  },

  // 26-40: কারক ও বিভক্তি, পদ প্রকরণ
  {
    questionText: '‘ডাক্তার ডাক’ বাক্যে ‘ডাক্তার’ কোন কারকে কোন বিভক্তি?',
    type: 'multiple-choice',
    options: ['কর্মে শূন্য', 'কর্তায় শূন্য', 'করণে শূন্য', 'অপাদানে শূন্য'],
    correctAnswer: 'কর্মে শূন্য',
    explanation: 'কাকে ডাকবে? ডাক্তারকে। ক্রিয়াকে ‘কী’ বা ‘কাকে’ দিয়ে প্রশ্ন করলে কর্মকারক পাওয়া যায় এবং কোনো বিভক্তি চিহ্ন না থাকায় শূন্য বিভক্তি।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘তিলে তৈল হয়’ বাক্যে ‘তিলে’ কোন কারকে কোন বিভক্তি?',
    type: 'multiple-choice',
    options: ['অপাদানে ৭মী', 'অধিকরণে ৭মী', 'করণে ৭মী', 'কর্মে ৭মী'],
    correctAnswer: 'অপাদানে ৭মী',
    explanation: 'তিল থেকে তৈল উৎপন্ন বা জাত হয়, যা অপাদান কারক। এ-বিভক্তি থাকায় অপাদানে ৭মী।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘তিলে তৈল আছে’ বাক্যে ‘তিলে’ কোন কারকে কোন বিভক্তি?',
    type: 'multiple-choice',
    options: ['অধিকরণে ৭মী', 'অপাদানে ৭মী', 'করণে ৭মী', 'কর্তায় ৭মী'],
    correctAnswer: 'অধিকরণে ৭মী',
    explanation: 'তিলের সর্বত্র তৈল বিরাজমান (অভিব্যাপক স্থান বা আধার), তাই এটি অধিকরণ কারকে ৭মী।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘টাকায় কিনা হয়’ বাক্যে ‘টাকায়’ কোন কারক?',
    type: 'multiple-choice',
    options: ['করণ কারক', 'অপাদান কারক', 'কর্ম কারক', 'অধিকরণ কারক'],
    correctAnswer: 'করণ কারক',
    explanation: 'টাকা দিয়ে বা টাকার দ্বারা কার্য সাধিত হয় (উপায় বা মাধ্যম), তাই করণ কারকে ৭মী বিভক্তি।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘পাপে বিরত হও’ বাক্যে ‘পাপে’ কোন কারক?',
    type: 'multiple-choice',
    options: ['অপাদান কারক', 'অধিকরণ কারক', 'করণ কারক', 'সম্প্রদান কারক'],
    correctAnswer: 'অপাদান কারক',
    explanation: 'যা থেকে কোনো কিছু পতিত, ভীত, চলিত বা বিরত হয়, তাকে অপাদান কারক বলে।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘সূর্যোদয়ে অন্ধকার দূরীভূত হয়’ এখানে ‘সূর্যোদয়ে’ কোন কারক?',
    type: 'multiple-choice',
    options: ['ভাবাধিকরণ', 'কালাধিকরণ', 'স্থানাধিকরণ', 'অপাদান'],
    correctAnswer: 'ভাবাধিকরণ',
    explanation: 'একটি ক্রিয়া অন্য ক্রিয়ার কারণ হলে তাকে ভাবাধিকরণ বলে। একে ল্যাটিন অনুসরণে এবসোলিউট লোকালিসও বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'advanced',
  },
  {
    questionText: '‘ভিক্ষুককে ভিক্ষা দাও’ বাক্যে ‘ভিক্ষুককে’ কোন কারকে কোন বিভক্তি?',
    type: 'multiple-choice',
    options: ['সম্প্রদানে ৪র্থী', 'কর্মে ২য়া', 'অপাদানে ৪র্থী', 'করণে ২য়া'],
    correctAnswer: 'সম্প্রদানে ৪র্থী',
    explanation: 'স্বত্ব ত্যাগ করে কাউকে কোনো কিছু দান করলে যাকে দান করা হয় তা সম্প্রদান কারক এবং ‘কে’ বিভক্তি হলো ৪র্থী।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘ধোপাকে কাপড় দাও’ বাক্যে ‘ধোপাকে’ কোন কারক?',
    type: 'multiple-choice',
    options: ['কর্ম কারক', 'সম্প্রদান কারক', 'করণ কারক', 'অপাদান কারক'],
    correctAnswer: 'কর্ম কারক',
    explanation: 'ধোপাকে কাপড় ফেরত পাওয়ার শর্তে দেওয়া হয়, কোনো চিরতরে স্বত্ব ত্যাগ নয়। তাই এটি কর্ম কারক।',
    points: 1,
    subject: 'Bangla',
    topic: 'কারক ও বিভক্তি',
    difficulty: 'beginner',
  },
  {
    questionText: 'শব্দ ও ধাতুর মূল রূপকে কী বলা হয়?',
    type: 'multiple-choice',
    options: ['প্রকৃতি', 'প্রত্যয়', 'উপসর্গ', 'অনুসর্গ'],
    correctAnswer: 'প্রকৃতি',
    explanation: 'শব্দের মূলকে নামপ্রকৃতি এবং ক্রিয়ার মূলকে ধাতু বা ক্রিয়া প্রকৃতি বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রকৃতি ও প্রত্যয়',
    difficulty: 'beginner',
  },
  {
    questionText: '‘কর্তব্য’ শব্দের সঠিক প্রকৃতি ও প্রত্যয় কোনটি?',
    type: 'multiple-choice',
    options: ['কৃ + তব্য', 'কর + তব্য', 'কোট + তব্য', 'করি + তব্য'],
    correctAnswer: 'কৃ + তব্য',
    explanation: 'কৃ (ধাতু) + তব্য (কৃৎ প্রত্যয়) = কর্তব্য।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রকৃতি ও প্রত্যয়',
    difficulty: 'beginner',
  },
  {
    questionText: '‘লাজুক’ শব্দের সঠিক প্রকৃতি-প্রত্যয় কোনটি?',
    type: 'multiple-choice',
    options: ['লাজ + উক', 'লাজা + উক', 'লজ্জা + উক', 'লাজ + ক'],
    correctAnswer: 'লাজ + উক',
    explanation: 'তদ্ধিত প্রত্যয়ের নিয়ম: লাজ + উক = লাজুক।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রকৃতি ও প্রত্যয়',
    difficulty: 'intermediate',
  },
  {
    questionText: 'উপসর্গ শব্দ বা ধাতুর কোথায় বসে?',
    type: 'multiple-choice',
    options: ['পূর্বে', 'মাঝে', 'শেষে', 'আলাদাভাবে'],
    correctAnswer: 'পূর্বে',
    explanation: 'উপসর্গ সর্বদা ধাতু বা শব্দের পূর্বে বসে নতুন অর্থবোধক শব্দ তৈরি করে। এদের নিজস্ব কোনো অর্থবাচকতা নেই, কিন্তু অর্থদ্যোতকতা আছে।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপসর্গ',
    difficulty: 'beginner',
  },
  {
    questionText: 'খাঁটি বাংলা উপসর্গ কয়টি?',
    type: 'multiple-choice',
    options: ['২১টি', '২০টি', '১৯টি', '২৫টি'],
    correctAnswer: '২১টি',
    explanation: 'খাঁটি বাংলা উপসর্গ ২১টি এবং সংস্কৃত (তৎসম) উপসর্গ ২০টি।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপসর্গ',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন চারটি উপসর্গ বাংলা ও তৎসম উভয় স্থানেই পাওয়া যায়?',
    type: 'multiple-choice',
    options: ['আ, সু, বি, নি', 'প্র, পরা, অপ, সং', 'অ, অঘা, অজ, অনা', 'অতি, অধি, অপি, অভি'],
    correctAnswer: 'আ, সু, বি, নি',
    explanation: '‘আ, সু, বি, নি’ এই চারটি উপসর্গ খাঁটি বাংলা ও তৎসম উভয় তালিকাতেই বিদ্যমান।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপসর্গ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘অনুগমন’ শব্দে ‘অনু’ উপসর্গটি কী অর্থে ব্যবহৃত হয়েছে?',
    type: 'multiple-choice',
    options: ['পশ্চাৎ', 'সাদৃশ্য', 'পুনঃপুন', 'বিপরীত'],
    correctAnswer: 'পশ্চাৎ',
    explanation: 'অনুগমন মানে পশ্চাতে বা পিছু পিছু গমন। এখানে ‘অনু’ পশ্চাৎ অর্থে ব্যবহৃত।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপসর্গ',
    difficulty: 'intermediate',
  },

  // 41-55: বাগধারা, প্রবাদ-প্রবচন ও সমার্থক/বিপরীত শব্দ
  {
    questionText: '‘অগাধ জলের মাছ’ বাগধারার অর্থ কী?',
    type: 'multiple-choice',
    options: ['খুব ধূর্ত ব্যক্তি', 'অসহায় ব্যক্তি', 'বোকা লোক', 'শান্ত স্বভাবের লোক'],
    correctAnswer: 'খুব ধূর্ত ব্যক্তি',
    explanation: 'অগাধ জলের মাছ বাগধারার অর্থ অতি চালাক বা গভীর জলের ধূর্ত ব্যক্তি।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '‘অরণ্যে রোদন’ বাগধারার সঠিক অর্থ কোনটি?',
    type: 'multiple-choice',
    options: ['বৃথা চেষ্টা', 'জঙ্গলে কান্না', 'ভীষণ বিপদ', 'অসহায় ক্রন্দন'],
    correctAnswer: 'বৃথা চেষ্টা',
    explanation: 'অরণ্যে রোদন অর্থ নিস্ফল আবেদন বা বৃথা চেষ্টা।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '‘ডুমুরের ফুল’ বাগধারাটির অর্থ কী?',
    type: 'multiple-choice',
    options: ['অদৃশ্য বা দুর্লভ বস্তু', 'সুন্দর ফুল', 'তুচ্ছ বিষয়', 'ক্ষণস্থায়ী সুখ'],
    correctAnswer: 'অদৃশ্য বা দুর্লভ বস্তু',
    explanation: 'ডুমুরের ফুল কখনো সচরাচর চোখে পড়ে না, তাই দুর্লভ বা দেখা না যাওয়া বস্তুকে ডুমুরের ফুল বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '‘কৈ মাছের প্রাণ’ বাগধারাটির অর্থ কী?',
    type: 'multiple-choice',
    options: ['যা সহজে মরে না', 'অত্যন্ত চঞ্চল', 'অস্থির মতি', 'ভীষণ সাহসী'],
    correctAnswer: 'যা সহজে মরে না',
    explanation: 'কৈ মাছ দীর্ঘক্ষণ পানি ছাড়া বেঁচে থাকতে পারে, তাই সহজে যার প্রাণ যায় না তাকে ‘কৈ মাছের প্রাণ’ বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '‘শাকের করাত’ বাগধারার অর্থ কী?',
    type: 'multiple-choice',
    options: ['উভয় সংকট', 'তীক্ষ্ণ অস্ত্র', 'কঠোর পরিশ্রম', 'অসম লড়াই'],
    correctAnswer: 'উভয় সংকট',
    explanation: 'শাকের করাত যেতেও কাটে, আসতেও কাটে; অর্থাৎ উভয় সংকট।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '‘সৌরভ’ শব্দের বিপরীত শব্দ কোনটি?',
    type: 'multiple-choice',
    options: ['পৌরভ', 'দুর্গন্ধ', 'কুরভ', 'অনাবিল'],
    correctAnswer: 'পৌরভ',
    explanation: 'সৌরভ এর বিপরীত শব্দ পৌরভ বা দুর্গন্ধ। প্রচলিত আভিধানিক বিপরীত শব্দ হলো ‘পৌরভ’।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিপরীত শব্দ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘উদ্ধত’ শব্দের বিপরীতার্থক শব্দ কোনটি?',
    type: 'multiple-choice',
    options: ['বিনয়ী', 'নম্র', 'ভদ্র', 'শান্ত'],
    correctAnswer: 'বিনয়ী',
    explanation: 'উদ্ধত শব্দের যথাযথ বিপরীত শব্দ হলো বিনয়ী।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিপরীত শব্দ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘জঙ্গম’ শব্দের বিপরীত শব্দ কোনটি?',
    type: 'multiple-choice',
    options: ['স্থাবর', 'অচল', 'স্থির', 'ধীর'],
    correctAnswer: 'স্থাবর',
    explanation: 'জঙ্গম (যা গতিশীল) এর বিপরীত শব্দ স্থাবর (যা স্থির)। বিসিএসে অনেকবার এসেছে।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিপরীত শব্দ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘অর্বাচীন’ শব্দের বিপরীত শব্দ কী?',
    type: 'multiple-choice',
    options: ['প্রাচীন', 'নবীন', 'প্রবীণ', 'আধুনিক'],
    correctAnswer: 'প্রাচীন',
    explanation: 'অর্বাচীন মানে নতুন বা আধুনিক; এর বিপরীত শব্দ প্রাচীন।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিপরীত শব্দ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘সূর্য’ শব্দের সমার্থক শব্দ কোনটি?',
    type: 'multiple-choice',
    options: ['মিহির', 'সুধাকর', 'শশাঙ্ক', 'বিধু'],
    correctAnswer: 'মিহির',
    explanation: 'সূর্যের সমার্থক: মিহির, তপন, রবি, ভানু, দিনকর। শশাঙ্ক ও সুধাকর হলো চাঁদের সমার্থক।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমার্থক শব্দ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘পবন’ শব্দের সমার্থক নয় কোনটি?',
    type: 'multiple-choice',
    options: ['পাথার', 'সমীরণ', 'মারুত', 'অনিল'],
    correctAnswer: 'পাথার',
    explanation: 'সমীরণ, মারুত, অনিল, বাত হলো বাতাসের সমার্থক। পাথার অর্থ সমুদ্র।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমার্থক শব্দ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘যার কোনো কিছুতেই ভয় নেই’ এককথায় কী হবে?',
    type: 'multiple-choice',
    options: ['অকুতোভয়', 'নির্ভীক', 'সাহসী', 'অপরাজেয়'],
    correctAnswer: 'অকুতোভয়',
    explanation: 'যার কোনো দিকে থেকেই ভয় নেই তাকে এককথায় বলে ‘অকুতোভয়’।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘যা বলা হয়নি’ এককথায় কী হবে?',
    type: 'multiple-choice',
    options: ['অনুক্ত', 'অবক্তব্য', 'অকথ্য', 'অপ্রকাশিত'],
    correctAnswer: 'অনুক্ত',
    explanation: 'যা বলা হয়নি = অনুক্ত। যা বলা উচিত নয় = অবক্তব্য। যা বলা যায় না = অকথ্য।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘যে নারীর স্বামী ও পুত্র নেই’ এককথায় কী হবে?',
    type: 'multiple-choice',
    options: ['অবিরা', 'অনূঢ়া', 'বিধবা', 'বন্ধ্যা'],
    correctAnswer: 'অবিরা',
    explanation: 'যে নারীর স্বামী ও পুত্র নেই = অবিরা। যে নারী কুমারী বা অবিবাহিত = অনূঢ়া।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘হনন করার ইচ্ছা’ এককথায় কী?',
    type: 'multiple-choice',
    options: ['জিঘাংসা', 'জিগীষা', 'জিজীবিষা', 'জিজ্ঞাসা'],
    correctAnswer: 'জিঘাংসা',
    explanation: 'হনন করার ইচ্ছা = জিঘাংসা। জয়ের ইচ্ছা = জিগীষা। বেঁচে থাকার ইচ্ছা = জিজীবিষা। জানার ইচ্ছা = জিজ্ঞাসা।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'intermediate',
  },

  // 56-70: শুদ্ধ বানান ও বাক্য শুদ্ধি
  {
    questionText: 'কোন বানানটি শুদ্ধ?',
    type: 'multiple-choice',
    options: ['মুহূর্ত', 'মুহুর্থ', 'মুহুর্ত', 'মূর্হুত'],
    correctAnswer: 'মুহূর্ত',
    explanation: 'শুদ্ধ বানান: ম-এ হ্রস্ব-উ + হ-এ দীর্ঘ-ঊ + ত-এ রেফ = ‘মুহূর্ত’।',
    points: 1,
    subject: 'Bangla',
    topic: 'বানান শুদ্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কোন বানানটি শুদ্ধ?',
    type: 'multiple-choice',
    options: ['মুমূর্ষু', 'মুমুর্ষু', 'মুমুর্যূ', 'মুমূর্ষূ'],
    correctAnswer: 'মুমূর্ষু',
    explanation: 'শুদ্ধ রূপ: ম-এ হ্রস্ব-উ, ম-এ দীর্ঘ-ঊ, ষ-এ হ্রস্ব-উ এবং রেফ = ‘মুমূর্ষু’।',
    points: 1,
    subject: 'Bangla',
    topic: 'বানান শুদ্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কোন বানানটি শুদ্ধ?',
    type: 'multiple-choice',
    options: ['নিরপরাধী', 'নিরপরাধ', 'নিরপরাদ্ধ', 'নিরপরাধি'],
    correctAnswer: 'নিরপরাধ',
    explanation: 'প্রত্যয়জনিত বা লিঙ্গজনিত ভুল: ‘নিরপরাধী ব্যক্তি’ নয়, শুদ্ধ হবে ‘নিরপরাধ ব্যক্তি’।',
    points: 1,
    subject: 'Bangla',
    topic: 'বানান শুদ্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কোন বানানটি অশুদ্ধ?',
    type: 'multiple-choice',
    options: ['দারিদ্রতা', 'দারিদ্র্য', 'দরিদ্রতা', 'দীনতা'],
    correctAnswer: 'দারিদ্রতা',
    explanation: 'য-ফলা এবং তা প্রত্যয় একসাথে বসে না। হয় ‘দারিদ্র্য’ হবে অথবা ‘দরিদ্রতা’ হবে। ‘দারিদ্রতা’ অশুদ্ধ।',
    points: 1,
    subject: 'Bangla',
    topic: 'বানান শুদ্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কোন বাক্যটি শুদ্ধ?',
    type: 'multiple-choice',
    options: [
      'সকল সদস্যগণ উপস্থিত ছিলেন।',
      'সকল সদস্য উপস্থিত ছিলেন।',
      'সব সদস্যদের উপস্থিতি ঘটেছিল।',
      'সদস্যবৃন্দরা উপস্থিত ছিলেন।',
    ],
    correctAnswer: 'সকল সদস্য উপস্থিত ছিলেন।',
    explanation: 'বহুলবচনের দ্বিবিধ প্রয়োগ বা বাহুল্য দোষ: ‘সকল’ এবং ‘গণ’ একসঙ্গে ব্যবহৃত হলে বাহুল্য দোষ হয়। শুদ্ধ হলো: ‘সকল সদস্য উপস্থিত ছিলেন’।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য শুদ্ধি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘বিদ্যান মূর্খ অপেক্ষা শ্রেষ্ঠতর’ বাক্যটির শুদ্ধ রূপ কোনটি?',
    type: 'multiple-choice',
    options: [
      'বিদ্বান মূর্খ অপেক্ষা শ্রেষ্ঠ।',
      'বিদ্যান ব্যক্তি মূর্খের চেয়ে শ্রেষ্ঠতর।',
      'বিদ্বান ব্যক্তি মূর্খ হতে শ্রেষ্ঠতর।',
      'বিদ্বান মূর্খের সমতুল্য।',
    ],
    correctAnswer: 'বিদ্বান মূর্খ অপেক্ষা শ্রেষ্ঠ।',
    explanation: '‘অপেক্ষা’ থাকলে আবার ‘তর’ প্রত্যয় যোগ করা বাহুল্য দোষ। এছাড়া বানান হবে ‘বিদ্বান’। তাই শুদ্ধ: বিদ্বান মূর্খ অপেক্ষা শ্রেষ্ঠ।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য শুদ্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘অধ্যয়ন’ শব্দের শুদ্ধ উচ্চারণ কোনটি?',
    type: 'multiple-choice',
    options: ['ওদ্ধোয়োন্', 'অধ্ধায়ন', 'অধ্যয়ন্', 'ওদ্ধায়ন'],
    correctAnswer: 'ওদ্ধোয়োন্',
    explanation: 'আদ্য অ-এর পরে য-ফলা থাকলে অ-এর উচ্চারণ ‘ও’ এর মতো হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'উচ্চারণ',
    difficulty: 'advanced',
  },
  {
    questionText: '‘শহীদ মিনার’ শব্দে ‘শহীদ’ কোন ভাষার শব্দ?',
    type: 'multiple-choice',
    options: ['আরবি', 'ফারসি', 'তুর্কি', 'পর্তুগিজ'],
    correctAnswer: 'আরবি',
    explanation: 'শহীদ, কুরবানি, হালাল, হারাম, আদালত ইত্যাদি আরবি শব্দ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'beginner',
  },
  {
    questionText: '‘দারোগা’ কোন ভাষার শব্দ?',
    type: 'multiple-choice',
    options: ['তুর্কি', 'পর্তুগিজ', 'ফারসি', 'ওলন্দাজ'],
    correctAnswer: 'তুর্কি',
    explanation: 'দারোগা, চাকর, বন্দুক, তোপ, বাবুর্চি, কুলি ইত্যাদি তুর্কি ভাষার শব্দ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘আনারস’ এবং ‘চাবি’ কোন ভাষার শব্দ?',
    type: 'multiple-choice',
    options: ['পর্তুগিজ', 'ওলন্দাজ', 'ফরাসি', 'ইংরেজি'],
    correctAnswer: 'পর্তুগিজ',
    explanation: 'আনারস, আলপিন, আলমারি, চাবি, পাউরুটি, সাবান ইত্যাদি পর্তুগিজ শব্দ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'beginner',
  },
  {
    questionText: '‘হরতাল’ কোন ভাষার শব্দ?',
    type: 'multiple-choice',
    options: ['গুজরাটি', 'মারাঠি', 'পাঞ্জাবি', 'হিন্দি'],
    correctAnswer: 'গুজরাটি',
    explanation: 'হরতাল গুজরাটি শব্দ। চাহিদা, শিখ হলো পাঞ্জাবি শব্দ। খদ্দর হলো গুজরাটি শব্দ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'beginner',
  },
  {
    questionText: '‘রিকশা’ কোন ভাষার শব্দ?',
    type: 'multiple-choice',
    options: ['জাপানি', 'চীনা', 'বর্মি', 'মালয়'],
    correctAnswer: 'জাপানি',
    explanation: 'রিকশা, হারিকিরি, হাসনাহেনা হলো জাপানি শব্দ। চা, চিনি, লিচু হলো চীনা শব্দ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'beginner',
  },
  {
    questionText: '‘গুরুচণ্ডালী দোষ’ বলতে কী বোঝায়?',
    type: 'multiple-choice',
    options: [
      'তৎসম শব্দের সাথে দেশি/তদ্ভব শব্দের মিশ্রণ',
      'সাধু ও চলিত ভাষার মিশ্রণ নয় কেবল বানান ভুল',
      'বিদেশি শব্দের যথেচ্ছ প্রয়োগ',
      'বাক্যে কর্তা ও ক্রিয়ার অনন্বয়',
    ],
    correctAnswer: 'তৎসম শব্দের সাথে দেশি/তদ্ভব শব্দের মিশ্রণ',
    explanation: 'তৎসম শব্দের সঙ্গে দেশি বা তদ্ভব শব্দের অশোভন মিশ্রণকে গুরুচণ্ডালী দোষ বলে (যেমন: মড়াদাহ, শবপোড়া)।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য প্রকরণ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'বাংলা ভাষায় জ্যোতি বা ছেদচিহ্ন প্রথম সার্থকভাবে ব্যবহার করেন কে?',
    type: 'multiple-choice',
    options: ['ঈশ্বরচন্দ্র বিদ্যাসাগর', 'উইলিয়াম কেরি', 'বঙ্কিমচন্দ্র চট্টোপাধ্যায়', 'রবীন্দ্রনাথ ঠাকুর'],
    correctAnswer: 'ঈশ্বরচন্দ্র বিদ্যাসাগর',
    explanation: 'ঈশ্বরচন্দ্র বিদ্যাসাগর তাঁর ‘বেতাল পঞ্চবিংশতি’ (১৮৪৭) গ্রন্থে প্রথম সফলভাবে বাংলা গদ্যে বিরামচিহ্নের প্রয়োগ ঘটান।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিরামচিহ্ন',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন বিরামচিহ্নে থামার কোনো প্রয়োজন নেই?',
    type: 'multiple-choice',
    options: ['হাইফেন ও ব্র্যাকেট', 'কমা', 'কোলন', 'সেমিকোলন'],
    correctAnswer: 'হাইফেন ও ব্র্যাকেট',
    explanation: 'হাইফেন, ইলেক ও ব্র্যাকেট বা বন্ধনী চিহ্নে থামার কোনো সময় ব্যয় করতে হয় না।',
    points: 1,
    subject: 'Bangla',
    topic: 'বিরামচিহ্ন',
    difficulty: 'intermediate',
  },

  // 71-100: বাংলা সাহিত্য - প্রাচীন, মধ্যযুগ ও আধুনিক যুগ
  {
    questionText: 'বাংলা সাহিত্যের প্রাচীনতম নিদর্শন কোনটি?',
    type: 'multiple-choice',
    options: ['চর্যাপদ', 'শ্রীকৃষ্ণকীর্তন', 'মঙ্গলকাব্য', 'মৈমনসিংহ গীতিকা'],
    correctAnswer: 'চর্যাপদ',
    explanation: 'চর্যাপদ হলো বাংলা ভাষার আদি বা প্রাচীনতম কাব্যসংগ্রহ। এর রচয়িতা বৌদ্ধ সহজিয়া সিদ্ধাচার্যগণ।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রাচীন যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'চর্যাপদের পুঁথি কে কত সালে কোথা থেকে আবিষ্কার করেন?',
    type: 'multiple-choice',
    options: [
      'মহামহোপাধ্যায় হরপ্রসাদ শাস্ত্রী ১৯০৭ সালে নেপালের রাজদরবারের রয়েল লাইব্রেরি থেকে',
      'সুনীতিকুমার চট্টোপাধ্যায় ১৯১৬ সালে কলকাতা থেকে',
      'ড. মুহম্মদ শহীদুল্লাহ ১৯১২ সালে তিব্বত থেকে',
      'ড. সুকুমার সেন ১৯২০ সালে ঢাকা বিশ্ববিদ্যালয় থেকে',
    ],
    correctAnswer: 'মহামহোপাধ্যায় হরপ্রসাদ শাস্ত্রী ১৯০৭ সালে নেপালের রাজদরবারের রয়েল লাইব্রেরি থেকে',
    explanation: '১৯০৭ সালে মহামহোপাধ্যায় হরপ্রসাদ শাস্ত্রী নেপালের রাজদরবারের রয়েল লাইব্রেরি থেকে চর্যাপদের মূল পুথি আবিষ্কার করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রাচীন যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'চর্যাপদে সবচেয়ে বেশি পদ রচনা করেছেন কে?',
    type: 'multiple-choice',
    options: ['কাহ্নপা (১৩টি)', 'লুইপা (২টি)', 'ভুসুকুপা (৮টি)', 'শবরপা (২টি)'],
    correctAnswer: 'কাহ্নপা (১৩টি)',
    explanation: 'কাহ্নপা বা কৃষ্ণাচার্য সর্বোচ্চ ১৩টি পদ রচনা করেছেন। দ্বিতীয় স্থানে ভুসুকুপা (৮টি)। আদি কবি লুইপা।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রাচীন যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'মধ্যযুগের প্রথম কাব্য কোনটি?',
    type: 'multiple-choice',
    options: ['শ্রীকৃষ্ণকীর্তন', 'পদ্মাবতী', 'মনসামঙ্গল', 'ইউসুফ-জোলেখা'],
    correctAnswer: 'শ্রীকৃষ্ণকীর্তন',
    explanation: 'বড়ু চণ্ডীদাস রচিত ‘শ্রীকৃষ্ণকীর্তন’ মধ্যযুগের প্রথম লিখিত কাব্য। বসন্তরঞ্জন রায় বিদ্বদ্বল্লভ ১৯০৯ সালে বাঁকুড়ার এক গৃহস্থের গোয়ালঘর থেকে এটি আবিষ্কার করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'মধ্যযুগ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘আমার সন্তান যেন থাকে দুধেভাতে’—এই উক্তিটি কোন কাব্যের কার প্রার্থনা?',
    type: 'multiple-choice',
    options: [
      'অন্নদামঙ্গল কাব্যের ঈশ্বরী পাটুনীর',
      'মনসামঙ্গল কাব্যের বেহুলার',
      'চণ্ডীমঙ্গল কাব্যের ফুল্লরার',
      'শ্রীকৃষ্ণকীর্তনের রাধার',
    ],
    correctAnswer: 'অন্নদামঙ্গল কাব্যের ঈশ্বরী পাটুনীর',
    explanation: 'ভারতচন্দ্র রায়গুণাকরের ‘অন্নদামঙ্গল’ কাব্যে দেবী অন্নপূর্ণার কাছে ঈশ্বরী পাটুনীর এই চিরন্তন কল্যাণ প্রার্থনা।',
    points: 1,
    subject: 'Bangla',
    topic: 'মধ্যযুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'পদ্মাবতী কাব্যের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['আলাওল', 'দৌলত কাজী', 'শাহ মুহম্মদ সগীর', 'সৈয়দ সুলতান'],
    correctAnswer: 'আলাওল',
    explanation: 'মহাকবি আলাওল মালিক মুহম্মদ জায়সীর হিন্দি ‘পদুমাবত’ কাব্য অবলম্বনে আরাকান রাজসভায় পদ্মাবতী কাব্য রচনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'মধ্যযুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা সাহিত্যের প্রথম মুসলিম কবি কে?',
    type: 'multiple-choice',
    options: ['শাহ মুহম্মদ সগীর', 'দৌলত কাজী', 'আলাওল', 'সাবিরিদ খাঁ'],
    correctAnswer: 'শাহ মুহম্মদ সগীর',
    explanation: 'সুলতান গিয়াসউদ্দিন আজম শাহের রাজত্বকালে রচিত ‘ইউসুফ-জোলেখা’ কাব্যের রচয়িতা শাহ মুহম্মদ সগীর বাংলা সাহিত্যের প্রথম মুসলিম কবি।',
    points: 1,
    subject: 'Bangla',
    topic: 'মধ্যযুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'মাইকেল মধুসূদন দত্তের অমর মহাকাব্য ‘মেঘনাদবধ কাব্য’ কত সালে প্রকাশিত হয়?',
    type: 'multiple-choice',
    options: ['১৮৬১ সালে', '১৮৫৮ সালে', '১৮৬৫ সালে', '১৮৭২ সালে'],
    correctAnswer: '১৮৬১ সালে',
    explanation: 'অমিত্রাক্ষর ছন্দে রচিত বাংলা সাহিত্যের প্রথম সার্থক মহাকাব্য ‘মেঘনাদবধ কাব্য’ ১৮৬১ সালে প্রকাশিত হয়। এটি ৯টি সর্গে বিভক্ত।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস কোনটি?',
    type: 'multiple-choice',
    options: ['দুর্গেশনন্দিনী', 'আলালের ঘরের দুলাল', 'কপালকুণ্ডলা', 'চোখের বালি'],
    correctAnswer: 'দুর্গেশনন্দিনী',
    explanation: '১৮৬৫ সালে বঙ্কিমচন্দ্র চট্টোপাধ্যায় রচিত ‘দুর্গেশনন্দিনী’ বাংলা সাহিত্যের প্রথম সার্থক রোমান্টিক উপন্যাস।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'রবীন্দ্রনাথ ঠাকুর কত সালে এবং কোন গ্রন্থের জন্য নোবেল পুরস্কার লাভ করেন?',
    type: 'multiple-choice',
    options: ['১৯১৩ সালে Song Offerings এর জন্য', '১৯১১ সালে গীতাঞ্জলির জন্য', '১৯১৫ সালে গোরা উপন্যাসের জন্য', '১৯১৮ সালে বলাকা কাব্যের জন্য'],
    correctAnswer: '১৯১৩ সালে Song Offerings এর জন্য',
    explanation: '১৯১৩ সালে গীতাঞ্জলির ইংরেজি অনুবাদ ‘Song Offerings’ এর ভূমিকা (ভূমিকা লিখেছিলেন ডব্লিউ বি ইয়েটস) সহ ইংরেজি প্রকাশের জন্য সাহিত্যে প্রথম এশীয় হিসেবে নোবেল পুরস্কার পান।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'কাজী নজরুল ইসলাম সম্পাদিত বিখ্যাত পত্রিকা কোনটি?',
    type: 'multiple-choice',
    options: ['ধূমকেতু ও লাঙল', 'সবুজপত্র', 'বঙ্গদর্শন', 'কল্লোল'],
    correctAnswer: 'ধূমকেতু ও লাঙল',
    explanation: 'কাজী নজরুল ইসলাম ১৯২২ সালে অর্ধ-সাপ্তাহিক ‘ধূমকেতু’ এবং ১৯২৫ সালে ‘লাঙল’ পত্রিকা সম্পাদনা করেন। ধূমকেতুতে ‘আনন্দময়ীর আগমনে’ কবিতা লিখে তিনি কারাবরণ করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: 'নজরুল রবীন্দ্রনাথকে তাঁর কোন গ্রন্থটি উৎসর্গ করেছিলেন?',
    type: 'multiple-choice',
    options: ['সঞ্চিতা', 'অগ্নিবীণা', 'দোলনচাঁপা', 'বিষের বাঁশী'],
    correctAnswer: 'সঞ্চিতা',
    explanation: 'কাজী নজরুল ইসলাম রবীন্দ্রনাথ ঠাকুরকে ‘সঞ্চিতা’ কাব্যগ্রন্থ উৎসর্গ করেন। রবীন্দ্রনাথ নজরুলকে তাঁর ‘বসন্ত’ নাটক উৎসর্গ করেছিলেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘নকশী কাঁথার মাঠ’ কাব্যগ্রন্থের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['পল্লীকবি জসীমউদ্দীন', 'জীবনানন্দ দাশ', 'ফররুখ আহমদ', 'সুকান্ত ভট্টাচার্য'],
    correctAnswer: 'পল্লীকবি জসীমউদ্দীন',
    explanation: '১৯২৯ সালে প্রকাশিত এই অমর আখ্যানকাব্যের নায়ক-নায়িকা রূপাই ও সাজু। এটি ইংরেজিতে ‘The Field of the Embroidered Quilt’ নামে অনূদিত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘রূপসী বাংলার কবি’ কাকে বলা হয়?',
    type: 'multiple-choice',
    options: ['জীবনানন্দ দাশ', 'জসীমউদ্দীন', 'ঈশ্বরচন্দ্র গুপ্ত', 'সুধীন্দ্রনাথ দত্ত'],
    correctAnswer: 'জীবনানন্দ দাশ',
    explanation: 'জীবনানন্দ দাশকে রূপসী বাংলার কবি, তিমির হননের কবি এবং নির্জনতম কবি হিসেবে আখ্যায়িত করা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘রক্তাক্ত প্রান্তর’ নাটকের পটভূমি কী?',
    type: 'multiple-choice',
    options: [
      'পানিপথের তৃতীয় যুদ্ধ',
      'পলাশীর যুদ্ধ',
      'সিপাহী বিদ্রোহ',
      '১৯৭১ সালের মুক্তিযুদ্ধ',
    ],
    correctAnswer: 'পানিপথের তৃতীয় যুদ্ধ',
    explanation: 'মুনীর চৌধুরী রচিত ঐতিহাসিক নাটক ‘রক্তাক্ত প্রান্তর’ ১৭৬১ সালের পানিপথের তৃতীয় যুদ্ধের পটভূমিতে রচিত। বিখ্যাত উক্তি: ‘মানুষের মৃত্যু হলে তবু মানব থেকে যায়’।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'মুক্তিযুদ্ধভিত্তিক উপন্যাস ‘রাইফেল রোটি আওরাত’ এর রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['আনোয়ার পাশা', 'জহির রায়হান', 'শওকত ওসমান', 'সৈয়দ শামসুল হক'],
    correctAnswer: 'আনোয়ার পাশা',
    explanation: 'শহীদ বুদ্ধিজীবী আনোয়ার পাশা ১৯৭১ সালে অবরুদ্ধ ঢাকায় বসে মুক্তিযুদ্ধের ওপর প্রথম উপন্যাস ‘রাইফেল রোটি আওরাত’ রচনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'মুক্তিযুদ্ধ সাহিত্য',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘হাজার বছর ধরে’ উপন্যাসের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['জহির রায়হান', 'শওকত আলী', 'আখতারুজ্জামান ইলিয়াস', 'হুমায়ূন আহমেদ'],
    correctAnswer: 'জহির রায়হান',
    explanation: 'গ্রামীণ জীবনের পটভূমিতে রচিত ‘হাজার বছর ধরে’ উপন্যাসের কেন্দ্রীয় চরিত্র টুনি ও মন্তু। এর রচয়িতা জহির রায়হান।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘চিলেকোঠার সেপাই’ উপন্যাসটির রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['আখতারুজ্জামান ইলিয়াস', 'শওকত ওসমান', 'হাসান আজিজুল হক', 'আবুল ফজল'],
    correctAnswer: 'আখতারুজ্জামান ইলিয়াস',
    explanation: '১৯৬৯-এর গণঅভ্যুত্থানের প্রেক্ষাপটে রচিত এই উপন্যাসের প্রধান চরিত্র ওসমান ও হাড্ডি খিজির। রচয়িতা আখতারুজ্জামান ইলিয়াস।',
    points: 1,
    subject: 'Bangla',
    topic: 'আধুনিক যুগ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘একুশে ফেব্রুয়ারি’ সংকলন গ্রন্থের প্রথম সম্পাদক কে?',
    type: 'multiple-choice',
    options: ['হাসান হাফিজুর রহমান', 'আব্দুল গাফফার চৌধুরী', 'শামসুর রাহমান', 'বোরহানউদ্দিন খান জাহাঙ্গীর'],
    correctAnswer: 'হাসান হাফিজুর রহমান',
    explanation: '১৯৫৩ সালে প্রকাশিত ভাষা আন্দোলনের ওপর প্রথম সাহিত্য সংকলন ‘একুশে ফেব্রুয়ারি’ সম্পাদনা করেন কবি হাসান হাফিজুর রহমান।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষা আন্দোলন সাহিত্য',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘আমার ভাইয়ের রক্তে রাঙানো একুশে ফেব্রুয়ারি’ গানটির বর্তমান সুরকার কে?',
    type: 'multiple-choice',
    options: ['আলতাফ মাহমুদ', 'আব্দুল লতিফ', 'সমর দাস', 'শেখ লুৎফর রহমান'],
    correctAnswer: 'আলতাফ মাহমুদ',
    explanation: 'গানটির রচয়িতা আব্দুল গাফফার চৌধুরী। প্রথম সুরকার ছিলেন আব্দুল লতিফ এবং বর্তমান বহুল প্রচলিত অমর সুরকার শহীদ আলতাফ মাহমুদ।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষা আন্দোলন সাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: '‘নীলদর্পণ’ নাটকের রচয়িতা কে এবং এটি কোন বিদ্রোহের প্রেক্ষাপটে রচিত?',
    type: 'multiple-choice',
    options: [
      'দীনবন্ধু মিত্র; নীলকর সাহেবদের অত্যাচারের বিরুদ্ধে নীল বিদ্রোহ',
      'মীর মশাররফ হোসেন; জমিদারি প্রথা বিরোধী আন্দোলন',
      'দ্বিজেন্দ্রলাল রায়; সিপাহী বিদ্রোহ',
      'গিরিশচন্দ্র ঘোষ; সাঁওতাল বিদ্রোহ',
    ],
    correctAnswer: 'দীনবন্ধু মিত্র; নীলকর সাহেবদের অত্যাচারের বিরুদ্ধে নীল বিদ্রোহ',
    explanation: '১৮৬০ সালে ঢাকা থেকে প্রকাশিত দীনবন্ধু মিত্রের ‘নীলদর্পণ’ নাটকটি মাইকেল মধুসূদন দত্ত ‘The Indigo Planting Mirror’ নামে ইংরেজি অনুবাদ করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'নাটক ও সাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: '‘বিষাদ-সিন্ধু’ উপন্যাসের মূল উপজীব্য বিষয় কী?',
    type: 'multiple-choice',
    options: ['কারবালার মর্মান্তিক ইতিহাস', 'পলাশীর যুদ্ধ', 'পানিপথের যুদ্ধ', 'ক্রুসেড'],
    correctAnswer: 'কারবালার মর্মান্তিক ইতিহাস',
    explanation: 'মীর মশাররফ হোসেন রচিত ঐতিহাসিক রোমান্টিক উপন্যাস ‘বিষাদ-সিন্ধু’ (মহরম পর্ব, উদ্ধার পর্ব, এজিদ বধ পর্ব) কারবালার ইতিহাস আশ্রিত।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপন্যাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'বেগম রোকেয়া সাখাওয়াত হোসেন রচিত প্রথম ইংরেজি উপন্যাসিকা কোনটি?',
    type: 'multiple-choice',
    options: ["Sultana's Dream", 'Padmarag', 'Motichur', 'Abarodhbasini'],
    correctAnswer: "Sultana's Dream",
    explanation: '১৯০৫ সালে ‘The Indian Ladies Magazine’ এ প্রকাশিত ‘Sultana\'s Dream’ বিশ্বের আদি নারীবাদী কল্পবিজ্ঞান উপন্যাসের অন্যতম।',
    points: 1,
    subject: 'Bangla',
    topic: 'নারী জাগরণ ও সাহিত্য',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘পথের পাঁচালী’ ও ‘অপরাজিত’ উপন্যাসের অমর রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['বিভূতিভূষণ বন্দ্যোপাধ্যায়', 'তারাশঙ্কর বন্দ্যোপাধ্যায়', 'শরৎচন্দ্র চট্টোপাধ্যায়', 'মানিক বন্দ্যোপাধ্যায়'],
    correctAnswer: 'বিভূতিভূষণ বন্দ্যোপাধ্যায়',
    explanation: 'অপু ও দুর্গা চরিত্রের অমর স্রষ্টা প্রকৃতিপ্রেমী কথাসাহিত্যিক বিভূতিভূষণ বন্দ্যোপাধ্যায়।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপন্যাস',
    difficulty: 'beginner',
  },
  {
    questionText: '‘পদ্মা নদীর মাঝি’ উপন্যাসের প্রধান চরিত্র কোনটি?',
    type: 'multiple-choice',
    options: ['কুবের ও কপিলা', 'অপু ও দুর্গা', 'রূপাই ও সাজু', 'ওসমান ও খিজির'],
    correctAnswer: 'কুবের ও কপিলা',
    explanation: 'মানিক বন্দ্যোপাধ্যায় রচিত ধীবর সমাজের জীবনসংগ্রামের আখ্যান ‘পদ্মা নদীর মাঝি’ (হোসেন মিয়ার ময়নাদ্বীপ, কুবের, কপিলা ও মালা)।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপন্যাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'শরৎচন্দ্র চট্টোপাধ্যায় কোন উপন্যাসের জন্য কুন্তলীন পুরস্কার লাভ করেন?',
    type: 'multiple-choice',
    options: ['মন্দির', 'দেবদাস', 'চরিত্রহীন', 'শ্রীকান্ত'],
    correctAnswer: 'মন্দির',
    explanation: '১৯০৩ সালে তাঁর প্রথম মুদ্রিত গল্প ‘মন্দির’ কুন্তলীন পুরস্কার লাভ করে।',
    points: 1,
    subject: 'Bangla',
    topic: 'উপন্যাস ও গল্প',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘স্বাধীনতা হীনতায় কে বাঁচিতে চায় হে, কে বাঁচিতে চায়?’ চরণটির রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['রঙ্গলাল বন্দ্যোপাধ্যায়', 'হেমচন্দ্র বন্দ্যোপাধ্যায়', 'নবীনচন্দ্র সেন', 'মাইকেল মধুসূদন দত্ত'],
    correctAnswer: 'রঙ্গলাল বন্দ্যোপাধ্যায়',
    explanation: 'কবি রঙ্গলাল বন্দ্যোপাধ্যায়ের ‘পদ্মিনী উপাখ্যান’ (১৮৫৮) কাব্যের এই দেশপ্রেমমূলক পঙ্‌ক্তিটি সুবিখ্যাত।',
    points: 1,
    subject: 'Bangla',
    topic: 'কবিতা ও উক্তি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘সবার উপরে মানুষ সত্য, তাহার উপরে নাই’—কার বিখ্যাত বাণী?',
    type: 'multiple-choice',
    options: ['চণ্ডীদাস', 'বিদ্যাপতি', 'জ্ঞানদাস', 'গোবিন্দদাস'],
    correctAnswer: 'চণ্ডীদাস',
    explanation: 'মধ্যযুগের বৈষ্ণব পদাবলীর অমর কবি বড়ু চণ্ডীদাসের এই মানবতাবাদী বাণী চিরস্মরণীয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'মধ্যযুগ ও পদাবলী',
    difficulty: 'beginner',
  },
  {
    questionText: '‘মৈমনসিংহ গীতিকা’ কে সংকলন ও সম্পাদনা করেন?',
    type: 'multiple-choice',
    options: ['ড. দীনেশচন্দ্র সেন', 'চন্দ্রকুমার দে', 'মুহম্মদ শহীদুল্লাহ', 'সুকুমার সেন'],
    correctAnswer: 'ড. দীনেশচন্দ্র সেন',
    explanation: 'চন্দ্রকুমার দে গ্রামগঞ্জ থেকে পালাগানগুলো সংগ্রহ করেন এবং কলকাতা বিশ্ববিদ্যালয়ের ড. দীনেশচন্দ্র সেন তা ১৯২৩ সালে সংকলন ও সম্পাদনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'লোকসাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা লিপির উৎস কী?',
    type: 'multiple-choice',
    options: ['ব্রাহ্মী লিপি', 'খরোষ্ঠী লিপি', 'দেবনাগরী লিপি', 'আরবীয় লিপি'],
    correctAnswer: 'ব্রাহ্মী লিপি',
    explanation: 'ভারতীয় প্রাচীন ব্রাহ্মী লিপির পূর্ব রূপ কুটিল লিপি থেকে পর্যায়ক্রমে বাংলা লিপির উদ্ভব ঘটেছে।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষাতত্ত্ব',
    difficulty: 'beginner',
  },
  {
    questionText: 'সাধু ভাষা ও চলিত ভাষার মূল পার্থক্য কোন পদে দেখা যায়?',
    type: 'multiple-choice',
    options: ['সর্বনাম ও ক্রিয়া পদে', 'বিশেষ্য ও বিশেষণে', 'অব্যয় ও বিশেষ্যে', 'উপসর্গে ও অনুসর্গে'],
    correctAnswer: 'সর্বনাম ও ক্রিয়া পদে',
    explanation: 'সাধু ও চলিত ভাষার রূপভেদ প্রধানত ক্রিয়া পদ ও সর্বনাম পদের সংক্ষিপ্ত ও পূর্ণাঙ্গ রূপের মধ্যে প্রতিফলিত হয় (যেমন: তাহার/তার, করিতেছিল/করছিল)।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষা রীতি',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি চলিত ভাষার বৈশিষ্ট্য নয়?',
    type: 'multiple-choice',
    options: ['তৎসম শব্দের প্রাচুর্য ও গুরুগম্ভীরতা', 'সহজবোধ্য ও পরিবর্তনশীল', 'সংক্ষিপ্ত ক্রিয়াপদ', 'তদ্ভব শব্দের আধিক্য'],
    correctAnswer: 'তৎসম শব্দের প্রাচুর্য ও গুরুগম্ভীরতা',
    explanation: 'তৎসম শব্দের আধিক্য ও গুরুগম্ভীরতা সাধু ভাষার বৈশিষ্ট্য, চলিত ভাষার নয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষা রীতি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘পকেটমার’ কোন শ্রেণীর শব্দ?',
    type: 'multiple-choice',
    options: ['মিশ্র শব্দ (ইংরেজি + বাংলা)', 'দেশি শব্দ', 'তৎসম শব্দ', 'ফারসি শব্দ'],
    correctAnswer: 'মিশ্র শব্দ (ইংরেজি + বাংলা)',
    explanation: 'পকেট (ইংরেজি) + মার (বাংলা) = পকেটমার, এটি একটি মিশ্র শব্দ। হেড-মৌলভী (ইংরেজি + ফারসি), শাক-সবজি (তৎসম + ফারসি)।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দ ভাণ্ডার',
    difficulty: 'beginner',
  },
  {
    questionText: '‘গবেষণা’ শব্দের সঠিক সন্ধি বিচ্ছেদ কোনটি?',
    type: 'multiple-choice',
    options: ['গো + এষণা', 'গব + এষণা', 'গো + ষণা', 'গবে + ষণা'],
    correctAnswer: 'গো + এষণা',
    explanation: 'ও-কারের পর অন্য স্বরবর্ণ থাকলে ‘ও’ স্থলে ‘অব’ হয়। গো + এষণা = গবেষণা।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘বিদ্যালয়’ কোন সন্ধির উদাহরণ?',
    type: 'multiple-choice',
    options: ['স্বরসন্ধি', 'ব্যঞ্জনসন্ধি', 'বিসর্গসন্ধি', 'নিপাতনে সিদ্ধ সন্ধি'],
    correctAnswer: 'স্বরসন্ধি',
    explanation: 'বিদ্যা (আ) + আলয় (আ) = বিদ্যালয় (আ + আ = আ)। স্বরবর্ণের সাথে স্বরবর্ণের মিলনে স্বরসন্ধি হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'সন্ধি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘যিনি বিদ্বান তিনি সর্বত্র পূজিত হন’—এটি কোন ধরনের বাক্য?',
    type: 'multiple-choice',
    options: ['মিশ্র বা জটিল বাক্য', 'সরল বাক্য', 'যৌগিক বাক্য', 'প্রশ্নবোধক বাক্য'],
    correctAnswer: 'মিশ্র বা জটিল বাক্য',
    explanation: 'যে বাক্যে একটি প্রধান খণ্ডবাক্য এবং এক বা একাধিক আশ্রিত বাক্য সাপেক্ষভাবে যুক্ত থাকে তাকে জটিল বা মিশ্র বাক্য বলে।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য প্রকরণ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘তিনি ধনী কিন্তু কৃপণ’—এটি কোন ধরনের বাক্য?',
    type: 'multiple-choice',
    options: ['যৌগিক বাক্য', 'সরল বাক্য', 'জটিল বাক্য', 'ভাববাচ্য বাক্য'],
    correctAnswer: 'যৌগিক বাক্য',
    explanation: 'পরস্পর নিরপেক্ষ দুই বা ততোধিক সরল বা জটিল বাক্য যখন অব্যয় (এবং, কিন্তু, অথচ, বা) দ্বারা যুক্ত হয় তাকে যৌগিক বাক্য বলে।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য প্রকরণ',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি সার্থক বাক্যের কয়টি গুণ থাকা আবশ্যক?',
    type: 'multiple-choice',
    options: ['৩টি (আকাঙ্ক্ষা, আসত্তি, যোগ্যতা)', '২টি', '৪টি', '৫টি'],
    correctAnswer: '৩টি (আকাঙ্ক্ষা, আসত্তি, যোগ্যতা)',
    explanation: 'একটি আদর্শ বাক্যের তিনটি অপরিহার্য গুণ থাকে: আকাঙ্ক্ষা, আসত্তি (পদের সন্নিবেশ) এবং যোগ্যতা।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য প্রকরণ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘গরু আকাশে উড়ে’—বাক্যটিতে কোন গুণের অভাব রয়েছে?',
    type: 'multiple-choice',
    options: ['যোগ্যতা', 'আকাঙ্ক্ষা', 'আসত্তি', 'গুরুচণ্ডালী'],
    correctAnswer: 'যোগ্যতা',
    explanation: 'বাক্যস্থিত পদসমূহের বাস্তব অর্থসঙ্গতি ও বিশ্বাসযোগ্যতাকে যোগ্যতা বলে। গরুর ওড়ার ক্ষমতা না থাকায় এটি যোগ্যতাহীন বাক্য।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাক্য প্রকরণ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘অগ্নি’ শব্দের সমার্থক নয় কোনটি?',
    type: 'multiple-choice',
    options: ['অম্বু', 'অনল', 'পাবক', 'হুতাশন'],
    correctAnswer: 'অম্বু',
    explanation: 'অনল, পাবক, হুতাশন, বহ্নি, বৈশ্বানর হলো আগুনের সমার্থক। ‘অম্বু’ অর্থ পানি বা জল।',
    points: 1,
    subject: 'Bangla',
    topic: 'সমার্থক শব্দ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘হাতির ডাক’ কে এককথায় কী বলে?',
    type: 'multiple-choice',
    options: ['বৃংহণ বা বৃংহিত', 'হ্রেষা', 'রোদন', 'গর্জন'],
    correctAnswer: 'বৃংহণ বা বৃংহিত',
    explanation: 'হাতির ডাক = বৃংহণ। ঘোড়ার ডাক = হ্রেষা। কোকিলের ডাক = কুহু। ময়ূরের ডাক = কেকা। কুকুরের ডাক = বুক্কন।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘ঘোড়ার ডাক’ কে এককথায় কী বলে?',
    type: 'multiple-choice',
    options: ['হ্রেষা', 'বৃংহণ', 'কেকা', 'চিঁহি'],
    correctAnswer: 'হ্রেষা',
    explanation: 'ঘোড়ার ডাককে সংস্কৃত ব্যাকরণে ‘হ্রেষা’ বলা হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'এককথায় প্রকাশ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘উর্ণনাভ’ শব্দটির সঠিক অর্থ কী?',
    type: 'multiple-choice',
    options: ['মাকড়সা', 'উটপাখি', 'মৌমাছি', 'তিমি মাছ'],
    correctAnswer: 'মাকড়সা',
    explanation: 'উর্ণা (জাল) নাভিতে যার = উর্ণনাভ বা মাকড়সা। এটি বহুব্রীহি সমাসবদ্ধ পদ।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দার্থ ও পরিভাষা',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘মার্জার’ শব্দের অর্থ কী?',
    type: 'multiple-choice',
    options: ['বিড়াল', 'বানর', 'ময়ূর', 'মৃগ'],
    correctAnswer: 'বিড়াল',
    explanation: 'মার্জার অর্থ বিড়াল। বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের কমলাকান্তের দপ্তরে বিখ্যাত রম্যরচনা হলো ‘বিড়াল’ বা মার্জার কথা।',
    points: 1,
    subject: 'Bangla',
    topic: 'শব্দার্থ ও সাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: '‘কবর’ কবিতার রচয়িতা কে এবং এটি কোন ছন্দে রচিত?',
    type: 'multiple-choice',
    options: [
      'পল্লীকবি জসীমউদ্দীন; মাত্রাবৃত্ত ছন্দ',
      'কাজী নজরুল ইসলাম; অক্ষরবৃত্ত ছন্দ',
      'রবীন্দ্রনাথ ঠাকুর; স্বরবৃত্ত ছন্দ',
      'জীবনানন্দ দাশ; গদ্যছন্দ',
    ],
    correctAnswer: 'পল্লীকবি জসীমউদ্দীন; মাত্রাবৃত্ত ছন্দ',
    explanation: '‘এখানে তোর দাদির কবর ডালিম গাছের তলে’—জসীমউদ্দীনের বিখ্যাত ‘কবর’ কবিতাটি মাত্রাবৃত্ত ছন্দে রচিত তাঁর ‘রাখালী’ কাব্যগ্রন্থের অন্তর্ভুক্ত।',
    points: 1,
    subject: 'Bangla',
    topic: 'কবিতা ও ছন্দ',
    difficulty: 'beginner',
  },
  {
    questionText: 'মুনীর চৌধুরী রচিত ‘কবর’ নাটকটির প্রেক্ষাপট কী?',
    type: 'multiple-choice',
    options: [
      '১৯৫২ সালের ভাষা আন্দোলন',
      '১৯৭১ সালের মুক্তিযুদ্ধ',
      '১৯৬৯ এর গণঅভ্যুত্থান',
      '১৯৪৩ এর দুর্ভিক্ষ',
    ],
    correctAnswer: '১৯৫২ সালের ভাষা আন্দোলন',
    explanation: 'ভাষা আন্দোলনের প্রেক্ষাপটে ঢাকা কেন্দ্রীয় কারাগারে রাজবন্দী অবস্থায় ১৯৫৩ সালে মুনীর চৌধুরী আলোড়ন সৃষ্টিকারী ‘কবর’ একাঙ্ক নাটক রচনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'নাটক',
    difficulty: 'beginner',
  },
  {
    questionText: '‘শামসুর রাহমান’ রচিত মুক্তিযুদ্ধভিত্তিক বিখ্যাত কবিতা কোনটি?',
    type: 'multiple-choice',
    options: [
      'তোমাকে পাওয়ার জন্যে, হে স্বাধীনতা',
      'কিশোর কবি',
      'বিদ্রোহী',
      'রূপসী বাংলা',
    ],
    correctAnswer: 'তোমাকে পাওয়ার জন্যে, হে স্বাধীনতা',
    explanation: '‘তোমাকে পাওয়ার জন্যে, হে স্বাধীনতা’ এবং ‘স্বাধীনতা তুমি’ কবি শামসুর রাহমানের ‘বন্দী শিবির থেকে’ (১৯৭২) কাব্যগ্রন্থের অমর সৃষ্টি।',
    points: 1,
    subject: 'Bangla',
    topic: 'মুক্তিযুদ্ধ সাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: '‘বাংলা সাহিত্যের ইতিবৃত্ত’ গ্রন্থের যৌথ রচয়িতা কারা?',
    type: 'multiple-choice',
    options: [
      'ড. মুহম্মদ এনামুল হক ও ড. মুহম্মদ শহীদুল্লাহ',
      'মুহম্মদ আব্দুল হাই ও সৈয়দ আলী আহসান',
      'সুকুমার সেন ও সুনীতিকুমার চট্টোপাধ্যায়',
      'অসিতকুমার বন্দ্যোপাধ্যায় ও দীনেশচন্দ্র সেন',
    ],
    correctAnswer: 'মুহম্মদ আব্দুল হাই ও সৈয়দ আলী আহসান',
    explanation: 'ঢাকা বিশ্ববিদ্যালয়ের খ্যাতনামা পণ্ডিত মুহম্মদ আব্দুল হাই এবং সৈয়দ আলী আহসান যৌথভাবে ‘বাংলা সাহিত্যের ইতিবৃত্ত’ রচনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'সাহিত্য ইতিহাস',
    difficulty: 'advanced',
  },
  {
    questionText: '‘ওরা কদম আলী’ এবং ‘ইবলিশ’ নাটকের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['মামুনুর রশীদ', 'সেলিম আল দীন', 'আব্দুল্লাহ আল মামুন', 'সৈয়দ শামসুল হক'],
    correctAnswer: 'মামুনুর রশীদ',
    explanation: 'নাট্যকার মামুনুর রশীদ শ্রেণীসংগ্রাম ও অধিকার আদায়ের প্রেক্ষাপটে ‘ওরা কদম আলী’, ‘ইবলিশ’, ‘গিনিপিগ’ রচনা করেন।',
    points: 1,
    subject: 'Bangla',
    topic: 'নাটক',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘কীত্তনখোলা’ ও ‘কেরামত মঙ্গল’ নাটকের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['সেলিম আল দীন', 'মুনীর চৌধুরী', 'মামুনুর রশীদ', 'দ্বিজেন্দ্রলাল রায়'],
    correctAnswer: 'সেলিম আল দীন',
    explanation: 'দ্বৈতাদ্বৈতবাদী নাট্যরীতির প্রবক্তা সেলিম আল দীন রচিত বিখ্যাত নাটক ‘কীত্তনখোলা’, ‘কেরামত মঙ্গল’, ‘চাকা’ ও ‘হরগজ’।',
    points: 1,
    subject: 'Bangla',
    topic: 'নাটক',
    difficulty: 'intermediate',
  },
  {
    questionText: 'রবীন্দ্রনাথ ঠাকুরের প্রথম প্রকাশিত কাব্যগ্রন্থ কোনটি?',
    type: 'multiple-choice',
    options: ['বনফুল', 'কবিকাহিনী', 'ভানুসিংহ ঠাকুরের পদাবলী', 'সন্ধ্যাসংগীত'],
    correctAnswer: 'কবিকাহিনী',
    explanation: '১৮৭৮ সালে গ্রন্থাকারে প্রকাশিত রবীন্দ্রনাথ ঠাকুরের প্রথম কাব্যগ্রন্থ ‘কবিকাহিনী’। তাঁর রচিত প্রথম প্রকাশিত কবিতা ‘হিন্দু মেলার উপহার’ (১৮৭৫)।',
    points: 1,
    subject: 'Bangla',
    topic: 'রবীন্দ্রনাথ ঠাকুর',
    difficulty: 'intermediate',
  },
  {
    questionText: 'কাজী নজরুল ইসলামের প্রথম প্রকাশিত কাব্যগ্রন্থ কোনটি?',
    type: 'multiple-choice',
    options: ['অগ্নিবীণা (১৯২২)', 'বিষের বাঁশী', 'ভাঙার গান', 'দোলনচাঁপা'],
    correctAnswer: 'অগ্নিবীণা (১৯২২)',
    explanation: '১৯২২ সালে প্রকাশিত ‘অগ্নিবীণা’ নজরুলের প্রথম কাব্যগ্রন্থ। এতে প্রলয়োল্লাস, বিদ্রোহী, রক্তাম্বরধারিণী মা প্রভৃতি বিখ্যাত ১২টি কবিতা রয়েছে।',
    points: 1,
    subject: 'Bangla',
    topic: 'কাজী নজরুল ইসলাম',
    difficulty: 'beginner',
  },
  {
    questionText: 'নজরুলের ‘বিদ্রোহী’ কবিতাটি প্রথম কোন পত্রিকায় প্রকাশিত হয়?',
    type: 'multiple-choice',
    options: ['বিজলী (১৯২২)', 'ধূমকেতু', 'সওগাত', 'লাঙল'],
    correctAnswer: 'বিজলী (১৯২২)',
    explanation: '১৯২২ সালের ৬ই জানুয়ারি মুজাফফর আহমদ ও অবনীভূষণ রায়ের সাপ্তাহিক ‘বিজলী’ পত্রিকায় প্রথম ‘বিদ্রোহী’ কবিতা প্রকাশিত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'কাজী নজরুল ইসলাম',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘পায়ের আওয়াজ পাওয়া যায়’ সৈয়দ শামসুল হকের কোন ধরনের রচনা?',
    type: 'multiple-choice',
    options: ['কাব্যনাট্য (মুক্তিযুদ্ধভিত্তিক)', 'উপন্যাস', 'ঐতিহাসিক মহাকাব্য', 'ছোটগল্প সংকলন'],
    correctAnswer: 'কাব্যনাট্য (মুক্তিযুদ্ধভিত্তিক)',
    explanation: 'সৈয়দ শামসুল হক রচিত মুক্তিযুদ্ধভিত্তিক বিখ্যাত পদ্যনাটক বা কাব্যনাট্য হলো ‘পায়ের আওয়াজ পাওয়া যায়’। তাঁর অপর কাব্যনাটক ‘নুরলদীনের সারাজীবন’।',
    points: 1,
    subject: 'Bangla',
    topic: 'মুক্তিযুদ্ধ সাহিত্য',
    difficulty: 'beginner',
  },
  {
    questionText: '‘জাগো বাহে, কোনঠে সবায়!’—চরণটি সৈয়দ শামসুল হকের কোন নাটকের সংলাপ?',
    type: 'multiple-choice',
    options: ['নুরলদীনের সারাজীবন', 'পায়ের আওয়াজ পাওয়া যায়', 'গণনায়ক', 'ঈর্ষা'],
    correctAnswer: 'নুরলদীনের সারাজীবন',
    explanation: 'রংপুরের কৃষক বিদ্রোহের ঐতিহাসিক নায়ক নূরুলদীনকে নিয়ে রচিত অমর কাব্যনাটক ‘নুরলদীনের সারাজীবন’।',
    points: 1,
    subject: 'Bangla',
    topic: 'নাটক',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা একাডেমি কত সালে প্রতিষ্ঠিত হয়?',
    type: 'multiple-choice',
    options: ['১৯৫৫ সালের ৩রা ডিসেম্বর', '১৯৫২ সালের ২১শে ফেব্রুয়ারি', '১৯৫৪ সালের ৮ই মে', '১৯৬০ সালের পহেলা বৈশাখ'],
    correctAnswer: '১৯৫৫ সালের ৩রা ডিসেম্বর',
    explanation: 'ভাষা আন্দোলনের প্রত্যক্ষ ফসল হিসেবে ১৯৫৫ সালের ৩রা ডিসেম্বর বর্ধমান হাউজে বাংলা একাডেমি প্রতিষ্ঠিত হয়। প্রথম পরিচালক ছিলেন ড. এনামুল হক।',
    points: 1,
    subject: 'Bangla',
    topic: 'প্রতিষ্ঠান ও ইতিহাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি ঈশ্বরচন্দ্র বিদ্যাসাগরের মৌলিক রচনা?',
    type: 'multiple-choice',
    options: ['প্রভাবতী সম্ভাষণ', 'বেতাল পঞ্চবিংশতি', 'শকুন্তলা', 'সীতার বনবাস'],
    correctAnswer: 'প্রভাবতী সম্ভাষণ',
    explanation: 'বিদ্যাসাগরের অনূদিত গ্রন্থ অনেক হলেও তাঁর একমাত্র মৌলিক শোকগদ্য হলো ‘প্রভাবতী সম্ভাষণ’।',
    points: 1,
    subject: 'Bangla',
    topic: 'ঈশ্বরচন্দ্র বিদ্যাসাগর',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘সঞ্চয়িতা’ কোন কবির কাব্য সংকলন?',
    type: 'multiple-choice',
    options: ['রবীন্দ্রনাথ ঠাকুর', 'কাজী নজরুল ইসলাম', 'জীবনানন্দ দাশ', 'সত্যেন্দ্রনাথ দত্ত'],
    correctAnswer: 'রবীন্দ্রনাথ ঠাকুর',
    explanation: '‘সঞ্চয়িতা’ হলো রবীন্দ্রনাথ ঠাকুরের কবিতার সংকলন; আর ‘সঞ্চিতা’ হলো কাজী নজরুল ইসলামের কবিতার সংকলন। বিসিএসে বারবার আসা কনফিউজিং প্রশ্ন।',
    points: 1,
    subject: 'Bangla',
    topic: 'কাব্য সংকলন',
    difficulty: 'beginner',
  },
  {
    questionText: '‘বত্রিশ সিংহাসন’ কার লেখা?',
    type: 'multiple-choice',
    options: ['মৃত্যুঞ্জয় বিদ্যালঙ্কার', 'রামরাম বসু', 'উইলিয়াম কেরি', 'ঈশ্বরচন্দ্র বিদ্যাসাগর'],
    correctAnswer: 'মৃত্যুঞ্জয় বিদ্যালঙ্কার',
    explanation: 'ফোর্ট উইলিয়াম কলেজের পণ্ডিত মৃত্যুঞ্জয় বিদ্যালঙ্কার ১৮০২ সালে ‘বত্রিশ সিংহাসন’ রচনা করেন। তাঁর অন্যান্য গ্রন্থ: রাজাবলি, প্রবোধ চন্দ্রিকা।',
    points: 1,
    subject: 'Bangla',
    topic: 'ফোর্ট উইলিয়াম কলেজ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'বাংলা ভাষায় প্রকাশিত প্রথম সাময়িকপত্র কোনটি?',
    type: 'multiple-choice',
    options: ['দিকদর্শন (১৮১৮)', 'সমাচার দর্পণ', 'বঙ্গদর্শন', 'সংবাদ প্রভাকর'],
    correctAnswer: 'দিকদর্শন (১৮১৮)',
    explanation: '১৮১৮ সালের এপ্রিল মাসে শ্রীরামপুর ব্যাপটিস্ট মিশন থেকে জন ক্লার্ক মার্শম্যানের সম্পাদনায় প্রথম মাসিক সাময়িকপত্র ‘দিকদর্শন’ প্রকাশিত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'সংবাদপত্র ও সাময়িকী',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাঙালি পরিচালিত প্রথম সংবাদপত্র কোনটি?',
    type: 'multiple-choice',
    options: ['বেঙ্গল গেজেটি (১৮১৮)', 'সমাচার দর্পণ', 'সংবাদ কৌমুদী', 'তত্ত্ববোধিনী'],
    correctAnswer: 'বেঙ্গল গেজেটি (১৮১৮)',
    explanation: 'গঙ্গাকিশোর ভট্টাচার্যের সম্পাদনায় ১৮১৮ সালে প্রকাশিত ‘বেঙ্গল গেজেটি’ হলো বাঙালি পরিচালিত প্রথম সংবাদপত্র।',
    points: 1,
    subject: 'Bangla',
    topic: 'সংবাদপত্র ও সাময়িকী',
    difficulty: 'intermediate',
  },
  {
    questionText: 'প্রথম বাংলা দৈনিক সংবাদপত্র কোনটি?',
    type: 'multiple-choice',
    options: ['সংবাদ প্রভাকর (১৮৩৯)', 'সমাচার দর্পণ', 'ইন্ডিয়ান মিরর', 'আজাদ'],
    correctAnswer: 'সংবাদ প্রভাকর (১৮৩৯)',
    explanation: 'ঈশ্বরচন্দ্র গুপ্তের সম্পাদনায় ১৮৩১ সালে সাপ্তাহিক হিসেবে এবং ১৮৩৯ সালে বাংলা সাহিত্যের প্রথম দৈনিক সংবাদপত্র হিসেবে ‘সংবাদ প্রভাকর’ প্রকাশিত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'সংবাদপত্র ও সাময়িকী',
    difficulty: 'beginner',
  },
  {
    questionText: '‘সবুজপত্র’ পত্রিকাটি কত সালে প্রকাশিত হয় এবং এর সম্পাদক কে ছিলেন?',
    type: 'multiple-choice',
    options: ['১৯১৪ সালে প্রমথ চৌধুরী', '১৯২৩ সালে দীনেশচন্দ্র সেন', '১৮৭২ সালে বঙ্কিমচন্দ্র', '১৯০৫ সালে রবীন্দ্রনাথ ঠাকুর'],
    correctAnswer: '১৯১৪ সালে প্রমথ চৌধুরী',
    explanation: 'বাংলা সাহিত্যে চলিত রীতির আন্দোলনের অগ্রদূত প্রমথ চৌধুরী ১৯১৪ সালে ‘সবুজপত্র’ সম্পাদনা করেন। তাঁর ছদ্মনাম ছিল ‘বীরবল’।',
    points: 1,
    subject: 'Bangla',
    topic: 'সংবাদপত্র ও সাময়িকী',
    difficulty: 'beginner',
  },
  {
    questionText: '‘গড্ডলিকা প্রবাহ’ বাগধারায় ‘গড্ডল’ শব্দের প্রকৃত অর্থ কী?',
    type: 'multiple-choice',
    options: ['ভেড়া', 'স্রোত', 'হাঁস', 'গরু'],
    correctAnswer: 'ভেড়া',
    explanation: '‘গড্ডল’ শব্দের অর্থ ভেড়া। ভেড়ার পালের একটি যেদিকে যায় অন্যগুলো অন্ধের মতো সেদিকে ধাবিত হয়, সেখান থেকেই ‘অন্ধ অনুকরণ’ অর্থে গড্ডলিকা প্রবাহ।',
    points: 1,
    subject: 'Bangla',
    topic: 'বাগধারা ও শব্দার্থ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘সন্ধ্যাভাষা’ কোন সাহিত্যের ভাষার সাথে সম্পৃক্ত?',
    type: 'multiple-choice',
    options: ['চর্যাপদ', 'শ্রীকৃষ্ণকীর্তন', 'মঙ্গলকাব্য', 'বৈষ্ণব পদাবলী'],
    correctAnswer: 'চর্যাপদ',
    explanation: 'চর্যাপদের ভাষাকে আলো-আঁধারি বা দ্ব্যর্থবোধক আধ্যাত্মিক ভাষা বলা হয়, যার নাম ‘সন্ধ্যাভাষা’ বা সান্ধ্যভাষা।',
    points: 1,
    subject: 'Bangla',
    topic: 'চর্যাপদ',
    difficulty: 'beginner',
  },
  {
    questionText: 'বাংলা ভাষার উৎপত্তি কোন অপভ্রংশ থেকে ড. মুহম্মদ শহীদুল্লাহর মতে?',
    type: 'multiple-choice',
    options: ['গৌড় অপভ্রংশ', 'মাগধী অপভ্রংশ', 'শৌরসেনী অপভ্রংশ', 'পৈশাচী অপভ্রংশ'],
    correctAnswer: 'গৌড় অপভ্রংশ',
    explanation: 'ড. মুহম্মদ শহীদুল্লাহর মতে গৌড়ী প্রাকৃত ও গৌড় অপভ্রংশ থেকে বাংলা ভাষার জন্ম। ড. সুনীতিকুমার চট্টোপাধ্যায়ের মতে মাগধী অপভ্রংশ থেকে।',
    points: 1,
    subject: 'Bangla',
    topic: 'ভাষাতত্ত্ব',
    difficulty: 'intermediate',
  },
  {
    questionText: 'চর্যাপদ মূলত কোন ছন্দে রচিত?',
    type: 'multiple-choice',
    options: ['মাত্রাবৃত্ত ছন্দ', 'অক্ষরবৃত্ত ছন্দ', 'স্বরবৃত্ত ছন্দ', 'অমিত্রাক্ষর ছন্দ'],
    correctAnswer: 'মাত্রাবৃত্ত ছন্দ',
    explanation: 'অধিকাংশ ভাষাতত্ত্ববিদের মতে চর্যাপদের পদগুলো পাদাকুলক জাতীয় প্রাচীন মাত্রাবৃত্ত ছন্দে রচিত গান।',
    points: 1,
    subject: 'Bangla',
    topic: 'ছন্দ',
    difficulty: 'intermediate',
  },
  {
    questionText: '‘আমার দেখা নয়াচীন’ গ্রন্থের রচয়িতা কে?',
    type: 'multiple-choice',
    options: ['বঙ্গবন্ধু শেখ মুজিবুর রহমান', 'আবুল মনসুর আহমদ', 'মওলানা ভাসানী', 'মুহাম্মদ মনসুরউদ্দীন'],
    correctAnswer: 'বঙ্গবন্ধু শেখ মুজিবুর রহমান',
    explanation: '১৯৫২ সালের অক্টোবরে শান্তি সম্মেলনে চীন ভ্রমণের অভিজ্ঞতা নিয়ে বঙ্গবন্ধু শেখ মুজিবুর রহমান ‘আমার দেখা নয়াচীন’ রচনা করেন (২০২০ সালে প্রকাশিত)।',
    points: 1,
    subject: 'Bangla',
    topic: 'আত্মজীবনী ও ভ্রমণ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘অসমাপ্ত আত্মজীবনী’ কার রচিত গ্রন্থ এবং এটি কত সালে প্রকাশিত হয়?',
    type: 'multiple-choice',
    options: ['বঙ্গবন্ধু শেখ মুজিবুর রহমান (২০১২ সালে)', 'তাজউদ্দীন আহমদ (২০১৪ সালে)', 'শেরে বাংলা এ কে ফজলুল হক (২০১০ সালে)', 'হোসেন শহীদ সোহরাওয়ার্দী (২০১৫ সালে)'],
    correctAnswer: 'বঙ্গবন্ধু শেখ মুজিবুর রহমান (২০১২ সালে)',
    explanation: 'বঙ্গবন্ধু শেখ মুজিবুর রহমানের লেখা ‘অসমাপ্ত আত্মজীবনী’ ২০১২ সালের জুনে ইউপিএল কর্তৃক প্রকাশিত হয়।',
    points: 1,
    subject: 'Bangla',
    topic: 'ইতিহাস ও সাহিত্য',
    difficulty: 'beginner',
  },
];

