import { IJobQuestionItem } from './banglaQuestions.js';

export const bankJobQuestions: IJobQuestionItem[] = [
  // Commercial & Financial Banking Questions (Bangladesh Bank AD, Combined 8/9 Banks, Officer)
  {
    questionText: 'What is the full form of RTGS in banking transactions?',
    type: 'multiple-choice',
    options: [
      'Real Time Gross Settlement',
      'Real Time General Settlement',
      'Rapid Transfer Gross Security',
      'Retail Trade Guaranteed System',
    ],
    correctAnswer: 'Real Time Gross Settlement',
    explanation: 'RTGS enables instantaneous settlement of high-value interbank fund transfers on an order-by-order basis.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Banking Terms & Operations',
    difficulty: 'beginner',
  },
  {
    questionText: 'What is the minimum capital requirement (CRAR) under Basel III framework for banks in Bangladesh?',
    type: 'multiple-choice',
    options: ['10% plus 2.5% conservation buffer', '8%', '15%', '12%'],
    correctAnswer: '10% plus 2.5% conservation buffer',
    explanation: 'Under Bangladesh Bank Basel III guidelines, banks maintain 10% Capital to Risk-weighted Assets Ratio (CRAR) plus a 2.5% Capital Conservation Buffer.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Central Banking & Regulations',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Which rate is the rate at which the central bank lends money to commercial banks against government securities?',
    type: 'multiple-choice',
    options: ['Repo Rate (Repurchase Rate)', 'Reverse Repo Rate', 'Bank Rate', 'Call Money Rate'],
    correctAnswer: 'Repo Rate (Repurchase Rate)',
    explanation: 'The Repo (Repurchase Agreement) rate is the key monetary policy rate at which Bangladesh Bank injects liquidity to commercial banks against securities.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Monetary Economics',
    difficulty: 'intermediate',
  },
  {
    questionText: 'A trader marked an item 30% above the cost price and allowed a discount of 10% on the marked price. What is his percentage profit?',
    type: 'multiple-choice',
    options: ['17%', '20%', '15%', '18%'],
    correctAnswer: '17%',
    explanation: 'Let CP = 100. MP = 130. Discount 10% of 130 = 13. SP = 130 - 13 = 117. Profit = 117 - 100 = 17%.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Bank Quantitative Aptitude',
    difficulty: 'beginner',
  },
  {
    questionText: 'A sum of money compounded annually doubles itself in 4 years. In how many years will it become 8 times itself at the same rate of interest?',
    type: 'multiple-choice',
    options: ['12 years', '16 years', '8 years', '10 years'],
    correctAnswer: '12 years',
    explanation: 'Under compound interest: 2 = (1+r)⁴. 8 times = 2³ = [(1+r)⁴]³ = (1+r)¹². Therefore, it takes 4 × 3 = 12 years.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Bank Quantitative Aptitude',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Find the odd one out from the following group: Dollar, Euro, Rupee, Ounce, Pound.',
    type: 'multiple-choice',
    options: ['Ounce', 'Euro', 'Rupee', 'Pound'],
    correctAnswer: 'Ounce',
    explanation: 'Dollar, Euro, Rupee, and Pound are international currencies, whereas "Ounce" is a unit of weight measurement.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Analytical & Critical Reasoning',
    difficulty: 'beginner',
  },
  {
    questionText: 'ANALOGY: TELESCOPE : ASTRONOMER :: MICROSCOPE : ?',
    type: 'multiple-choice',
    options: ['Biologist', 'Geologist', 'Engineer', 'Doctor'],
    correctAnswer: 'Biologist',
    explanation: 'A telescope is an essential tool for an astronomer; similarly, a microscope is an essential tool for a biologist.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Verbal Reasoning & Analogy',
    difficulty: 'beginner',
  },
  {
    questionText: 'What is a "Bear Market" in financial and stock exchange terminology?',
    type: 'multiple-choice',
    options: [
      'A market condition where share prices are declining over a prolonged period',
      'A market where prices are rapidly climbing',
      'A market dealing exclusively in commodities',
      'An illegal black market',
    ],
    correctAnswer: 'A market condition where share prices are declining over a prolonged period',
    explanation: 'A bear market indicates falling prices and widespread pessimism, whereas a bull market signifies rising prices and optimistic investor sentiment.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Stock Market & Finance',
    difficulty: 'beginner',
  },
  {
    questionText: 'What does "NPL" stand for in banking financial statements?',
    type: 'multiple-choice',
    options: [
      'Non-Performing Loan',
      'Net Payment Liability',
      'Non-Profit Ledger',
      'National Portfolio Loan',
    ],
    correctAnswer: 'Non-Performing Loan',
    explanation: 'An NPL is a bank loan where the borrower has failed to make scheduled repayments of principal or interest for a specified period (typically 90+ days).',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Banking Terms & Operations',
    difficulty: 'beginner',
  },
  {
    questionText: 'A train 150m long moving at 60 km/h crosses another train 100m long running in the opposite direction at 40 km/h. In how many seconds do they cross each other?',
    type: 'multiple-choice',
    options: ['9 seconds', '10 seconds', '12 seconds', '8 seconds'],
    correctAnswer: '9 seconds',
    explanation: 'Relative speed in opposite directions = 60 + 40 = 100 km/h = 100 × (5/18) = 250/9 m/s. Total distance = 150 + 100 = 250m. Time = 250 / (250/9) = 9 seconds.',
    points: 1,
    subject: 'Bank Job Preparation',
    topic: 'Bank Quantitative Aptitude',
    difficulty: 'intermediate',
  },
];
