import { IJobQuestionItem } from './banglaQuestions.js';

export const englishQuestions: IJobQuestionItem[] = [
  // 1-25: Appropriate Prepositions & Fill in the Blanks (Most frequent in BCS, Banks, Teacher Recruitment)
  {
    questionText: 'He is proficient _____ English and Mathematics.',
    type: 'multiple-choice',
    options: ['in', 'at', 'with', 'on'],
    correctAnswer: 'in',
    explanation: '"Proficient in" means skilled or adept in a subject, language, or branch of learning.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'She is good _____ Mathematics, but weak in English.',
    type: 'multiple-choice',
    options: ['at', 'in', 'with', 'for'],
    correctAnswer: 'at',
    explanation: 'We use "good at" when referring to ability or skill at an activity or subject.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'The magistrate convicted the accused _____ theft.',
    type: 'multiple-choice',
    options: ['of', 'for', 'with', 'by'],
    correctAnswer: 'of',
    explanation: '"Convict of" / "accuse of" / "acquit of" always take the preposition "of".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'You should abide _____ the rules of the institution.',
    type: 'multiple-choice',
    options: ['by', 'with', 'to', 'for'],
    correctAnswer: 'by',
    explanation: '"Abide by" means to conform to, accept, or comply with rules or decisions.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'Smoking is detrimental _____ human health.',
    type: 'multiple-choice',
    options: ['to', 'for', 'at', 'in'],
    correctAnswer: 'to',
    explanation: '"Detrimental to" / "injurious to" / "harmful to" take the preposition "to".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'He refrained _____ making any controversial statement.',
    type: 'multiple-choice',
    options: ['from', 'to', 'with', 'by'],
    correctAnswer: 'from',
    explanation: '"Refrain from" / "abstain from" / "desist from" take "from".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'The committee consists _____ seven members.',
    type: 'multiple-choice',
    options: ['of', 'in', 'with', 'for'],
    correctAnswer: 'of',
    explanation: '"Consist of" means to be composed or made up of.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'True happiness consists _____ contentment.',
    type: 'multiple-choice',
    options: ['in', 'of', 'at', 'with'],
    correctAnswer: 'in',
    explanation: '"Consist in" means to lie or reside in something inherently (e.g. happiness consists in contentment).',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'intermediate',
  },
  {
    questionText: 'The patient died _____ cancer last night.',
    type: 'multiple-choice',
    options: ['of', 'from', 'by', 'for'],
    correctAnswer: 'of',
    explanation: 'A person dies "of" a disease (cancer, malaria, cholera), but dies "from" an external cause/overeating/wound.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'He died _____ over-working in the factory.',
    type: 'multiple-choice',
    options: ['from', 'of', 'by', 'with'],
    correctAnswer: 'from',
    explanation: 'Dying from an indirect or external cause such as over-work, fatigue, or wound takes "from".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'intermediate',
  },
  {
    questionText: 'The soldier died _____ his country on the battlefield.',
    type: 'multiple-choice',
    options: ['for', 'of', 'from', 'in'],
    correctAnswer: 'for',
    explanation: 'To die for a noble cause or for one\'s country takes "for".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'He died _____ poison.',
    type: 'multiple-choice',
    options: ['by', 'of', 'from', 'with'],
    correctAnswer: 'by',
    explanation: 'To die by violence, suicide, or poison takes the preposition "by".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'intermediate',
  },
  {
    questionText: 'I prefer tea _____ coffee in the morning.',
    type: 'multiple-choice',
    options: ['to', 'than', 'more than', 'over'],
    correctAnswer: 'to',
    explanation: '"Prefer ... to", "senior to", "junior to", "prior to", "inferior to" always take "to", never "than".',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'He was absorbed _____ his scientific research.',
    type: 'multiple-choice',
    options: ['in', 'at', 'with', 'on'],
    correctAnswer: 'in',
    explanation: '"Absorbed in" means deeply engrossed or immersed in work/thoughts.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'The police are looking _____ the murder case.',
    type: 'multiple-choice',
    options: ['into', 'at', 'after', 'for'],
    correctAnswer: 'into',
    explanation: '"Look into" means to investigate. "Look after" means to take care of.',
    points: 1,
    subject: 'English',
    topic: 'Phrasal Verbs',
    difficulty: 'beginner',
  },
  {
    questionText: 'He succeeded _____ passing the civil service examination.',
    type: 'multiple-choice',
    options: ['in', 'at', 'for', 'with'],
    correctAnswer: 'in',
    explanation: '"Succeed in" + gerund (verb+ing) is the correct grammatical structure.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'You must compensate him _____ the loss sustained.',
    type: 'multiple-choice',
    options: ['for', 'with', 'against', 'to'],
    correctAnswer: 'for',
    explanation: '"Compensate for" means to provide recompense for damage or loss.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'The principal presided _____ the annual prize-giving ceremony.',
    type: 'multiple-choice',
    options: ['over', 'at', 'in', 'on'],
    correctAnswer: 'over',
    explanation: '"Preside over" means to be in the position of authority in a meeting or gathering.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'He is devoid _____ common sense.',
    type: 'multiple-choice',
    options: ['of', 'from', 'in', 'with'],
    correctAnswer: 'of',
    explanation: '"Devoid of" means lacking or free from something.',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'beginner',
  },
  {
    questionText: 'She burst _____ tears upon hearing the tragic news.',
    type: 'multiple-choice',
    options: ['into', 'out', 'with', 'in'],
    correctAnswer: 'into',
    explanation: '"Burst into tears" (suddenly cry), but "burst out laughing" (suddenly laugh).',
    points: 1,
    subject: 'English',
    topic: 'Appropriate Preposition',
    difficulty: 'intermediate',
  },

  // 26-50: Subject-Verb Agreement, Conditionals & Sentence Correction
  {
    questionText: 'Neither the teacher nor the students _____ present in the auditorium.',
    type: 'multiple-choice',
    options: ['were', 'was', 'is', 'are being'],
    correctAnswer: 'were',
    explanation: 'When subjects are connected by "neither...nor" or "either...or", the verb agrees with the closer subject ("the students" = plural).',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'beginner',
  },
  {
    questionText: 'The chairman along with his board members _____ arrived.',
    type: 'multiple-choice',
    options: ['has', 'have', 'are', 'were'],
    correctAnswer: 'has',
    explanation: 'Phrases like "along with", "as well as", "together with", "accompanied by" do not change the number of the main subject ("The chairman" = singular).',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Each of the applicants _____ required to bring original certificates.',
    type: 'multiple-choice',
    options: ['is', 'are', 'were', 'have been'],
    correctAnswer: 'is',
    explanation: '"Each", "every", "either", "neither", "one" take a singular verb.',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'beginner',
  },
  {
    questionText: 'Many a student _____ failed in the preliminary screening.',
    type: 'multiple-choice',
    options: ['has', 'have', 'are', 'were'],
    correctAnswer: 'has',
    explanation: '"Many a" is followed by a singular noun and takes a singular verb ("Many a student has").',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Ten miles _____ a long distance to walk on foot.',
    type: 'multiple-choice',
    options: ['is', 'are', 'were', 'have been'],
    correctAnswer: 'is',
    explanation: 'Expressions of distance, money, periods of time, or measurement take a singular verb when considered as a unified amount.',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'beginner',
  },
  {
    questionText: 'The Arabian Nights _____ still a favorite book among readers.',
    type: 'multiple-choice',
    options: ['is', 'are', 'were', 'have been'],
    correctAnswer: 'is',
    explanation: 'Titles of single books, movies, or works of art ending in \'s\' take a singular verb.',
    points: 1,
    subject: 'English',
    topic: 'Subject-Verb Agreement',
    difficulty: 'beginner',
  },
  {
    questionText: 'If I _____ a king, I would help the poor and needy.',
    type: 'multiple-choice',
    options: ['were', 'was', 'am', 'had been'],
    correctAnswer: 'were',
    explanation: 'In second/unreal conditional sentences expressing hypothetical wishes or contrary-to-fact scenarios, "were" is used for all persons.',
    points: 1,
    subject: 'English',
    topic: 'Conditionals',
    difficulty: 'beginner',
  },
  {
    questionText: 'Had I known your contact number, I _____ you yesterday.',
    type: 'multiple-choice',
    options: ['would have phoned', 'would phone', 'will phone', 'had phoned'],
    correctAnswer: 'would have phoned',
    explanation: 'Third conditional structure: Had + subject + past participle ... would have + past participle.',
    points: 1,
    subject: 'English',
    topic: 'Conditionals',
    difficulty: 'intermediate',
  },
  {
    questionText: 'It is high time we _____ our lifestyle and bad habits.',
    type: 'multiple-choice',
    options: ['changed', 'change', 'should change', 'had changed'],
    correctAnswer: 'changed',
    explanation: 'After "It is time" or "It is high time", the following clause must take past indefinite tense (V2).',
    points: 1,
    subject: 'English',
    topic: 'Right Form of Verbs',
    difficulty: 'beginner',
  },
  {
    questionText: 'I fancy I _____ pale upon seeing the accident.',
    type: 'multiple-choice',
    options: ['turned', 'turn', 'turning', 'will turn'],
    correctAnswer: 'turned',
    explanation: 'After expressions like "I wish", "I fancy", the following verb takes past tense.',
    points: 1,
    subject: 'English',
    topic: 'Right Form of Verbs',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Scarcely had the teacher entered the classroom _____ the bell rang.',
    type: 'multiple-choice',
    options: ['when', 'than', 'then', 'as soon as'],
    correctAnswer: 'when',
    explanation: '"Hardly had... when" and "Scarcely had... when" are correlative conjunctions; "No sooner had... than".',
    points: 1,
    subject: 'English',
    topic: 'Conjunctions',
    difficulty: 'beginner',
  },
  {
    questionText: 'No sooner had we reached the railway station _____ the train departed.',
    type: 'multiple-choice',
    options: ['than', 'then', 'when', 'before'],
    correctAnswer: 'than',
    explanation: '"No sooner had ... than" is the standard correlative conjunction.',
    points: 1,
    subject: 'English',
    topic: 'Conjunctions',
    difficulty: 'beginner',
  },
  {
    questionText: 'Which sentence is grammatically correct?',
    type: 'multiple-choice',
    options: [
      'One of my friends is a doctor.',
      'One of my friends are a doctor.',
      'One of my friend is a doctor.',
      'One of my friend are doctor.',
    ],
    correctAnswer: 'One of my friends is a doctor.',
    explanation: '"One of + plural noun + singular verb" is the correct grammatical structure.',
    points: 1,
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'beginner',
  },
  {
    questionText: 'Choose the correct sentence:',
    type: 'multiple-choice',
    options: [
      'He insisted on seeing her.',
      'He insisted to see her.',
      'He insisted for seeing her.',
      'He insisted over seeing her.',
    ],
    correctAnswer: 'He insisted on seeing her.',
    explanation: '"Insist" always takes the preposition "on" followed by a gerund ("on seeing").',
    points: 1,
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'beginner',
  },
  {
    questionText: 'Which sentence is correct regarding comparative degree?',
    type: 'multiple-choice',
    options: [
      'He is senior to me by two years.',
      'He is more senior than me by two years.',
      'He is senior than me by two years.',
      'He is most senior to me by two years.',
    ],
    correctAnswer: 'He is senior to me by two years.',
    explanation: 'Latin comparatives (senior, junior, prior, superior, inferior) take "to", never "than" or "more".',
    points: 1,
    subject: 'English',
    topic: 'Degrees of Comparison',
    difficulty: 'beginner',
  },

  // 51-80: Synonyms, Antonyms, Idioms & Phrases
  {
    questionText: 'What is the synonym of "CANDID"?',
    type: 'multiple-choice',
    options: ['Frank / Outspoken', 'Deceitful', 'Secretive', 'Arrogant'],
    correctAnswer: 'Frank / Outspoken',
    explanation: '"Candid" means truthful, straightforward, and sincere.',
    points: 1,
    subject: 'English',
    topic: 'Vocabulary - Synonyms',
    difficulty: 'beginner',
  },
  {
    questionText: 'What is the antonym of "AFFLUENT"?',
    type: 'multiple-choice',
    options: ['Destitute / Impoverished', 'Wealthy', 'Prosperous', 'Opulent'],
    correctAnswer: 'Destitute / Impoverished',
    explanation: '"Affluent" means wealthy; its opposite is "destitute" or "poor".',
    points: 1,
    subject: 'English',
    topic: 'Vocabulary - Antonyms',
    difficulty: 'beginner',
  },
  {
    questionText: 'What is the synonym of "METICULOUS"?',
    type: 'multiple-choice',
    options: ['Painstaking / Thorough', 'Careless', 'Hasty', 'Superficial'],
    correctAnswer: 'Painstaking / Thorough',
    explanation: '"Meticulous" means showing great attention to detail; very careful and precise.',
    points: 1,
    subject: 'English',
    topic: 'Vocabulary - Synonyms',
    difficulty: 'intermediate',
  },
  {
    questionText: 'What is the antonym of "TRANSIENT"?',
    type: 'multiple-choice',
    options: ['Permanent / Enduring', 'Fleeting', 'Momentary', 'Brief'],
    correctAnswer: 'Permanent / Enduring',
    explanation: '"Transient" means lasting only for a short time; impermanent. Opposite is permanent.',
    points: 1,
    subject: 'English',
    topic: 'Vocabulary - Antonyms',
    difficulty: 'intermediate',
  },
  {
    questionText: 'What is the synonym of "PRAGMATIC"?',
    type: 'multiple-choice',
    options: ['Practical / Realistic', 'Idealistic', 'Theoretical', 'Impractical'],
    correctAnswer: 'Practical / Realistic',
    explanation: '"Pragmatic" means dealing with things sensibly and realistically in a practical way.',
    points: 1,
    subject: 'English',
    topic: 'Vocabulary - Synonyms',
    difficulty: 'beginner',
  },
  {
    questionText: 'What is the meaning of the idiom "A bolt from the blue"?',
    type: 'multiple-choice',
    options: ['A sudden unexpected calamity', 'A flash of lightning', 'A pleasant surprise', 'A thunderstorm'],
    correctAnswer: 'A sudden unexpected calamity',
    explanation: '"A bolt from the blue" means an unexpected and very shocking event or piece of news (বিনা মেঘে বজ্রপাত).',
    points: 1,
    subject: 'English',
    topic: 'Idioms & Phrases',
    difficulty: 'beginner',
  },
  {
    questionText: 'The idiom "At sixes and sevens" means:',
    type: 'multiple-choice',
    options: ['In a state of total confusion or disorder', 'In perfect harmony', 'Counting numbers', 'At an auction'],
    correctAnswer: 'In a state of total confusion or disorder',
    explanation: '"At sixes and sevens" signifies disorganization or state of confusion (এলোমেলো অবস্থা).',
    points: 1,
    subject: 'English',
    topic: 'Idioms & Phrases',
    difficulty: 'beginner',
  },
  {
    questionText: 'What does "Burning the candle at both ends" mean?',
    type: 'multiple-choice',
    options: ['Exhausting energy by overworking day and night', 'Lighting two candles', 'Wasting wax', 'Celebrating a party'],
    correctAnswer: 'Exhausting energy by overworking day and night',
    explanation: '"Burn the candle at both ends" means to go to bed late and get up early, overworking excessively.',
    points: 1,
    subject: 'English',
    topic: 'Idioms & Phrases',
    difficulty: 'intermediate',
  },
  {
    questionText: 'What does the idiom "Call a spade a spade" mean?',
    type: 'multiple-choice',
    options: ['To speak plainly and bluntly without beating around the bush', 'To play cards', 'To dig in a garden', 'To hide the truth'],
    correctAnswer: 'To speak plainly and bluntly without beating around the bush',
    explanation: 'Calling a spade a spade means speaking the unvarnished truth directly (স্পষ্ট ভাষায় অপ্রিয় সত্য বলা).',
    points: 1,
    subject: 'English',
    topic: 'Idioms & Phrases',
    difficulty: 'beginner',
  },
  {
    questionText: 'The phrase "Achilles\' heel" refers to:',
    type: 'multiple-choice',
    options: ['A fatal weakness or vulnerability in an otherwise strong entity', 'A strong fortress', 'A fast runner', 'A medical injury'],
    correctAnswer: 'A fatal weakness or vulnerability in an otherwise strong entity',
    explanation: 'From Greek mythology, Achilles\' heel signifies a vulnerable point or soft spot.',
    points: 1,
    subject: 'English',
    topic: 'Idioms & Phrases',
    difficulty: 'beginner',
  },
  {
    questionText: 'A person who hates or distrusts mankind is called a:',
    type: 'multiple-choice',
    options: ['Misanthrope', 'Philanthropist', 'Altruist', 'Misogynist'],
    correctAnswer: 'Misanthrope',
    explanation: 'A misanthrope hates humankind. Philanthropist loves mankind. Misogynist hates women.',
    points: 1,
    subject: 'English',
    topic: 'One Word Substitution',
    difficulty: 'beginner',
  },
  {
    questionText: 'One who knows everything is termed:',
    type: 'multiple-choice',
    options: ['Omniscient', 'Omnipotent', 'Omnipresent', 'Polyglot'],
    correctAnswer: 'Omniscient',
    explanation: 'Omniscient = all-knowing; Omnipotent = all-powerful; Omnipresent = present everywhere.',
    points: 1,
    subject: 'English',
    topic: 'One Word Substitution',
    difficulty: 'beginner',
  },
  {
    questionText: 'A remedy for all diseases or problems is known as a:',
    type: 'multiple-choice',
    options: ['Panacea', 'Placebo', 'Antibiotic', 'Vaccine'],
    correctAnswer: 'Panacea',
    explanation: '"Panacea" is a universal remedy or cure-all (সর্বব্যাধিহর মহৌষধ).',
    points: 1,
    subject: 'English',
    topic: 'One Word Substitution',
    difficulty: 'beginner',
  },
  {
    questionText: 'Which one of the following words is correctly spelt?',
    type: 'multiple-choice',
    options: ['Liaison', 'Liason', 'Liaizon', 'Liasion'],
    correctAnswer: 'Liaison',
    explanation: 'L-I-A-I-S-O-N is the correct spelling, meaning communication or cooperation.',
    points: 1,
    subject: 'English',
    topic: 'Spelling',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Which word is spelt correctly?',
    type: 'multiple-choice',
    options: ['Bureaucracy', 'Burocracy', 'Beurocracy', 'Bureaucracity'],
    correctAnswer: 'Bureaucracy',
    explanation: 'B-U-R-E-A-U-C-R-A-C-Y is the correct spelling for administrative system.',
    points: 1,
    subject: 'English',
    topic: 'Spelling',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Find the correctly spelt word:',
    type: 'multiple-choice',
    options: ['Questionnaire', 'Questionaire', 'Questionare', 'Questionnair'],
    correctAnswer: 'Questionnaire',
    explanation: 'Q-U-E-S-T-I-O-N-N-A-I-R-E has double \'n\'.',
    points: 1,
    subject: 'English',
    topic: 'Spelling',
    difficulty: 'intermediate',
  },

  // 81-110: Voice, Narration, Parts of Speech & Transformations
  {
    questionText: 'Change the voice: "Who wrote the play Hamlet?"',
    type: 'multiple-choice',
    options: [
      'By whom was the play Hamlet written?',
      'Who was written the play Hamlet by?',
      'By whom the play Hamlet was written?',
      'By who was the play Hamlet written?',
    ],
    correctAnswer: 'By whom was the play Hamlet written?',
    explanation: 'Interrogative passive with "who": By whom + auxiliary (was) + subject (the play Hamlet) + past participle (written)?',
    points: 1,
    subject: 'English',
    topic: 'Voice Change',
    difficulty: 'beginner',
  },
  {
    questionText: 'Change the voice: "Do not laugh at the poor."',
    type: 'multiple-choice',
    options: [
      'Let not the poor be laughed at.',
      'Let not the poor laughed at.',
      'The poor should not laughed at.',
      'Let the poor not being laughed at.',
    ],
    correctAnswer: 'Let not the poor be laughed at.',
    explanation: 'Imperative negative passive: Let not + object + be + past participle + preposition.',
    points: 1,
    subject: 'English',
    topic: 'Voice Change',
    difficulty: 'beginner',
  },
  {
    questionText: 'Change the voice: "Honey tastes sweet."',
    type: 'multiple-choice',
    options: [
      'Honey is sweet when it is tasted.',
      'Honey is tasted sweet.',
      'Honey was sweet when tasted.',
      'Honey tastes being sweet.',
    ],
    correctAnswer: 'Honey is sweet when it is tasted.',
    explanation: 'Quasi-passive verbs take the form: Subject + be verb + adjective + when it is + past participle.',
    points: 1,
    subject: 'English',
    topic: 'Voice Change',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Direct to Indirect: He said to me, "What are you doing?"',
    type: 'multiple-choice',
    options: [
      'He asked me what I was doing.',
      'He asked me what was I doing.',
      'He told me what I was doing.',
      'He asked that what I was doing.',
    ],
    correctAnswer: 'He asked me what I was doing.',
    explanation: 'In reported questions, wh-word remains, sentence order becomes assertive (subject before verb: I was doing).',
    points: 1,
    subject: 'English',
    topic: 'Narration',
    difficulty: 'beginner',
  },
  {
    questionText: 'The indirect speech of: The teacher said to the boy, "Honesty is the best policy."',
    type: 'multiple-choice',
    options: [
      'The teacher told the boy that honesty is the best policy.',
      'The teacher told the boy that honesty was the best policy.',
      'The teacher said that honesty had been the best policy.',
      'The teacher asked if honesty is the best policy.',
    ],
    correctAnswer: 'The teacher told the boy that honesty is the best policy.',
    explanation: 'Universal truths or habitual facts do not change their tense in indirect speech.',
    points: 1,
    subject: 'English',
    topic: 'Narration',
    difficulty: 'beginner',
  },
  {
    questionText: 'What part of speech is the word "Courageous"?',
    type: 'multiple-choice',
    options: ['Adjective', 'Noun', 'Adverb', 'Verb'],
    correctAnswer: 'Adjective',
    explanation: 'The suffix "-ous" indicates an adjective (e.g. courageous, dangerous, famous). Courage is the noun.',
    points: 1,
    subject: 'English',
    topic: 'Parts of Speech',
    difficulty: 'beginner',
  },
  {
    questionText: 'In the sentence "Still waters run deep", what part of speech is "Still"?',
    type: 'multiple-choice',
    options: ['Adjective', 'Adverb', 'Noun', 'Conjunction'],
    correctAnswer: 'Adjective',
    explanation: '"Still" qualifies the noun "waters", describing its calm/motionless state, hence it is an adjective.',
    points: 1,
    subject: 'English',
    topic: 'Parts of Speech',
    difficulty: 'intermediate',
  },
  {
    questionText: 'In "He worked hard", the word "hard" is an:',
    type: 'multiple-choice',
    options: ['Adverb', 'Adjective', 'Noun', 'Pronoun'],
    correctAnswer: 'Adverb',
    explanation: '"Hard" modifies the action verb "worked" (how did he work?), so it functions as an adverb of manner.',
    points: 1,
    subject: 'English',
    topic: 'Parts of Speech',
    difficulty: 'beginner',
  },

  // 111-150: English Literature (Authors, Periods, Shakespeare, Romantic Poets, Quotes)
  {
    questionText: 'Who is recognized as the "Father of English Poetry"?',
    type: 'multiple-choice',
    options: ['Geoffrey Chaucer', 'William Shakespeare', 'John Milton', 'Edmund Spenser'],
    correctAnswer: 'Geoffrey Chaucer',
    explanation: 'Geoffrey Chaucer (author of "The Canterbury Tales") is universally celebrated as the Father of English Literature and Poetry.',
    points: 1,
    subject: 'English',
    topic: 'English Literature',
    difficulty: 'beginner',
  },
  {
    questionText: 'Who wrote the epic poem "Paradise Lost"?',
    type: 'multiple-choice',
    options: ['John Milton', 'William Shakespeare', 'John Donne', 'Alexander Pope'],
    correctAnswer: 'John Milton',
    explanation: 'John Milton composed the blind epic "Paradise Lost" (1667) in blank verse to "justify the ways of God to men".',
    points: 1,
    subject: 'English',
    topic: 'English Literature',
    difficulty: 'beginner',
  },
  {
    questionText: '"To be, or not to be, that is the question"—This soliloquy appears in which Shakespearean tragedy?',
    type: 'multiple-choice',
    options: ['Hamlet', 'Macbeth', 'King Lear', 'Othello'],
    correctAnswer: 'Hamlet',
    explanation: 'This famous philosophical soliloquy on existence and suicide is spoken by Prince Hamlet in Act 3, Scene 1.',
    points: 1,
    subject: 'English',
    topic: 'Shakespeare',
    difficulty: 'beginner',
  },
  {
    questionText: 'In which play does the character "Lady Macbeth" appear?',
    type: 'multiple-choice',
    options: ['Macbeth', 'Hamlet', 'Julius Caesar', 'The Tempest'],
    correctAnswer: 'Macbeth',
    explanation: 'Lady Macbeth is the ambitious, ruthless wife of Macbeth who prompts him to murder King Duncan.',
    points: 1,
    subject: 'English',
    topic: 'Shakespeare',
    difficulty: 'beginner',
  },
  {
    questionText: '"All the world\'s a stage, and all the men and women merely players"—from which play is this taken?',
    type: 'multiple-choice',
    options: ['As You Like It', 'Twelfth Night', 'The Merchant of Venice', 'A Midsummer Night\'s Dream'],
    correctAnswer: 'As You Like It',
    explanation: 'Spoken by Jaques in Act 2, Scene 7 of William Shakespeare\'s pastoral comedy "As You Like It".',
    points: 1,
    subject: 'English',
    topic: 'Shakespeare',
    difficulty: 'intermediate',
  },
  {
    questionText: 'Who is known as the "Poet of Nature" in English Literature?',
    type: 'multiple-choice',
    options: ['William Wordsworth', 'John Keats', 'P.B. Shelley', 'Lord Byron'],
    correctAnswer: 'William Wordsworth',
    explanation: 'Wordsworth, pioneer of the Romantic Movement with Samuel Taylor Coleridge ("Lyrical Ballads", 1798), is known as the Poet of Nature.',
    points: 1,
    subject: 'English',
    topic: 'Romantic Period',
    difficulty: 'beginner',
  },
  {
    questionText: '"A thing of beauty is a joy forever"—Who wrote this immortal opening line?',
    type: 'multiple-choice',
    options: ['John Keats', 'William Wordsworth', 'Lord Tennyson', 'Robert Browning'],
    correctAnswer: 'John Keats',
    explanation: 'Written by John Keats (the Poet of Beauty) in his poem "Endymion" (1818).',
    points: 1,
    subject: 'English',
    topic: 'Romantic Period',
    difficulty: 'beginner',
  },
  {
    questionText: '"If Winter comes, can Spring be far behind?"—Which poem concludes with this optimistic line?',
    type: 'multiple-choice',
    options: ['Ode to the West Wind by P.B. Shelley', 'Ode to a Nightingale by Keats', 'The Solitary Reaper by Wordsworth', 'Ulysses by Tennyson'],
    correctAnswer: 'Ode to the West Wind by P.B. Shelley',
    explanation: 'Percy Bysshe Shelley concludes his revolutionary lyrical poem "Ode to the West Wind" with this celebrated rhetorical line.',
    points: 1,
    subject: 'English',
    topic: 'Romantic Period',
    difficulty: 'beginner',
  },
  {
    questionText: 'Who authored the Victorian novel "David Copperfield" and "A Tale of Two Cities"?',
    type: 'multiple-choice',
    options: ['Charles Dickens', 'Thomas Hardy', 'George Eliot', 'William Makepeace Thackeray'],
    correctAnswer: 'Charles Dickens',
    explanation: 'Charles Dickens was the preeminent novelist of the Victorian era, portraying social injustice in industrial England.',
    points: 1,
    subject: 'English',
    topic: 'Victorian Period',
    difficulty: 'beginner',
  },
  {
    questionText: 'Who wrote the landmark modernist poem "The Waste Land" (1922)?',
    type: 'multiple-choice',
    options: ['T.S. Eliot', 'W.B. Yeats', 'Ezra Pound', 'W.H. Auden'],
    correctAnswer: 'T.S. Eliot',
    explanation: 'Thomas Stearns Eliot published "The Waste Land" in 1922 and received the Nobel Prize in Literature in 1948.',
    points: 1,
    subject: 'English',
    topic: 'Modern Period',
    difficulty: 'beginner',
  },
  {
    questionText: 'The play "Arms and the Man" was written by:',
    type: 'multiple-choice',
    options: ['George Bernard Shaw', 'Oscar Wilde', 'Samuel Beckett', 'Harold Pinter'],
    correctAnswer: 'George Bernard Shaw',
    explanation: 'G.B. Shaw wrote "Arms and the Man" (satirizing romantic notions of war and heroism), "Pygmalion", and "Man and Superman".',
    points: 1,
    subject: 'English',
    topic: 'Modern Period',
    difficulty: 'beginner',
  },
  {
    questionText: 'Who wrote the novella "The Old Man and the Sea"?',
    type: 'multiple-choice',
    options: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'William Faulkner', 'John Steinbeck'],
    correctAnswer: 'Ernest Hemingway',
    explanation: 'Ernest Hemingway won the Pulitzer Prize (1953) and Nobel Prize (1954) following "The Old Man and the Sea" featuring Santiago.',
    points: 1,
    subject: 'English',
    topic: 'American Literature',
    difficulty: 'beginner',
  },
  {
    questionText: 'Which American president delivered the historic "Gettysburg Address"?',
    type: 'multiple-choice',
    options: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'Franklin D. Roosevelt'],
    correctAnswer: 'Abraham Lincoln',
    explanation: 'Abraham Lincoln delivered the Gettysburg Address in 1863 defining democracy: "government of the people, by the people, for the people".',
    points: 1,
    subject: 'English',
    topic: 'Famous Speeches & Quotes',
    difficulty: 'beginner',
  },
  {
    questionText: 'Who wrote the famous dystopian political novel "Nineteen Eighty-Four" (1984)?',
    type: 'multiple-choice',
    options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H.G. Wells'],
    correctAnswer: 'George Orwell',
    explanation: 'George Orwell (Eric Arthur Blair) authored "Nineteen Eighty-Four" (introducing Big Brother, Thought Police) and "Animal Farm".',
    points: 1,
    subject: 'English',
    topic: '20th Century Literature',
    difficulty: 'beginner',
  },
];
