import { IJobQuestionItem } from './banglaQuestions.js';

export const mathQuestions: IJobQuestionItem[] = [
  // 1-30: পাটিগণিত - শতকরা, লাভ ও ক্ষতি
  {
    questionText: 'একটি দ্রব্যের ক্রয়মূল্য ৮০০ টাকা। দ্রব্যটি ২০% লাভে বিক্রয় করা হলে বিক্রয়মূল্য কত টাকা হবে?',
    type: 'multiple-choice',
    options: ['৯৬০ টাকা', '৯৪০ টাকা', '১০০০ টাকা', '৯২০ টাকা'],
    correctAnswer: '৯৬০ টাকা',
    explanation: '২০% লাভ হলে বিক্রয়মূল্য = ক্রয়মূল্যের ১২০%। ৮০০ × (১২০/১০০) = ৯৬০ টাকা।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - লাভ ও ক্ষতি',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি ঘড়ি ৫০০ টাকায় ক্রয় করে ৪৫০ টাকায় বিক্রয় করলে শতকরা কত ক্ষতি হবে?',
    type: 'multiple-choice',
    options: ['১০%', '৮%', '১২%', '১৫%'],
    correctAnswer: '১০%',
    explanation: 'ক্ষতি = ৫০০ - ৪৫০ = ৫০ টাকা। শতকরা ক্ষতি = (৫০ / ৫০০) × ১০০% = ১০%।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - লাভ ও ক্ষতি',
    difficulty: 'beginner',
  },
  {
    questionText: 'টাকায় ৩টি করে লেবু কিনে টাকায় ২টি করে বিক্রি করলে শতকরা কত লাভ হবে?',
    type: 'multiple-choice',
    options: ['৫০%', '৩৩.৩৩%', '২৫%', '২০%'],
    correctAnswer: '৫০%',
    explanation: '১টির ক্রয়মূল্য = ১/৩ টাকা, ১টির বিক্রয়মূল্য = ১/২ টাকা। লাভ = ১/২ - ১/৩ = ১/৬ টাকা। শতকরা লাভ = (১/৬ ÷ ১/৩) × ১০০% = ৫০%। (বিসিএস ও ব্যাংকে অতি জনপ্রিয় প্রশ্ন)',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - লাভ ও ক্ষতি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'চিনির মূল্য ২৫% বৃদ্ধি পাওয়ায় একটি পরিবার চিনির ব্যবহার শতকরা কত কমালে চিনির বাবদ খরচ অপরিবর্তিত থাকবে?',
    type: 'multiple-choice',
    options: ['২০%', '২৫%', '১৬.৬৭%', '৩০%'],
    correctAnswer: '২০%',
    explanation: 'ব্যবহার হ্রাসের শতকরা সূত্র = [বৃদ্ধি / (১০০ + বৃদ্ধি)] × ১০০% = [২৫ / ১২৫] × ১০০% = ২০%।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - শতকরা',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি সংখ্যার ৪০% এর সাথে ৪২ যোগ করলে সংখ্যাটিই পাওয়া যায়। সংখ্যাটি কত?',
    type: 'multiple-choice',
    options: ['৭০', '৮০', '৬০', '৭৫'],
    correctAnswer: '৭০',
    explanation: 'ধরি সংখ্যাটি x। ০.৪০x + ৪২ = x ⇒ ০.৬০x = ৪২ ⇒ x = ৪২ / ০.৬০ = ৭০।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - শতকরা',
    difficulty: 'beginner',
  },
  {
    questionText: 'বার্ষিক ১০% সরল সুদে কত বছরে ৫০০ টাকার সুদ ১০০ টাকা হবে?',
    type: 'multiple-choice',
    options: ['২ বছর', '৩ বছর', '১.৫ বছর', '৪ বছর'],
    correctAnswer: '২ বছর',
    explanation: 'I = Pnr ⇒ n = I / (Pr) = ১০০ / (৫০০ × ০.১০) = ১০০ / ৫০ = ২ বছর।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - সরল সুদ',
    difficulty: 'beginner',
  },
  {
    questionText: 'সরল সুদের হারে কোনো আসল ৮ বছরে সুদে-আসলে দ্বিগুণ হলে সুদের হার কত?',
    type: 'multiple-choice',
    options: ['১২.৫%', '১০%', '১৫%', '৮%'],
    correctAnswer: '১২.৫%',
    explanation: 'দ্বিগুণ হলে সুদ = আসল (P)। I = Pnr ⇒ P = P × n × r ⇒ r = ১ / n = ১ / ৮ = ১২.৫%।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - সরল সুদ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'পিতা ও পুত্রের বয়সের অনুপাত ৭ : ২ এবং তাদের বয়সের সমষ্টি ৪৫ বছর। পুত্রের বর্তমান বয়স কত?',
    type: 'multiple-choice',
    options: ['১০ বছর', '১৪ বছর', '৮ বছর', '১২ বছর'],
    correctAnswer: '১০ বছর',
    explanation: 'অনুপাত রাশিগুলোর যোগফল = ৭ + ২ = ৯। পুত্রের বয়স = ৪৫ × (২/৯) = ১০ বছর।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - অনুপাত ও বয়স',
    difficulty: 'beginner',
  },
  {
    questionText: 'ক ও খ একটি কাজ একত্রে ১২ দিনে করতে পারে। ক একা কাজটি ২০ দিনে করতে পারলে খ একা কাজটি কত দিনে সম্পন্ন করবে?',
    type: 'multiple-choice',
    options: ['৩০ দিনে', '২৫ দিনে', '৪০ দিনে', '৩৫ দিনে'],
    correctAnswer: '৩০ দিনে',
    explanation: 'খ ১ দিনে করে = ১/১২ - ১/২০ = (৫ - ৩)/৬০ = ২/৬০ = ১/৩০ অংশ। অতএব খ একা কাজটি সম্পন্ন করবে ৩০ দিনে।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - সময় ও কাজ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'একটি ট্রেন ১২০ মিটার দীর্ঘ। ট্রেনটির গতিবেগ ঘণ্টায় ৫৪ কিমি হলে একটি ল্যাম্পপোস্ট অতিক্রম করতে তার কত সেকেন্ড সময় লাগবে?',
    type: 'multiple-choice',
    options: ['৮ সেকেন্ড', '১০ সেকেন্ড', '১২ সেকেন্ড', '৬ সেকেন্ড'],
    correctAnswer: '৮ সেকেন্ড',
    explanation: 'গতিবেগ = ৫৪ × (৫/১৮) = ১৫ মিটার/সেকেন্ড। সময় = দূরত্ব / গতিবেগ = ১২০ / ১৫ = ৮ সেকেন্ড।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - সময় ও দূরত্ব',
    difficulty: 'intermediate',
  },
  {
    questionText: 'স্থির পানিতে নৌকার গতিবেগ ঘণ্টায় ১০ কিমি এবং স্রোতের গতিবেগ ঘণ্টায় ২ কিমি হলে স্রোতের অনুকূলে ২৪ কিমি যেতে কত ঘণ্টা সময় লাগবে?',
    type: 'multiple-choice',
    options: ['২ ঘণ্টা', '৩ ঘণ্টা', '২.৫ ঘণ্টা', '১.৫ ঘণ্টা'],
    correctAnswer: '২ ঘণ্টা',
    explanation: 'অনুকূলে বেগ = ১০ + ২ = ১২ কিমি/ঘণ্টা। সময় = দূরত্ব / অনুকূল বেগ = ২৪ / ১২ = ২ ঘণ্টা।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - নৌকা ও স্রোত',
    difficulty: 'beginner',
  },
  {
    questionText: 'দুটি সংখ্যার গ.সা.গু ১১ এবং ল.সা.গু ৭৭০০। একটি সংখ্যা ২৭৫ হলে অপর সংখ্যাটি কত?',
    type: 'multiple-choice',
    options: ['৩০৮', '৩০০', '৩২০', '৩৫০'],
    correctAnswer: '৩০৮',
    explanation: 'দুটি সংখ্যার গুণফল = ল.সা.গু × গ.সা.গু। অপর সংখ্যা = (১১ × ৭৭০০) / ২৭৫ = ৩০৮।',
    points: 1,
    subject: 'Mathematics',
    topic: 'পাটিগণিত - লসাগু ও গসাগু',
    difficulty: 'beginner',
  },

  // 31-60: বীজগণিত - সূত্রাবলি, মান নির্ণয়, সূচক ও লগ
  {
    questionText: 'যদি x + 1/x = 3 হয়, তবে x² + 1/x² এর মান কত?',
    type: 'multiple-choice',
    options: ['7', '9', '11', '5'],
    correctAnswer: '7',
    explanation: 'x² + 1/x² = (x + 1/x)² - 2 = 3² - 2 = 9 - 2 = 7। (বিসিএস ও সকল সরকারি চাকরির ট্রেডমার্ক প্রশ্ন)',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - মান নির্ণয়',
    difficulty: 'beginner',
  },
  {
    questionText: 'যদি a - 1/a = 2 হয়, তবে a³ - 1/a³ এর মান কত?',
    type: 'multiple-choice',
    options: ['14', '8', '12', '16'],
    correctAnswer: '14',
    explanation: 'a³ - 1/a³ = (a - 1/a)³ + 3(a)(1/a)(a - 1/a) = 2³ + 3(2) = 8 + 6 = 14।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - মান নির্ণয়',
    difficulty: 'intermediate',
  },
  {
    questionText: 'x² - 5x + 6 = 0 সমীকরণের মূলদ্বয় কী কী?',
    type: 'multiple-choice',
    options: ['2 এবং 3', '-2 এবং -3', '1 এবং 6', '-1 এবং -6'],
    correctAnswer: '2 এবং 3',
    explanation: '(x - 2)(x - 3) = 0 ⇒ x = 2 অথবা x = 3।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - দ্বিঘাত সমীকরণ',
    difficulty: 'beginner',
  },
  {
    questionText: 'log₂ 64 এর মান কত?',
    type: 'multiple-choice',
    options: ['6', '5', '8', '4'],
    correctAnswer: '6',
    explanation: '64 = 2⁶। log₂ (2⁶) = 6 log₂ 2 = 6 × 1 = 6।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - লগারিদম',
    difficulty: 'beginner',
  },
  {
    questionText: 'log₁₀ x = -2 হলে x এর মান কত?',
    type: 'multiple-choice',
    options: ['0.01', '0.1', '0.001', '100'],
    correctAnswer: '0.01',
    explanation: 'x = 10⁻² = 1 / 10² = 1 / 100 = 0.01।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - লগারিদম',
    difficulty: 'intermediate',
  },
  {
    questionText: '১ + ২ + ৩ + ... + ১০০ পর্যন্ত স্বাভাবিক ক্রমিক সংখ্যাগুলোর যোগফল কত?',
    type: 'multiple-choice',
    options: ['৫০৫০', '৫০০০', '৫১০০', '৫২৫০'],
    correctAnswer: '৫০৫০',
    explanation: 'যোগফল = n(n + 1) / 2 = 100(101) / 2 = 50 × 101 = 5050।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - সমান্তর ধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '১, ৩, ৫, ৭, ... ধারাটির n-তম পদ কোনটি?',
    type: 'multiple-choice',
    options: ['2n - 1', '2n + 1', 'n + 2', '2n'],
    correctAnswer: '2n - 1',
    explanation: 'সমান্তর ধারার প্রথম পদ a = 1, সাধারণ অন্তর d = 2। n-তম পদ = a + (n - 1)d = 1 + (n - 1)2 = 2n - 1।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - সমান্তর ধারা',
    difficulty: 'beginner',
  },
  {
    questionText: '২, ৪, ৮, ১৬, ... ধারাটির ৭ম পদ কত?',
    type: 'multiple-choice',
    options: ['১২৮', '৬৪', '২৫৬', '৯৬'],
    correctAnswer: '১২৮',
    explanation: 'গুণোত্তর ধারা: a = 2, অনুপাত r = 2। ৭ম পদ = ar⁶ = 2 × 2⁶ = 2 × 64 = 128।',
    points: 1,
    subject: 'Mathematics',
    topic: 'বীজগণিত - গুণোত্তর ধারা',
    difficulty: 'intermediate',
  },

  // 61-90: জ্যামিতি - কোণ, ত্রিভুজ, বৃত্ত ও পরিমিতি
  {
    questionText: 'একটি ত্রিভুজের তিন কোণের সমষ্টি কত?',
    type: 'multiple-choice',
    options: ['১৮০° বা দুই সমকোণ', '৩৬০°', '৯০°', '২৭০°'],
    correctAnswer: '১৮০° বা দুই সমকোণ',
    explanation: 'ইউক্লিডীয় জ্যামিতি অনুসারে যেকোনো ত্রিভুজের তিনটি অভ্যন্তরীণ কোণের সমষ্টি সর্বদা ১৮০ ডিগ্রি বা দুই সমকোণ।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - ত্রিভুজ',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি সমকোণী ত্রিভুজের ভূমি ৪ সেমি এবং লম্ব ৩ সেমি হলে অতিভুজ কত সেমি?',
    type: 'multiple-choice',
    options: ['৫ সেমি', '৭ সেমি', '৬ সেমি', '৪.৫ সেমি'],
    correctAnswer: '৫ সেমি',
    explanation: 'পিথাগোরাসের উপপাদ্য: অতিভুজ = √(ভূমি² + লম্ব²) = √(৪² + ৩²) = √(১৬ + ৯) = √২৫ = ৫ সেমি।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - পিথাগোরাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'বৃত্তের ব্যাস তিনগুণ বৃদ্ধি করলে এর ক্ষেত্রফল কতগুণ বৃদ্ধি পাবে?',
    type: 'multiple-choice',
    options: ['৯ গুণ', '৩ গুণ', '৬ গুণ', '১২ গুণ'],
    correctAnswer: '৯ গুণ',
    explanation: 'বৃত্তের ক্ষেত্রফল ব্যাস বা ব্যাসার্ধের বর্গের সমানুপাতিক (A = πr²)। ব্যাস ৩ গুণ হলে ক্ষেত্রফল ৩² = ৯ গুণ হবে।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - বৃত্ত',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি বৃত্তের ব্যাসার্ধ ৭ সেমি হলে এর পরিধি কত সেমি? (π = ২২/৭)',
    type: 'multiple-choice',
    options: ['৪৪ সেমি', '২২ সেমি', '১৫৪ সেমি', '৮৮ সেমি'],
    correctAnswer: '৪৪ সেমি',
    explanation: 'পরিধি = ২πr = ২ × (২২/৭) × ৭ = ৪৪ সেমি। (ক্ষেত্রফল = πr² = ১৫৪ বর্গ সেমি)।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - বৃত্ত',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি সামান্তরিকের ভূমি ১২ সেমি এবং উচ্চতা ৮ সেমি। এর ক্ষেত্রফল কত?',
    type: 'multiple-choice',
    options: ['৯৬ বর্গ সেমি', '৪৮ বর্গ সেমি', '১০০ বর্গ সেমি', '৪৪ বর্গ সেমি'],
    correctAnswer: '৯৬ বর্গ সেমি',
    explanation: 'সামান্তরিকের ক্ষেত্রফল = ভূমি × উচ্চতা = ১২ × ৮ = ৯৬ বর্গ সেমি।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - চতুর্ভুজ',
    difficulty: 'beginner',
  },
  {
    questionText: 'রম্বসের কর্ণদ্বয় পরস্পরকে কীভাবে ছেদ করে?',
    type: 'multiple-choice',
    options: ['সমকোণে সমদ্বিখণ্ডিত করে', 'অসমকোণে ছেদ করে', 'শুধু স্পর্শ করে', 'সমান্তরালে থাকে'],
    correctAnswer: 'সমকোণে সমদ্বিখণ্ডিত করে',
    explanation: 'রম্বস ও বর্গের কর্ণদ্বয় পরস্পরকে ৯০° বা সমকোণে সমদ্বিখণ্ডিত করে।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - চতুর্ভুজ',
    difficulty: 'intermediate',
  },
  {
    questionText: 'একটি সমবাহু ত্রিভুজের প্রতি বাহুর দৈর্ঘ্য ৪ সেমি হলে এর ক্ষেত্রফল কত বর্গ সেমি?',
    type: 'multiple-choice',
    options: ['4√3', '8√3', '16√3', '2√3'],
    correctAnswer: '4√3',
    explanation: 'সমবাহু ত্রিভুজের ক্ষেত্রফল = (√3 / 4) a² = (√3 / 4) × 4² = (√3 / 4) × 16 = 4√3 বর্গ সেমি।',
    points: 1,
    subject: 'Mathematics',
    topic: 'জ্যামিতি - সমবাহু ত্রিভুজ',
    difficulty: 'intermediate',
  },

  // 91-120: মানসিক দক্ষতা - ধারা, ঘড়ি, দিক ও যুক্তি
  {
    questionText: 'ধারার পরবর্তী সংখ্যাটি কত? ৩, ৬, ১১, ১৮, ২৭, _____?',
    type: 'multiple-choice',
    options: ['৩৮', '৩৬', '৩৯', '৪০'],
    correctAnswer: '৩৮',
    explanation: 'পার্থক্য বৃদ্ধি পাচ্ছে: ৩(+৩)=৬, ৬(+৫)=১১, ১১(+৭)=১৮, ১৮(+৯)=২৭, ২৭(+১১)=৩৮।',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - ধারা',
    difficulty: 'beginner',
  },
  {
    questionText: 'ধারার শূন্যস্থানে কী বসবে? ২, ৩, ৫, ৭, ১১, ১৩, _____?',
    type: 'multiple-choice',
    options: ['১৭', '১৫', '১৯', '১৬'],
    correctAnswer: '১৭',
    explanation: 'এটি ক্রমিক মৌলিক সংখ্যার ধারা (Prime numbers)। ১৩ এর পরবর্তী মৌলিক সংখ্যা হলো ১৭।',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - ধারা',
    difficulty: 'beginner',
  },
  {
    questionText: 'ঘড়িতে যখন ২টা ১৫ মিনিট বাজে তখন ঘণ্টার কাঁটা ও মিনিটের কাঁটার মধ্যবর্তী কোণ কত ডিগ্রি?',
    type: 'multiple-choice',
    options: ['২২.৫°', '৩০°', '১৫°', '৩৭.৫°'],
    correctAnswer: '২২.৫°',
    explanation: 'সূত্র: কোণ = |(৬০H - ১১M) / ২| = |(৬০×২ - ১১×১৫) / ২| = |(১২০ - ১৬৫) / ২| = |-৪৫ / ২| = ২২.৫°। (বিসিএস মানসিক দক্ষতায় অতি পরিচিত অঙ্ক)',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - ঘড়ি',
    difficulty: 'intermediate',
  },
  {
    questionText: 'একটি লোক উত্তর দিকে ১০ মিটার হেঁটে ডান দিকে ঘুরে ২০ মিটার গেল, তারপর আবার ডান দিকে ঘুরে ১০ মিটার গেল। সে শুরুর স্থান থেকে এখন কোন দিকে এবং কত দূরে আছে?',
    type: 'multiple-choice',
    options: ['পূর্ব দিকে ২০ মিটার', 'পশ্চিম দিকে ২০ মিটার', 'উত্তর দিকে ১০ মিটার', 'দক্ষিণ দিকে ১০ মিটার'],
    correctAnswer: 'পূর্ব দিকে ২০ মিটার',
    explanation: 'প্রথমে উত্তর ১০ মি, ডান ঘুরে (পূর্ব) ২০ মি, আবার ডান ঘুরে (দক্ষিণ) ১০ মি আসায় উলম্ব দূরত্ব ০ এবং কেবল পূর্ব দিকে ২০ মি দূরত্বে রয়েছে।',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - দিক নির্ণয়',
    difficulty: 'intermediate',
  },
  {
    questionText: 'যদি "CAT" কে সাংকেতিক কোডে "3120" লেখা হয়, তবে "DOG" কে কী লেখা হবে?',
    type: 'multiple-choice',
    options: ['4157', '4147', '3157', '4158'],
    correctAnswer: '4157',
    explanation: 'বর্ণমালার অবস্থান মান: C=3, A=1, T=20 (3120)। একইভাবে D=4, O=15, G=7 ⇒ 4157।',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - কোডিং',
    difficulty: 'beginner',
  },
  {
    questionText: 'আজ বুধবার হলে আজ থেকে ৮৪ দিন পর কী বার হবে?',
    type: 'multiple-choice',
    options: ['বুধবার', 'বৃহস্পতিবার', 'শুক্রবার', 'মঙ্গলবার'],
    correctAnswer: 'বুধবার',
    explanation: '৮৪ কে ৭ দিয়ে ভাগ করলে ভাগশেষ ০ থাকে (৮৪ = ৭ × ১২)। ভাগশেষ শূন্য হওয়ায় দিনটি একই বার অর্থাৎ বুধবারই হবে।',
    points: 1,
    subject: 'Mathematics',
    topic: 'মানসিক দক্ষতা - ক্যালেন্ডার',
    difficulty: 'beginner',
  },
];
