import { IJobQuestionItem } from './banglaQuestions.js';

export const scienceIctQuestions: IJobQuestionItem[] = [
  // 1-30: কম্পিউটার ও তথ্যপ্রযুক্তি (Hardware, Memory, OS, Networking, Cyber Security)
  {
    questionText: 'কম্পিউটারের মস্তিষ্ক বা ব্রেইন বলা হয় কোনটিকে?',
    type: 'multiple-choice',
    options: ['CPU (Central Processing Unit)', 'RAM', 'Hard Disk', 'Motherboard'],
    correctAnswer: 'CPU (Central Processing Unit)',
    explanation: 'সেন্ট্রাল প্রসেসিং ইউনিট (CPU) কম্পিউটারের সমস্ত গাণিতিক, যৌক্তিক ও নিয়ন্ত্রণ কাজ সম্পাদন করে বলে একে কম্পিউটারের মস্তিষ্ক বলা হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - কম্পিউটার হার্ডওয়্যার',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি কম্পিউটারের স্থায়ী বা নন-ভোলাটাইল (Non-volatile) মেমোরি?',
    type: 'multiple-choice',
    options: ['ROM (Read Only Memory)', 'RAM (Random Access Memory)', 'Cache Memory', 'Virtual Memory'],
    correctAnswer: 'ROM (Read Only Memory)',
    explanation: 'ROM একটি স্থায়ী মেমোরি, বিদ্যুৎ চলে গেলেও এর সংরক্ষিত ডেটা বা BIOS নির্দেশনাবলি মুছে যায় না। RAM বিদ্যুৎ চলে গেলে মুছে যায় (ভোলাটাইল)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - কম্পিউটার মেমোরি',
    difficulty: 'beginner',
  },
  {
    questionText: '১ গিগাবাইট (1 GB) সমান কত মেগাবাইট (MB)?',
    type: 'multiple-choice',
    options: ['১০২৪ মেগাবাইট (MB)', '১০০০ মেগাবাইট', '৫১২ মেগাবাইট', '২০৪৮ মেগাবাইট'],
    correctAnswer: '১০২৪ মেগাবাইট (MB)',
    explanation: 'কম্পিউটার বাইনারি গণনা অনুযায়ী: ১ বাইট = ৮ বিট; ১ KB = ১০২৪ বাইট; ১ MB = ১০২৪ KB; ১ GB = ১০২৪ MB; ১ TB = ১০২৪ GB।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - ডেটা পরিমাপ',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি ওপেন সোর্স অপারেটিং সিস্টেম?',
    type: 'multiple-choice',
    options: ['Linux', 'Windows 11', 'macOS', 'MS-DOS'],
    correctAnswer: 'Linux',
    explanation: 'লিনাক্স (Linux) লিনুস তোরভাল্ডস কর্তৃক উদ্ভাবিত একটি মুক্ত ও উন্মুক্ত সোর্স (Open Source) অপারেটিং সিস্টেম কার্নেল।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - অপারেটিং সিস্টেম',
    difficulty: 'beginner',
  },
  {
    questionText: 'ইন্টারনেটের মাধ্যমে ওয়েবপেজ প্রদর্শনের জন্য কোন প্রোটোকল ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['HTTP / HTTPS', 'FTP', 'SMTP', 'POP3'],
    correctAnswer: 'HTTP / HTTPS',
    explanation: 'হাইপারটেক্সট ট্রান্সফার প্রোটোকল (HTTP) ও সুরক্ষিত সংস্করণ (HTTPS) ওয়েব ব্রাউজারে ওয়েবপেজ স্থানান্তরের জন্য ব্যবহৃত হয়। FTP ফাইল স্থানান্তরে এবং SMTP ইমেইল পাঠাতে ব্যবহৃত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - নেটওয়ার্ক ও ইন্টারনেট',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি IPv4 অ্যাড্রেস কত বিটের হয়ে থাকে?',
    type: 'multiple-choice',
    options: ['৩২ বিট', '৬৪ বিট', '১২৮ বিট', '১৬ বিট'],
    correctAnswer: '৩২ বিট',
    explanation: 'IPv4 অ্যাড্রেস ৩২ বিটের (৪টি অক্টেট) এবং নতুন IPv6 অ্যাড্রেস ১২৮ বিটের হয়ে থাকে। (বিসিএস আইসিটিতে বারবার আসা প্রশ্ন)',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - নেটওয়ার্কিং',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি একটি ইনপুট ডিভাইস নয়?',
    type: 'multiple-choice',
    options: ['প্রিন্টার / স্পিকার', 'কীবোর্ড', 'অপটিক্যাল মাউস', 'বারকোড রিডার'],
    correctAnswer: 'প্রিন্টার / স্পিকার',
    explanation: 'প্রিন্টার, মনিটর, স্পিকার, প্রজেক্টর হলো আউটপুট ডিভাইস। কীবোর্ড, মাউস, স্ক্যানার, ওএমআর হলো ইনপুট ডিভাইস।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - ইনপুট ও আউটপুট',
    difficulty: 'beginner',
  },
  {
    questionText: 'ই-মেইল ঠিকানায় ইউজারনেম ও ডোমেইন নেমকে পৃথক করার জন্য কোন চিহ্নটি ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['@ (at the rate of)', '#', '&', '$'],
    correctAnswer: '@ (at the rate of)',
    explanation: 'রে টমলিনসন ১৯৭১ সালে প্রথম ইমেইল প্রেরণে ইউজারনেম এবং কম্পিউটার/ডোমেইনকে আলাদা করতে ‘@’ প্রতীক ব্যবহার করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - ইন্টারনেট',
    difficulty: 'beginner',
  },
  {
    questionText: 'DBMS এর পূর্ণরূপ কী?',
    type: 'multiple-choice',
    options: [
      'Database Management System',
      'Data Binary Management System',
      'Data Backup Management Server',
      'Digital Business Management System',
    ],
    correctAnswer: 'Database Management System',
    explanation: 'DBMS অর্থ ডেটাবেস ম্যানেজমেন্ট সিস্টেম (যেমন: MySQL, Oracle, PostgreSQL)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - ডেটাবেস',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোনটি ক্লাউড কম্পিউটিংয়ের সেবা মডেল নয়?',
    type: 'multiple-choice',
    options: ['MaaS (Modem as a Service)', 'IaaS (Infrastructure as a Service)', 'PaaS (Platform as a Service)', 'SaaS (Software as a Service)'],
    correctAnswer: 'MaaS (Modem as a Service)',
    explanation: 'ক্লাউড কম্পিউটিংয়ের প্রধান তিনটি সেবা স্তর হলো IaaS, PaaS, এবং SaaS।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আইসিটি - ক্লাউড কম্পিউটিং',
    difficulty: 'intermediate',
  },

  // 31-60: সাধারণ বিজ্ঞান (পদার্থ, রসায়ন, জীববিজ্ঞান ও স্বাস্থ্য)
  {
    questionText: 'বায়ুমণ্ডলে সর্বাধিক পরিমাণে প্রাপ্ত গ্যাস কোনটি?',
    type: 'multiple-choice',
    options: ['নাইট্রোজেন (প্রায় ৭৮.০৮%)', 'অক্সিজেন (প্রায় ২০.৯৫%)', 'কার্বন ডাই-অক্সাইড', 'আর্গন'],
    correctAnswer: 'নাইট্রোজেন (প্রায় ৭৮.০৮%)',
    explanation: 'শুষ্ক বাতাসে নাইট্রোজেনের পরিমাণ ৭৮.০৮%, অক্সিজেন ২০.৯৫%, আর্গন ০.৯৩% এবং কার্বন ডাই-অক্সাইড প্রায় ০.০৪%।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - পরিবেশ ও রসায়ন',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন ভিটামিনের অভাবে শিশুদের রিকেটস (Rickets) রোগ হয়?',
    type: 'multiple-choice',
    options: ['ভিটামিন D', 'ভিটামিন A', 'ভিটামিন C', 'ভিটামিন B12'],
    correctAnswer: 'ভিটামিন D',
    explanation: 'ভিটামিন ডি-এর অভাবে হাড় নরম ও বাঁকা হয়ে রিকেটস এবং প্রাপ্তবয়স্কদের অস্টিওম্যালাসিয়া রোগ হয়। সূর্যের আলো ত্বকে ভিটামিন ডি সংশ্লেষে সাহায্য করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - পুষ্টি ও ভিটামিন',
    difficulty: 'beginner',
  },
  {
    questionText: 'ভিটামিন সি (Ascorbic Acid) এর প্রধান প্রাকৃতিক উৎস কোনটি?',
    type: 'multiple-choice',
    options: ['টক জাতীয় ফল যেমন আমলকী, লেবু, পেয়ারা', 'দুধ ও ডিম', 'ভাত ও গম', 'গাজর ও শাকসবজি'],
    correctAnswer: 'টক জাতীয় ফল যেমন আমলকী, লেবু, পেয়ারা',
    explanation: 'আমলকী, লেবু, পেয়ারা ও কাঁচামরিচ ভিটামিন সি-এর উৎকৃষ্ট উৎস। এর অভাবে স্কার্ভি রোগ (দাঁতের মাড়ি দিয়ে রক্ত পড়া) হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - পুষ্টি ও ভিটামিন',
    difficulty: 'beginner',
  },
  {
    questionText: 'মানবদেহে সার্বজনীন গ্রহীতা (Universal Recipient) রক্তের গ্রুপ কোনটি?',
    type: 'multiple-choice',
    options: ['AB পজিটিভ (AB+)', 'O নেগেটিভ (O-)', 'A পজিটিভ', 'B পজিটিভ'],
    correctAnswer: 'AB পজিটিভ (AB+)',
    explanation: 'AB+ রক্তে কোনো অ্যান্টিবডি না থাকায় সব গ্রুপ থেকে রক্ত নিতে পারে (সার্বজনীন গ্রহীতা)। ও নেগেটিভ (O-) রক্তে কোনো অ্যান্টিজেন না থাকায় সার্বজনীন দাতা।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - মানব শরীরতত্ত্ব',
    difficulty: 'beginner',
  },
  {
    questionText: 'লোহিত রক্তকণিকার (RBC) গড় আয়ুষ্কাল কত দিন?',
    type: 'multiple-choice',
    options: ['১২০ দিন', '৬০ দিন', '১৫ দিন', '১৮০ দিন'],
    correctAnswer: '১২০ দিন',
    explanation: 'মানুষের লোহিত রক্তকণিকার গড় আয়ু প্রায় ১২০ দিন বা ৪ মাস। এটি অস্থিমজ্জায় তৈরি হয় এবং প্লীহায় ধ্বংসপ্রাপ্ত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - মানব শরীরতত্ত্ব',
    difficulty: 'beginner',
  },
  {
    questionText: 'শব্দের বেগ সবচেয়ে বেশি কোন মাধ্যমে?',
    type: 'multiple-choice',
    options: ['কঠিন মাধ্যমে (যেমন লোহা বা ইস্পাত)', 'বায়বীয় মাধ্যমে', 'তরল মাধ্যমে', 'শূন্য মাধ্যমে'],
    correctAnswer: 'কঠিন মাধ্যমে (যেমন লোহা বা ইস্পাত)',
    explanation: 'অণুর ঘনত্বের কারণে কঠিন মাধ্যমে শব্দের বেগ সবচেয়ে বেশি (ইস্পাতে প্রায় ৫১০০ মি/সে), বায়ুতে ৩৩২ মি/সে, এবং শূন্য মাধ্যমে শব্দ চলাচল করতে পারে না।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - পদার্থবিজ্ঞান',
    difficulty: 'beginner',
  },
  {
    questionText: 'সূর্যের আলো থেকে কোন ভিটামিন সংশ্লেষিত হয়?',
    type: 'multiple-choice',
    options: ['ভিটামিন D', 'ভিটামিন A', 'ভিটামিন E', 'ভিটামিন K'],
    correctAnswer: 'ভিটামিন D',
    explanation: 'সূর্যের অতিবেগুনি রশ্মির উপস্থিতিতে মানুষের ত্বকের নিচে থাকা কোলেস্টেরল থেকে ভিটামিন ডি তৈরি হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - পুষ্টি',
    difficulty: 'beginner',
  },
  {
    questionText: 'শুষ্ক বরফ (Dry Ice) কী?',
    type: 'multiple-choice',
    options: ['কঠিন কার্বন ডাই-অক্সাইড (Solid CO₂)', 'হিমাঙ্কের বরফ', 'ভারী পানি', 'কঠিন নাইট্রোজেন'],
    correctAnswer: 'কঠিন কার্বন ডাই-অক্সাইড (Solid CO₂)',
    explanation: 'উচ্চ চাপে ও -৭৮.৫ ডিগ্রি সেলসিয়াসে কার্বন ডাই-অক্সাইডকে কঠিনে রূপান্তরিত করলে তাকে শুষ্ক বরফ বলা হয়, যা তরল না হয়ে সরাসরি গ্যাসে পরিণত হয় (ঊর্ধ্বপাতন)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - রসায়ন',
    difficulty: 'beginner',
  },
  {
    questionText: 'বিশুদ্ধ পানির pH মান কত?',
    type: 'multiple-choice',
    options: ['৭.০ (নিরপেক্ষ)', '০', '১৪', '৫.৬'],
    correctAnswer: '৭.০ (নিরপেক্ষ)',
    explanation: '২৫ ডিগ্রি সেলসিয়াসে বিশুদ্ধ পানির পিএইচ ঠিক ৭ (নিরপেক্ষ)। ৭ এর কম এসিডীয় এবং ৭ এর বেশি ক্ষারীয়। মানব রক্তের স্বাভাবিক পিএইচ প্রায় ৭.৪।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাধারণ বিজ্ঞান - রসায়ন',
    difficulty: 'beginner',
  },
];
