import { IJobQuestionItem } from './banglaQuestions.js';

export const specialJobQuestions1: IJobQuestionItem[] = [
  // ========================================================
  // 1. GENERAL SCIENCE & ICT (50 questions)
  // ========================================================
  {
    questionText: 'বিদ্যুৎ প্রবাহের একক কোনটি?',
    type: 'multiple-choice',
    options: ['অ্যাম্পিয়ার (Ampere)', 'ভোল্ট (Volt)', 'ওয়াট (Watt)', 'জুল (Joule)'],
    correctAnswer: 'অ্যাম্পিয়ার (Ampere)',
    explanation: 'তড়িৎ প্রবাহের এসআই একক অ্যাম্পিয়ার (A); বিভব পার্থক্যের একক ভোল্ট (V) এবং ক্ষমতার একক ওয়াট (W)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - তড়িৎ',
    difficulty: 'beginner'
  },
  {
    questionText: 'রোধের (Resistance) আন্তর্জাতিক এসআই একক কোনটি?',
    type: 'multiple-choice',
    options: ['ওহম (Ohm, Ω)', 'কুলম্ব (Coulomb)', 'ফ্যারাড (Farad)', 'হেনরি (Henry)'],
    correctAnswer: 'ওহম (Ohm, Ω)',
    explanation: 'ওহমের সূত্র V = IR অনুযায়ী পরিবাহীর রোধের একক ওহম (Ω)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - তড়িৎ',
    difficulty: 'beginner'
  },
  {
    questionText: 'বাসাবাড়িতে সরবরাহকৃত সাধারণ বিদ্যুৎ প্রবাহের ধরন ও কম্পাঙ্ক কোনটি?',
    type: 'multiple-choice',
    options: ['২২০ ভোল্ট অল্টারনেটিং কারেন্ট (AC) এবং ৫০ হার্টজ (Hz)', '১১০ ভোল্ট DC', '২২০ ভোল্ট DC', '৪৪০ ভোল্ট AC ৬০ Hz'],
    correctAnswer: '২২০ ভোল্ট অল্টারনেটিং কারেন্ট (AC) এবং ৫০ হার্টজ (Hz)',
    explanation: 'বাংলাদেশে জাতীয় গ্রিড থেকে গৃহস্থালিতে ২২০ ভোল্ট, ৫০ হার্টজের দিক পরিবর্তী প্রবাহ (AC) সরবরাহ করা হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - বিদ্যুৎ',
    difficulty: 'intermediate'
  },
  {
    questionText: 'ট্রান্সফরমার (Transformer) বর্তনীতে কী পরিবর্তন করে?',
    type: 'multiple-choice',
    options: ['ভোল্টেজ ও তড়িৎ প্রবাহের মান হ্রাস-বৃদ্ধি করে', 'এসি কারেন্টকে ডিসিতে রূপান্তর করে', 'ফ্রিকোয়েন্সি দ্বিগুণ করে', 'বিদ্যুৎ সঞ্চয় করে'],
    correctAnswer: 'ভোল্টেজ ও তড়িৎ প্রবাহের মান হ্রাস-বৃদ্ধি করে',
    explanation: 'স্টেপ-আপ ও স্টেপ-ডাউন ট্রান্সফরমার তড়িৎ চুম্বকীয় আবেশের মাধ্যমে এসির ভোল্টেজ রূপান্তর করে (কম্পাঙ্ক অপরিবর্তিত থাকে)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - যন্ত্র',
    difficulty: 'intermediate'
  },
  {
    questionText: 'কোন রঙের আলোর তরঙ্গদৈর্ঘ্য (Wavelength) সবচেয়ে বেশি এবং কোন রঙের সবচেয়ে কম?',
    type: 'multiple-choice',
    options: ['লাল আলোর সবচেয়ে বেশি এবং বেগুনি আলোর সবচেয়ে কম', 'বেগুনি আলোর সবচেয়ে বেশি এবং লালের সবচেয়ে কম', 'সবুজ আলোর সবচেয়ে বেশি', 'হলুদ আলোর সবচেয়ে বেশি'],
    correctAnswer: 'লাল আলোর সবচেয়ে বেশি এবং বেগুনি আলোর সবচেয়ে কম',
    explanation: 'বেনীআসহকলা ক্রমানুসারে লালের তরঙ্গদৈর্ঘ্য সর্বাধিক (প্রায় ৭০০ ন্যানোমিটার) হওয়ায় এর বিচ্যুতি সবচেয়ে কম; বেগুনি আলোর তরঙ্গদৈর্ঘ্য সর্বনিম্ন (প্রায় ৪০০ ন্যানোমিটার)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - আলো',
    difficulty: 'beginner'
  },
  {
    questionText: 'আকাশ নীল দেখায় কেন?',
    type: 'multiple-choice',
    options: ['বায়ুমণ্ডলে নীল আলোর বিক্ষেপণ (Scattering) সবচেয়ে বেশি হয় বলে', 'সমুদ্রের পানির প্রতিফলনে', 'মহাকাশের রঙের কারণে', 'ওজোন গ্যাসের নিজস্ব রঙে'],
    correctAnswer: 'বায়ুমণ্ডলে নীল আলোর বিক্ষেপণ (Scattering) সবচেয়ে বেশি হয় বলে',
    explanation: 'র‌্যালের বিক্ষেপণ সূত্র অনুযায়ী কম তরঙ্গদৈর্ঘ্যের আলো বেশি বিক্ষিপ্ত হয়; তাই নীল আলো চতুর্দিকে ছড়িয়ে পড়ে আকাশকে নীল দেখায়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - আলো',
    difficulty: 'beginner'
  },
  {
    questionText: 'মরীচিকা (Mirage) সৃষ্টির কারণ আলোর কোন ধর্ম?',
    type: 'multiple-choice',
    options: ['আলোর পূর্ণ অভ্যন্তরীণ প্রতিফলন (Total Internal Reflection)', 'আলোর বিচ্ছুরণ', 'আলোর সমবর্তন', 'আলোর ব্যতিচার'],
    correctAnswer: 'আলোর পূর্ণ অভ্যন্তরীণ প্রতিফলন (Total Internal Reflection)',
    explanation: 'উত্তপ্ত মরুভূমি বা পিচঢালা রাস্তায় বাতাসের বিভিন্ন ঘনত্বের স্তরের কারণে আলোক রশ্মির পূর্ণ অভ্যন্তরীণ প্রতিফলনে মরীচিকা সৃষ্টি হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - আলো',
    difficulty: 'beginner'
  },
  {
    questionText: 'পরম শূন্য তাপমাত্রা (Absolute Zero Temperature) এর মান কত?',
    type: 'multiple-choice',
    options: ['-২৭৩.১৫° সেলসিয়াস বা ০ কেলভিন', '০° সেলসিয়াস', '-১০০° সেলসিয়াস', '-৪৬০° সেলসিয়াস'],
    correctAnswer: '-২৭৩.১৫° সেলসিয়াস বা ০ কেলভিন',
    explanation: 'তাত্ত্বিকভাবে যে তাপমাত্রায় কোনো গ্যাসের অণুর গতিশক্তি সম্পূর্ণরূপে থেমে যায় এবং আয়তন শূন্য হয় তাকে পরম শূন্য তাপমাত্রা বলে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - তাপ',
    difficulty: 'intermediate'
  },
  {
    questionText: 'প্রেসার কুকারে রান্না দ্রুত হয় কেন?',
    type: 'multiple-choice',
    options: ['উচ্চ চাপে পানির স্ফুটনাঙ্ক বৃদ্ধি পায় বলে (১০০°C এর বেশি হয়)', 'কুকারের বিশেষ ধাতুর কারণে', 'বাষ্প বাইরে যেতে পারে না বলে', 'তাপমাত্রা কমে যায় বলে'],
    correctAnswer: 'উচ্চ চাপে পানির স্ফুটনাঙ্ক বৃদ্ধি পায় বলে (১০০°C এর বেশি হয়)',
    explanation: 'চাপ বৃদ্ধির ফলে পানির স্ফুটনাঙ্ক ১০০°C থেকে বেড়ে প্রায় ১২০°C হয়, ফলে খাদ্য দ্রুত সিদ্ধ হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পদার্থবিজ্ঞান - চাপ ও স্ফুটনাঙ্ক',
    difficulty: 'beginner'
  },
  {
    questionText: 'সৌরজগতের সবচেয়ে বড় গ্রহ কোনটি এবং সবচেয়ে ছোট গ্রহ কোনটি?',
    type: 'multiple-choice',
    options: ['বৃহস্পতি সবচেয়ে বড় এবং বুধ সবচেয়ে ছোট', 'শনি সবচেয়ে বড় এবং মঙ্গল সবচেয়ে ছোট', 'নেপচুন সবচেয়ে বড় এবং শুক্র সবচেয়ে ছোট', 'পৃথিবী সবচেয়ে বড় এবং প্লুটো সবচেয়ে ছোট'],
    correctAnswer: 'বৃহস্পতি সবচেয়ে বড় এবং বুধ সবচেয়ে ছোট',
    explanation: 'বৃহস্পতি (Jupiter) সর্ববৃহৎ গ্রহ; বুধ (Mercury) সূর্যের নিকটতম ও ক্ষুদ্রতম গ্রহ।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'মহাকাশ ও সৌরজগৎ',
    difficulty: 'beginner'
  },
  {
    questionText: 'সূর্যের নিকটতম গ্রহ কোনটি এবং পৃথিবীর নিকটতম প্রতিবেশী গ্রহ কোনটি?',
    type: 'multiple-choice',
    options: ['সূর্যের নিকটতম বুধ এবং পৃথিবীর নিকটতম শুক্র (Venus)', 'সূর্যের নিকটতম শুক্র এবং পৃথিবীর নিকটতম মঙ্গল', 'সূর্যের নিকটতম পৃথিবী', 'সূর্যের নিকটতম মঙ্গল'],
    correctAnswer: 'সূর্যের নিকটতম বুধ এবং পৃথিবীর নিকটতম শুক্র (Venus)',
    explanation: 'সূর্যের সবচেয়ে কাছে বুধ; পৃথিবীর সবচেয়ে কাছে শুক্র (যা সন্ধ্যাতারা বা শুকতারা নামে পরিচিত)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'মহাকাশ ও সৌরজগৎ',
    difficulty: 'beginner'
  },
  {
    questionText: 'কোন গ্রহকে ‘লাল গ্রহ’ (Red Planet) বলা হয়?',
    type: 'multiple-choice',
    options: ['মঙ্গল গ্রহ (Mars)', 'শুক্র গ্রহ', 'বুধ গ্রহ', 'শনি গ্রহ'],
    correctAnswer: 'মঙ্গল গ্রহ (Mars)',
    explanation: 'পৃষ্ঠভাগে প্রচুর পরিমাণে আয়রন অক্সাইড (মরিচা) থাকার কারণে মঙ্গল গ্রহকে লালচে দেখায়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'মহাকাশ ও সৌরজগৎ',
    difficulty: 'beginner'
  },
  {
    questionText: 'হ্যালির ধূমকেতু কত বছর পর পর আকাশে দেখা যায়?',
    type: 'multiple-choice',
    options: ['৭৬ বছর পর পর', '৮৬ বছর পর পর', '৫০ বছর পর পর', '১০০ বছর পর পর'],
    correctAnswer: '৭৬ বছর পর পর',
    explanation: 'এডমন্ড হ্যালির নামানুসারে এই ধূমকেতু প্রতি ৭৫-৭৬ বছর অন্তর সূর্যের কাছাকাছি আসে (সর্বশেষ ১৯৮৬ সালে দেখা গিয়েছিল, পরবর্তী ২০৬১ সালে)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'মহাকাশ বিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'সূর্যে শক্তির মূল উৎস কোন নিউক্লিয়ার বিক্রিয়া?',
    type: 'multiple-choice',
    options: ['নিউক্লিয়ার ফিউশন (Nuclear Fusion)', 'নিউক্লিয়ার ফিশন', 'রাসায়নিক দহন', 'তেজস্ক্রিয় ক্ষয়'],
    correctAnswer: 'নিউক্লিয়ার ফিউশন (Nuclear Fusion)',
    explanation: 'উচ্চ তাপমাত্রা ও চাপে ৪টি হাইড্রোজেন নিউক্লিয়াস সংযোজিত হয়ে একটি হিলিয়াম নিউক্লিয়াসে রূপান্তরিত হয়ে বিপুল তাপ ও আলো উৎপন্ন করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পরমাণু ও পারমাণবিক পদার্থবিজ্ঞান',
    difficulty: 'intermediate'
  },
  {
    questionText: 'মানুষের রক্তে স্বাভাবিক pH এর মান কত?',
    type: 'multiple-choice',
    options: ['৭.৩৫ থেকে ৭.৪৫ (সামান্য ক্ষারীয়)', '৬.৫ (অম্লীয়)', '৮.৫ (তীব্র ক্ষারীয়)', '৭.০ (নিরপেক্ষ)'],
    correctAnswer: '৭.৩৫ থেকে ৭.৪৫ (সামান্য ক্ষারীয়)',
    explanation: 'মানব রক্তের গড় pH ৭.৪, যা সামান্য ক্ষারীয়। এর সামান্য তারতম্য জীবনহানির কারণ হতে পারে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'রসায়ন ও মানবদেহ',
    difficulty: 'beginner'
  },
  {
    questionText: 'লেবুর রসে কোন জৈব এসিড বিদ্যমান?',
    type: 'multiple-choice',
    options: ['সাইট্রিক এসিড (Citric Acid)', 'টারটারিক এসিড', 'অক্সালিক এসিড', 'ম্যালিক এসিড'],
    correctAnswer: 'সাইট্রিক এসিড (Citric Acid)',
    explanation: 'লেবু ও কমলায় সাইট্রিক এসিড; তেঁতুলে টারটারিক এসিড; আপেলে ম্যালিক এসিড; ভিনেগারে অ্যাসিটিক এসিড এবং দুধে ল্যাকটিক এসিড থাকে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'দৈনন্দিন রসায়ন',
    difficulty: 'beginner'
  },
  {
    questionText: 'ভিনেগার (Vinegar) বা সিরকা আসলে কী?',
    type: 'multiple-choice',
    options: ['অ্যাসিটিক এসিডের ৪-১০% জলীয় দ্রবণ', 'ফর্মালিনের জলীয় দ্রবণ', 'হাইড্রোক্লোরিক এসিড', 'সালফিউরিক এসিড'],
    correctAnswer: 'অ্যাসিটিক এসিডের ৪-১০% জলীয় দ্রবণ',
    explanation: 'অ্যাসিটিক এসিড (CH₃COOH) এর ৪% থেকে ১০% জলীয় দ্রবণকে প্রিজারভেটিভ হিসেবে ব্যবহৃত ভিনেগার বলে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'দৈনন্দিন রসায়ন',
    difficulty: 'beginner'
  },
  {
    questionText: 'বায়ুমণ্ডলে সর্বাধিক পরিমাণে উপস্থিত গ্যাস কোনটি?',
    type: 'multiple-choice',
    options: ['নাইট্রোজেন (প্রায় ৭৮.০৯%)', 'অক্সিজেন (প্রায় ২০.৯৫%)', 'আর্গন', 'কার্বন ডাই-অক্সাইড'],
    correctAnswer: 'নাইট্রোজেন (প্রায় ৭৮.০৯%)',
    explanation: 'বায়ুর উপাদান: নাইট্রোজেন ৭৮.০৯%, অক্সিজেন ২০.৯৫%, আর্গন ০.৯৩%, কার্বন ডাই-অক্সাইড ০.০৪%।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পরিবেশ বিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'কোন গ্যাসকে ‘হাস্য উদ্দীপক গ্যাস’ বা লাফিং গ্যাস (Laughing Gas) বলা হয়?',
    type: 'multiple-choice',
    options: ['নাইট্রাস অক্সাইড (N₂O)', 'নাইট্রোজেন ডাই-অক্সাইড (NO₂)', 'মিথেন (CH₄)', 'ক্লোরোফর্ম'],
    correctAnswer: 'নাইট্রাস অক্সাইড (N₂O)',
    explanation: 'নাইট্রাস অক্সাইড নিঃশ্বাসে গ্রহণ করলে স্নায়বিক উত্তেজনায় মৃদু আনন্দের অনুভূতি ও হাসি পায়, চিকিৎসায় অবেদন হিসেবে ব্যবহৃত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'রসায়ন',
    difficulty: 'beginner'
  },
  {
    questionText: 'বায়ুমণ্ডলের কোন স্তরে ওজোন (O₃) গ্যাসের স্তর অবস্থিত যা অতিবেগুনি রশ্মি শোষণ করে?',
    type: 'multiple-choice',
    options: ['স্ট্রাটোস্ফিয়ার (Stratosphere)', 'ট্রপোস্ফিয়ার (Troposphere)', 'মেসোস্ফিয়ার', 'থার্মোস্ফিয়ার'],
    correctAnswer: 'স্ট্রাটোস্ফিয়ার (Stratosphere)',
    explanation: 'ভূপৃষ্ঠের ১৫ থেকে ৩৫ কিমি ওপরে স্ট্রাটোস্ফিয়ারে অবস্থিত ওজোন স্তর সূর্যের ক্ষতিকর UV রশ্মি থেকে জীবজগতকে রক্ষা করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পরিবেশ বিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'মানবদেহের কোষের ‘শক্তিঘর’ (Powerhouse of the Cell) বলা হয় কোন অঙ্গাণুকে?',
    type: 'multiple-choice',
    options: ['মাইটোকন্ড্রিয়া (Mitochondria)', 'রাইবোজোম', 'গলজি বস্তু', 'লাইসোজোম'],
    correctAnswer: 'মাইটোকন্ড্রিয়া (Mitochondria)',
    explanation: 'কোষীয় শ্বসনের ক্রেবস চক্র মাইটোকন্ড্রিয়ায় সম্পন্ন হয় এবং বিপুল পরিমাণে শক্তি (ATP) তৈরি হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'কোষ ও বংশগতি',
    difficulty: 'beginner'
  },
  {
    questionText: 'কোষে প্রোটিন সংশ্লেষণ (Protein Synthesis) কোথায় ঘটে?',
    type: 'multiple-choice',
    options: ['রাইবোজোম (Ribosome)', 'লাইসোজোম', 'সেন্ট্রোজোম', 'মাইটোকন্ড্রিয়া'],
    correctAnswer: 'রাইবোজোম (Ribosome)',
    explanation: 'রাইবোজোম কোষের প্রোটিন ফ্যাক্টরি নামে পরিচিত; এটি অ্যামিনো এসিড যুক্ত করে পলিপেপটাইড শৃঙ্খল গঠন করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'কোষ ও বংশগতি',
    difficulty: 'intermediate'
  },
  {
    questionText: 'মানবদেহের ক্রোমোজোম সংখ্যা কতটি?',
    type: 'multiple-choice',
    options: ['২৩ জোড়া বা ৪৬টি', '২২ জোড়া', '২৪ জোড়া', '৪৫টি'],
    correctAnswer: '২৩ জোড়া বা ৪৬টি',
    explanation: 'মানুষের প্রতিটি দেহকোষে ২২ জোড়া অটোজোম এবং ১ জোড়া সেক্স ক্রোমোজোম (XX বা XY) মিলিয়ে মোট ৪৬টি ক্রোমোজোম থাকে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'বংশগতি ও জিনতত্ত্ব',
    difficulty: 'beginner'
  },
  {
    questionText: 'মায়ের গর্ভের ভ্রূণের লিঙ্গ নির্ধারণে কার ক্রোমোজোম ভূমিকা পালন করে?',
    type: 'multiple-choice',
    options: ['পিতার ক্রোমোজোম (Y ক্রোমোজোম)', 'মাতার ক্রোমোজোম', 'উভয়ের সমান', 'পরিবেশীয় তাপমাত্রা'],
    correctAnswer: 'পিতার ক্রোমোজোম (Y ক্রোমোজোম)',
    explanation: 'মায়ের ডিম্বাণু সর্বদা X ক্রোমোজোম ধারণ করে; পিতার শুক্রাণু X বহন করলে কন্যাসন্তান (XX) এবং Y বহন করলে পুত্রসন্তান (XY) হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'বংশগতি ও জিনতত্ত্ব',
    difficulty: 'beginner'
  },
  {
    questionText: 'ডিএনএ (DNA) এর ডাবল হেলিক্স (দ্বি-সূত্রক) কাঠামোর মডেল কত সালে কারা আবিষ্কার করেন?',
    type: 'multiple-choice',
    options: ['১৯৫৩ সালে ওয়াটসন ও ক্রিক (Watson & Crick)', 'রবার্ট হুক', 'গ্রেগর জোহান মেন্ডেল', 'লুই পাস্তুর'],
    correctAnswer: '১৯৫৩ সালে ওয়াটসন ও ক্রিক (Watson & Crick)',
    explanation: 'জেমস ওয়াটসন এবং ফ্রান্সিস ক্রিক ১৯৫৩ সালে ডিএনএর ডাবল হেলিক্স নকশা প্রস্তাব করেন এবং ১৯৬২ সালে নোবেল পুরস্কার লাভ করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'আণবিক জীববিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'পেনিসিলিন (Penicillin) অ্যান্টিবায়োটিক কে আবিষ্কার করেন?',
    type: 'multiple-choice',
    options: ['স্যার আলেকজান্ডার ফ্লেমিং (১৯২৮ সালে)', 'এডওয়ার্ড জেনার', 'রবার্ট কচ', 'লুই পাস্তুর'],
    correctAnswer: 'স্যার আলেকজান্ডার ফ্লেমিং (১৯২৮ সালে)',
    explanation: 'আলেকজান্ডার ফ্লেমিং পেনিসিলিয়াম নোটেটাম নামক ছত্রাক থেকে বিশ্বের প্রথম অ্যান্টিবায়োটিক পেনিসিলিন আবিষ্কার করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'চিকিৎসাবিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'জলাতঙ্কের টিকা (Rabies Vaccine) এবং দুধের পাস্তুরায়ন কে উদ্ভাবন করেন?',
    type: 'multiple-choice',
    options: ['লুই পাস্তুর (Louis Pasteur)', 'এডওয়ার্ড জেনার', 'অ্যান্টনি ভন লিউয়েনহুক', 'রবার্ট কচ'],
    correctAnswer: 'লুই পাস্তুর (Louis Pasteur)',
    explanation: 'ফরাসি অণুজীববিজ্ঞানী লুই পাস্তুর জলাতঙ্ক ও অ্যানথ্রাক্সের টিকা এবং অণুজীব ধ্বংসের পাস্তুরায়ন পদ্ধতি উদ্ভাবন করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'চিকিৎসাবিজ্ঞান ও অণুজীব',
    difficulty: 'beginner'
  },
  {
    questionText: 'বসন্ত রোগের টিকা (Smallpox Vaccine) সর্বপ্রথম কে আবিষ্কার করেন?',
    type: 'multiple-choice',
    options: ['ডা. এডওয়ার্ড জেনার (Edward Jenner, ১৭৯৬)', 'আলেকজান্ডার ফ্লেমিং', 'রবার্ট হুক', 'জোনাস সল্ক'],
    correctAnswer: 'ডা. এডওয়ার্ড জেনার (Edward Jenner, ১৭৯৬)',
    explanation: 'এডওয়ার্ড জেনার গোবসন্তের রস ব্যবহার করে ১৭৯৬ সালে মানবজাতির প্রথম সফল টিকা আবিষ্কার করেন এবং তাকে ইমিউনোলজির জনক বলা হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'চিকিৎসাবিজ্ঞান',
    difficulty: 'beginner'
  },
  {
    questionText: 'পোলিও টিকার (Polio Vaccine) সফল উদ্ভাবক কে?',
    type: 'multiple-choice',
    options: ['জোনাস সল্ক (Jonas Salk) এবং অ্যালবার্ট সাবিন', 'লুই পাস্তুর', 'ওয়াটসন', 'আলেকজান্ডার ফ্লেমিং'],
    correctAnswer: 'জোনাস সল্ক (Jonas Salk) এবং অ্যালবার্ট সাবিন',
    explanation: '১৯৫৩ সালে জোনাস সল্ক ইনজেকশন পোলিও টিকা এবং পরে অ্যালবার্ট সাবিন ওরাল (মুখের ড্রপ) পোলিও টিকা আবিষ্কার করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'চিকিৎসাবিজ্ঞান',
    difficulty: 'intermediate'
  },
  {
    questionText: 'রক্তের চাপ মাপার যন্ত্রের নাম কী?',
    type: 'multiple-choice',
    options: ['স্ফিগমোম্যানোমিটার (Sphygmomanometer)', 'ব্যারোমিটার', 'ল্যাকটোমিটার', 'অ্যালটিমিটার'],
    correctAnswer: 'স্ফিগমোম্যানোমিটার (Sphygmomanometer)',
    explanation: 'বায়ুর চাপ মাপক যন্ত্র ব্যারোমিটার; দুধের বিশুদ্ধতা মাপক ল্যাকটোমিটার; উচ্চতা মাপক অ্যালটিমিটার এবং রক্তচাপ মাপক স্ফিগমোম্যানোমিটার।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'বিজ্ঞান ও পরিমাপক যন্ত্র',
    difficulty: 'beginner'
  },
  {
    questionText: 'ভূমিকম্পের তীব্রতা মাপার স্কেলের নাম কী এবং যন্ত্রের নাম কী?',
    type: 'multiple-choice',
    options: ['রিক্টার স্কেল (Richter Scale) এবং সিসমোগ্রাফ (Seismograph)', 'থার্মোমিটার ও ব্যারোমিটার', 'অ্যামিটার ও গ্যালভানোমিটার', 'সোনার ও রাডার'],
    correctAnswer: 'রিক্টার স্কেল (Richter Scale) এবং সিসমোগ্রাফ (Seismograph)',
    explanation: 'সিসমোগ্রাফ দিয়ে ভূকম্পন তরঙ্গ লিপিবদ্ধ করা হয় এবং রিক্টার স্কেলের লগারিদমিক মাত্রায় শক্তি প্রকাশ করা হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ভূগোল ও যন্ত্র',
    difficulty: 'beginner'
  },
  {
    questionText: 'উচ্চ তাপমাত্রা মাপার জন্য কোন যন্ত্র ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['পাইরোমিটার (Pyrometer)', 'অ্যানিমোমিটার', 'হাইড্রোমিটার', 'থার্মোমিটার'],
    correctAnswer: 'পাইরোমিটার (Pyrometer)',
    explanation: 'সূর্য বা চুল্লির মতো অতি উচ্চ তাপমাত্রা দূর থেকে বিকিরণের সাহায্যে পরিমাপের যন্ত্র হলো পাইরোমিটার। বাতাসের গতি মাপক অ্যানিমোমিটার।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পরিমাপক যন্ত্র',
    difficulty: 'intermediate'
  },
  {
    questionText: 'সমুদ্রের গভীরতা মাপার একক এবং যন্ত্র কোনটি?',
    type: 'multiple-choice',
    options: ['একক ফ্যাদম (Fathom) এবং যন্ত্র ফ্যাথোমিটার (Fathometer)', 'নট এবং স্পিডোমিটার', 'মিটার এবং ব্যারোমিটার', 'মাইল এবং রাডার'],
    correctAnswer: 'একক ফ্যাদম (Fathom) এবং যন্ত্র ফ্যাথোমিটার (Fathometer)',
    explanation: '১ ফ্যাদম = ৬ ফুট = ১.৮৩ মিটার। শব্দ তরঙ্গের প্রতিধ্বনি পাঠিয়ে ফ্যাথোমিটার দিয়ে সমুদ্রের তলদেশের গভীরতা নির্ণয় করা হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'পরিমাপ ও যন্ত্র',
    difficulty: 'beginner'
  },
  {
    questionText: 'কম্পিউটারের প্রথম প্রোগ্রামিং ভাষা কোনটি?',
    type: 'multiple-choice',
    options: ['ফোরট্রান (FORTRAN, 1957)', 'সি (C)', 'জাভা (Java)', 'পাইথন (Python)'],
    correctAnswer: 'ফোরট্রান (FORTRAN, 1957)',
    explanation: 'আইবিএম কর্তৃক উদ্ভাবিত Formula Translation বা FORTRAN হলো প্রথম উচ্চস্তরের বাণিজ্যিক প্রোগ্রামিং ভাষা।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'কম্পিউটার প্রোগ্রামিং',
    difficulty: 'intermediate'
  },
  {
    questionText: 'সি (C) প্রোগ্রামিং ভাষার জনক কাকে বলা হয়?',
    type: 'multiple-choice',
    options: ['ডেনিস রিচি (Dennis Ritchie)', 'বিয়ার্নে স্ট্রোভস্ট্রুপ', 'জেমস গসলিং', 'গুইডো ভ্যান রসাম'],
    correctAnswer: 'ডেনিস রিচি (Dennis Ritchie)',
    explanation: '১৯৭২ সালে বেল ল্যাবরেটরিতে ডেনিস রিচি ইউনিক্স অপারেটিং সিস্টেম তৈরির উদ্দেশ্যে ‘সি’ ভাষা উদ্ভাবন করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'প্রোগ্রামিং ভাষা',
    difficulty: 'beginner'
  },
  {
    questionText: 'রিলেশনাল ডাটাবেস ম্যানেজমেন্ট সিস্টেমে (RDBMS) ডেটা কোয়েরি করার মানসম্মত ভাষা কোনটি?',
    type: 'multiple-choice',
    options: ['SQL (Structured Query Language)', 'HTML', 'XML', 'PHP'],
    correctAnswer: 'SQL (Structured Query Language)',
    explanation: 'এসকিউএল হলো আন্তর্জাতিক মানসম্পন্ন ভাষা যা ডাটাবেস তৈরি, টেবিল মডিফাই, ইনসার্ট, আপডেট ও সিলেক্ট কোয়েরিতে ব্যবহৃত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ডাটাবেস ও আইসিটি',
    difficulty: 'beginner'
  },
  {
    questionText: 'একটি টেবিলে প্রতিটি রেকর্ডকে অনন্যভাবে (Uniquely) শনাক্তকারী কী-কে কী বলা হয়?',
    type: 'multiple-choice',
    options: ['প্রাইমারি কি (Primary Key)', 'ফরেন কি (Foreign Key)', 'কম্পোজিট কি', 'ক্যান্ডিডেট কি'],
    correctAnswer: 'প্রাইমারি কি (Primary Key)',
    explanation: 'প্রাইমারি কি এমন একটি ফিল্ড যার মান কখনো নাল (Null) হতে পারে না এবং যার মান প্রতিটি রেকর্ডে অনন্য বা ইউনিক থাকে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ডাটাবেস',
    difficulty: 'beginner'
  },
  {
    questionText: 'ক্লাউড কম্পিউটিং সার্ভিসের তিনটি প্রধান মডেল কী কী?',
    type: 'multiple-choice',
    options: ['IaaS, PaaS, SaaS', 'HTTP, FTP, SMTP', 'LAN, MAN, WAN', 'RAM, ROM, SSD'],
    correctAnswer: 'IaaS, PaaS, SaaS',
    explanation: 'Infrastructure as a Service (IaaS), Platform as a Service (PaaS), Software as a Service (SaaS)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ক্লাউড কম্পিউটিং',
    difficulty: 'intermediate'
  },
  {
    questionText: '‘কৃত্রিম বুদ্ধিমত্তা’ (Artificial Intelligence) ধারণার প্রবক্তা বা জনক কাকে বিবেচনা করা হয়?',
    type: 'multiple-choice',
    options: ['জন ম্যাকার্থি (John McCarthy)', 'অ্যালান টুরিং', 'মারভিন মিনস্কি', 'জেফ্রি হিন্টন'],
    correctAnswer: 'জন ম্যাকার্থি (John McCarthy)',
    explanation: '১৯৫৬ সালের ডার্টমাউথ সম্মেলনে মার্কিন কম্পিউটার বিজ্ঞানী জন ম্যাকার্থি প্রথম ‘Artificial Intelligence’ শব্দবন্ধটি প্রবর্তন করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'কৃত্রিম বুদ্ধিমত্তা (AI)',
    difficulty: 'beginner'
  },
  {
    questionText: 'ব্লকচেইন (Blockchain) প্রযুক্তির উদ্ভাবক এবং বিটকয়েনের প্রতিষ্ঠাতা কে?',
    type: 'multiple-choice',
    options: ['সাতোশি নাকামোতো (Satoshi Nakamoto ছদ্মনাম)', 'ভিতালিক বুতেরিন', 'ইলন মাস্ক', 'নিক সাজাবো'],
    correctAnswer: 'সাতোশি নাকামোতো (Satoshi Nakamoto ছদ্মনাম)',
    explanation: '২০০৮ সালের হোয়াইটপেপারে অজ্ঞাতপরিচয় গবেষক সাতোশি নাকামোতো পিয়ার-টু-পিয়ার ক্রিপ্টোকারেন্সি বিটকয়েন ও ব্লকচেইন নকশা প্রকাশ করেন।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'উদ্বৃত্ত প্রযুক্তি',
    difficulty: 'beginner'
  },
  {
    questionText: 'টু-ফ্যাক্টর অথেন্টিকেশন (2FA) কেন সাইবার নিরাপত্তায় ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['শুধুমাত্র পাসওয়ার্ডের বাইরে ওটিপি বা বায়োমেট্রিক অতিরিক্ত স্তরের নিরাপত্তার জন্য', 'ইন্টারনেট গতি দ্বিগুণ করতে', 'পাসওয়ার্ড মুছে ফেলতে', 'ফাইল কম্প্রেস করতে'],
    correctAnswer: 'শুধুমাত্র পাসওয়ার্ডের বাইরে ওটিপি বা বায়োমেট্রিক অতিরিক্ত স্তরের নিরাপত্তার জন্য',
    explanation: '2FA ব্যবহারকারীর পাসওয়ার্ড চুরি হলেও অতিরিক্ত মোবাইল কোড বা বায়োমেট্রিক নিশ্চিতকরণ ছাড়া অ্যাকাউন্টে অননুমোদিত প্রবেশ রোধ করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সাইবার নিরাপত্তা',
    difficulty: 'beginner'
  },
  {
    questionText: 'ওয়েব পেজ তৈরির জন্য স্ট্যান্ডার্ড মার্কআপ ভাষা কোনটি?',
    type: 'multiple-choice',
    options: ['HTML (HyperText Markup Language)', 'CSS', 'JavaScript', 'C++'],
    correctAnswer: 'HTML (HyperText Markup Language)',
    explanation: 'এইচটিএমএল হলো ওয়েব ডকুমেন্টের কাঠামো তৈরির মার্কআপ ভাষা; সিএসএস হলো স্টাইলিং ও জাভাস্ক্রিপ্ট হলো ইন্টারঅ্যাকটিভিটি।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ওয়েব টেকনোলজি',
    difficulty: 'beginner'
  },
  {
    questionText: 'ইন্টারনেট ইমেইল প্রেরণের জন্য ব্যবহৃত প্রধান প্রোটোকল কোনটি?',
    type: 'multiple-choice',
    options: ['SMTP (Simple Mail Transfer Protocol)', 'POP3', 'IMAP', 'HTTP'],
    correctAnswer: 'SMTP (Simple Mail Transfer Protocol)',
    explanation: 'ইমেইল প্রেরণে এসএমটিপি (পোর্ট ২৫/৫৮৭) ব্যবহৃত হয় এবং সার্ভার থেকে মেইল গ্রহণে POP3 বা IMAP ব্যবহৃত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ইন্টারনেট প্রোটোকল',
    difficulty: 'intermediate'
  },
  {
    questionText: 'ডোমেন নামকে আইপি অ্যাড্রেসে (IP Address) রূপান্তর করে কোন নেটওয়ার্ক সার্ভিস?',
    type: 'multiple-choice',
    options: ['DNS (Domain Name System)', 'DHCP', 'NAT', 'FTP'],
    correctAnswer: 'DNS (Domain Name System)',
    explanation: 'ডিএনএস ইন্টারনেটের ফোনবুক হিসেবে কাজ করে যা মানুষের পাঠযোগ্য নামকে (যেমন google.com) মেশিনের আইপিতে রূপান্তর করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'নেটওয়ার্কিং',
    difficulty: 'beginner'
  },
  {
    questionText: 'কোন নেটওয়ার্ক টপোলজিতে একটি কেন্দ্রীয় হাব বা সুইচ (Central Hub/Switch) ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['স্টার টপোলজি (Star Topology)', 'বাস টপোলজি (Bus)', 'রিং টপোলজি (Ring)', 'মেশ টপোলজি (Mesh)'],
    correctAnswer: 'স্টার টপোলজি (Star Topology)',
    explanation: 'স্টার টপোলজিতে সকল কম্পিউটার বা নোড একটি কেন্দ্রীয় ডিভাইস (সুইচ/হাব)-এর সাথে সরাসরি পয়েন্ট-টু-পয়েন্ট ক্যাবল দিয়ে যুক্ত থাকে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'নেটওয়ার্কিং টপোলজি',
    difficulty: 'beginner'
  },
  {
    questionText: 'ব্লুটুথ (Bluetooth) প্রযুক্তির ওয়্যারলেস কভারেজ সীমা সাধারণত কত দূরত্ব পর্যন্ত কার্যকর?',
    type: 'multiple-choice',
    options: ['প্রায় ১০ মিটার (Short Range PAN)', '১০০ মিটার', '১ কিলোমিটার', '৫০ মিটার'],
    correctAnswer: 'প্রায় ১০ মিটার (Short Range PAN)',
    explanation: 'ব্লুটুথ ২.৪ গিগাহার্টজ ISM ব্যান্ডে পার্সোনাল এরিয়া নেটওয়ার্ক (PAN) তৈরি করে স্বল্প দূরত্বে (সাধারণত ১০ মিটার) ডেটা আদান-প্রদান করে।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'ওয়্যারলেস কমিউনিকেশন',
    difficulty: 'beginner'
  },
  {
    questionText: 'উইন্ডোজ অপারেটিং সিস্টেমে কোনো ফাইল বা ফোল্ডার চিরতরে মুছে ফেলতে (Recycle Bin এ না পাঠিয়ে) কোন শর্টকাট চাপতে হয়?',
    type: 'multiple-choice',
    options: ['Shift + Delete', 'Ctrl + Delete', 'Alt + Delete', 'Delete'],
    correctAnswer: 'Shift + Delete',
    explanation: 'Shift + Delete কমান্ড ব্যবহার করলে ফাইল রিসাইকেল বিনে না গিয়ে স্থায়ীভাবে ফাইল সিস্টেম থেকে মুছে যায়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'উইন্ডোজ শর্টকাট',
    difficulty: 'beginner'
  },
  {
    questionText: 'বাইনারি সংখ্যা পদ্ধতির ভিত্তি (Base) কত এবং এতে কোন দুটি অংক ব্যবহৃত হয়?',
    type: 'multiple-choice',
    options: ['ভিত্তি ২ এবং অংক ০ ও ১', 'ভিত্তি ১০ এবং ০-৯', 'ভিত্তি ৮ এবং ০-৭', 'ভিত্তি ১৬ এবং ০-F'],
    correctAnswer: 'ভিত্তি ২ এবং অংক ০ ও ১',
    explanation: 'ডিজিটাল কম্পিউটার বর্তনীতে অফ ও অন নির্দেশক দুটি অবস্থা থাকায় বাইনারি (০ ও ১) ব্যবহৃত হয়।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সংখ্যা পদ্ধতি',
    difficulty: 'beginner'
  },
  {
    questionText: 'দশমিক সংখ্যা (Decimal) ১৫ এর বাইনারি সমতুল্য মান কত?',
    type: 'multiple-choice',
    options: ['1111', '1010', '1100', '1001'],
    correctAnswer: '1111',
    explanation: '১৫ = ৮ + ৪ + ২ + ১ = ২³ + ২² + ২¹ + ২⁰ = (1111)₂।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সংখ্যা পদ্ধতি রূপান্তর',
    difficulty: 'beginner'
  },
  {
    questionText: 'হেক্সাডেসিমেল সংখ্যা পদ্ধতির ভিত্তি কত এবং এতে ‘A’ এর দশমিক মান কত?',
    type: 'multiple-choice',
    options: ['ভিত্তি ১৬ এবং A = ১০', 'ভিত্তি ৮ এবং A = ৮', 'ভিত্তি ১২ এবং A = ১১', 'ভিত্তি ২০ এবং A = ১৫'],
    correctAnswer: 'ভিত্তি ১৬ এবং A = ১০',
    explanation: 'হেক্সাডেসিমেলে ১৬টি প্রতীক: ০ থেকে ৯ এবং A(10), B(11), C(12), D(13), E(14), F(15)।',
    points: 1,
    subject: 'General Science & ICT',
    topic: 'সংখ্যা পদ্ধতি',
    difficulty: 'intermediate'
  }
];
