import { IJobQuestionItem } from './banglaQuestions.js';

export const teacherJobQuestions: IJobQuestionItem[] = [
  // Primary Assistant Teacher Recruitment (প্রাথমিক সহকারী শিক্ষক নিয়োগ পরীক্ষা) & NTRCA Special
  {
    questionText: 'বাংলাদেশে বাধ্যতামূলক প্রাথমিক শিক্ষা আইন কত সালে প্রণীত হয়?',
    type: 'multiple-choice',
    options: ['১৯৯০ সালে', '১৯৭৩ সালে', '১৯৯৩ সালে', '২০০০ সালে'],
    correctAnswer: '১৯৯০ সালে',
    explanation: '১৯৯০ সালে ‘বাধ্যতামূলক প্রাথমিক শিক্ষা আইন’ জাতীয় সংসদে গৃহীত হয় এবং ১৯৯২ সালের ১লা জানুয়ারি থেকে সারা দেশে পর্যায়ক্রমে কার্যকর হয়।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষা নীতিমালা ও ইতিহাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'কত বছর বয়স পর্যন্ত শিশুদের প্রাথমিক শিক্ষা বাধ্যতামূলক ও অবৈতনিক?',
    type: 'multiple-choice',
    options: ['৬ থেকে ১০ বছর (১ম থেকে ৫ম শ্রেণি)', '৫ থেকে ১২ বছর', '৭ থেকে ১৪ বছর', '৬ থেকে ১৪ বছর'],
    correctAnswer: '৬ থেকে ১০ বছর (১ম থেকে ৫ম শ্রেণি)',
    explanation: 'সংবিধানের ১৭ নং অনুচ্ছেদ এবং বাধ্যতামূলক প্রাথমিক শিক্ষা আইন ১৯৯০ অনুযায়ী ৬ থেকে ১০ বছর বয়সী সকল শিশুর প্রাথমিক শিক্ষা অবৈতনিক ও বাধ্যতামূলক।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষা নীতিমালা',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন সালে বাংলাদেশে প্রাথমিক বিদ্যালয়সমূহকে প্রথম জাতীয়করণ করা হয়?',
    type: 'multiple-choice',
    options: ['১৯৭৩ সালে (বঙ্গবন্ধু শেখ মুজিবুর রহমান কর্তৃক)', '১৯৮০ সালে', '২০১৩ সালে', '১৯৮৫ সালে'],
    correctAnswer: '১৯৭৩ সালে (বঙ্গবন্ধু শেখ মুজিবুর রহমান কর্তৃক)',
    explanation: '১৯৭৩ সালে জাতির পিতা বঙ্গবন্ধু শেখ মুজিবুর রহমান এক ঘোষণায় ৩৬,১৬৫টি প্রাথমিক বিদ্যালয় জাতীয়করণ ও শিক্ষকদের সরকারি মর্যাদা প্রদান করেন। পরবর্তীতে ২০১৩ সালে আরও ২৬,১৯৩টি বিদ্যালয় জাতীয়করণ হয়।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষা ইতিহাস',
    difficulty: 'beginner',
  },
  {
    questionText: 'একটি সংখ্যার তিনগুণের সাথে দ্বিগুণ যোগ করলে ৯০ হয়। সংখ্যাটি কত?',
    type: 'multiple-choice',
    options: ['১৮', '১৫', '২০', '১২'],
    correctAnswer: '১৮',
    explanation: 'ধরি সংখ্যাটি x। ৩x + ২x = ৯০ ⇒ ৫x = ৯০ ⇒ x = ৯০ / ৫ = ১৮। (প্রাইমারি শিক্ষক নিয়োগে নিয়মিত আসা পাটিগণিত)',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক গণিত',
    difficulty: 'beginner',
  },
  {
    questionText: '‘কুঁড়ি’ থেকে ‘ফুল’ ফোটে—এখানে ‘কুঁড়ি’ কোন কারকে কোন বিভক্তি?',
    type: 'multiple-choice',
    options: ['অপাদানে ৫মী', 'করণে ৫মী', 'অধিকরণে ৫মী', 'কর্মে ৫মী'],
    correctAnswer: 'অপাদানে ৫মী',
    explanation: 'কুঁড়ি থেকে ফুল জন্ম নেয় বা জাত হয়, যা অপাদান কারক। ‘থেকে’ অনুসর্গ ৫মী বিভক্তির স্থানীয়।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক বাংলা',
    difficulty: 'beginner',
  },
  {
    questionText: 'Choose the correct English translation: "সে সাঁতার কাটতে জানে না।"',
    type: 'multiple-choice',
    options: [
      'He does not know how to swim.',
      'He does not know to swim.',
      'He cannot knows swimming.',
      'He does not know swimming.',
    ],
    correctAnswer: 'He does not know how to swim.',
    explanation: 'কোনো কাজ করার কৌশল বা দক্ষতা বোঝাতে "know how to + verb" ব্যবহৃত হয়।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক ইংরেজি',
    difficulty: 'beginner',
  },
  {
    questionText: '‘বাক্যের ক্রিয়ার সাথে অন্যান্য পদের যে সম্পর্ক তাকে কী বলে?’',
    type: 'multiple-choice',
    options: ['কারক', 'সমাস', 'সন্ধি', 'প্রত্যয়'],
    correctAnswer: 'কারক',
    explanation: 'ক্রিয়ান্বয়ি কারকম্—অর্থাৎ বাক্যস্থিত ক্রিয়াপদের সঙ্গে নামপদের বা অন্যান্য পদের যে সম্পর্ক তাকে কারক বলে।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক বাংলা',
    difficulty: 'beginner',
  },
  {
    questionText: 'কোন ক্ষুদ্রতম সংখ্যাকে ৪, ৫ এবং ৬ দ্বারা ভাগ করলে প্রতিক্ষেত্রে ৩ অবশিষ্ট থাকে?',
    type: 'multiple-choice',
    options: ['৬৩', '৫৭', '৬৯', '৩৩'],
    correctAnswer: '৬৩',
    explanation: '৪, ৫ ও ৬ এর ল.সা.গু = ৬০। নির্ণেয় ক্ষুদ্রতম সংখ্যা = ৬০ + ৩ = ৬৩।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক গণিত',
    difficulty: 'beginner',
  },
  {
    questionText: 'শহীদ বুদ্ধিজীবী দিবস কোন তারিখে পালিত হয়?',
    type: 'multiple-choice',
    options: ['১৪ই ডিসেম্বর', '১৬ই ডিসেম্বর', '২৫শে মার্চ', '২১শে ফেব্রুয়ারি'],
    correctAnswer: '১৪ই ডিসেম্বর',
    explanation: '১৯৭১ সালের ১৪ই ডিসেম্বর পাকিস্তানি হানাদার বাহিনী পরাজয় নিশ্চিত জেনে এদেশের শ্রেষ্ঠ শিক্ষক, বুদ্ধিজীবী ও চিন্তাবিদদের হত্যা করে। তাই দিনটি শহীদ বুদ্ধিজীবী দিবস।',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'সাধারণ জ্ঞান - বাংলাদেশ',
    difficulty: 'beginner',
  },
  {
    questionText: '‘The pen is mightier than the sword’—This famous proverb means:',
    type: 'multiple-choice',
    options: [
      'The written word and intellect are more powerful than military force',
      'Pens are expensive than swords',
      'A sword cannot cut paper',
      'Writers are physically stronger than soldiers',
    ],
    correctAnswer: 'The written word and intellect are more powerful than military force',
    explanation: 'Edward Bulwer-Lytton coined this proverb signifying that peaceful communication and knowledge exert greater influence than brute force.',
    points: 1,
    subject: 'Primary Teacher Exam',
    topic: 'প্রাথমিক শিক্ষক ইংরেজি',
    difficulty: 'beginner',
  },
];
