import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Quiz from '../models/Quiz.js';
import QuizAttempt from '../models/QuizAttempt.js';
import QuestionBank from '../models/QuestionBank.js';
import ClassGroup from '../models/ClassGroup.js';
import Assignment from '../models/Assignment.js';
import Notification from '../models/Notification.js';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/quiz_room_db';

export const seedDatabase = async () => {
  try {
    console.log('[Seeder] Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('[Seeder] Connected to database');

    console.log('[Seeder] Clearing old records...');
    await Promise.all([
      User.deleteMany({}),
      Quiz.deleteMany({}),
      QuizAttempt.deleteMany({}),
      QuestionBank.deleteMany({}),
      ClassGroup.deleteMany({}),
      Assignment.deleteMany({}),
      Notification.deleteMany({}),
    ]);

    console.log('[Seeder] Creating Demo Users...');
    // Demo Teachers
    const teacher1 = await User.create({
      name: 'Prof. Sarah Connor',
      email: 'teacher@example.com',
      password: 'password123',
      role: 'teacher',
      bio: 'Senior Full-Stack Architect & Educational Instructor. Specializes in modern frontend engineering, web accessibility, and distributed architectures.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=SarahConnor',
    });

    const teacher2 = await User.create({
      name: 'Alex Rivera',
      email: 'alex.teacher@example.com',
      password: 'password123',
      role: 'teacher',
      bio: 'Staff Engineer & Computer Science Lecturer specializing in JavaScript runtimes, Python data engineering, and modern cloud deployment.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=AlexRivera',
    });

    // Demo Students
    const student1 = await User.create({
      name: 'David Miller',
      email: 'student@example.com',
      password: 'password123',
      role: 'student',
      bio: 'Independent learner mastering React, TypeScript, Next.js, and Python backend engineering.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=DavidMiller',
    });

    const student2 = await User.create({
      name: 'Emma Watson',
      email: 'emma.student@example.com',
      password: 'password123',
      role: 'student',
      bio: 'Frontend enthusiast focused on UI systems, modern CSS, and component testing.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=EmmaWatson',
    });

    const student3 = await User.create({
      name: 'Liam Chen',
      email: 'liam.student@example.com',
      password: 'password123',
      role: 'student',
      bio: 'Full-stack apprentice exploring Node.js concurrency and Python web frameworks.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=LiamChen',
    });

    const student4 = await User.create({
      name: 'Sophia Rodriguez',
      email: 'sophia.student@example.com',
      password: 'password123',
      role: 'student',
      bio: 'Design engineer passionate about Next.js App Router and semantic web standards.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=SophiaRodriguez',
    });

    const student5 = await User.create({
      name: 'Noah Kim',
      email: 'noah.student@example.com',
      password: 'password123',
      role: 'student',
      bio: 'Self-taught developer building scalable microservices and technical quizzes.',
      avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=NoahKim',
    });

    console.log('[Seeder] Creating Published Quizzes across 8 Topics...');

    // 1. HTML5 Semantics & Web Standards
    const quizHtml = await Quiz.create({
      title: 'HTML5 Semantic Architecture & Essentials',
      description: 'Master modern semantic elements, accessibility best practices, metadata, and document hierarchies.',
      subject: 'HTML',
      difficulty: 'beginner',
      teacher: teacher1._id,
      status: 'published',
      timeLimit: 15,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'html101',
      attemptsCount: 28,
      questions: [
        {
          questionText: 'What does HTML stand for?',
          type: 'multiple-choice',
          options: ['Hyper Text Markup Language', 'High Text Machine Language', 'Hyperlinks Text Mark Language', 'Home Tool Markup Language'],
          correctAnswer: 'Hyper Text Markup Language',
          explanation: 'HTML stands for Hyper Text Markup Language, the standard markup language for creating web documents.',
          points: 1,
        },
        {
          questionText: 'Which HTML5 element represents a thematic grouping of content, typically with a heading?',
          type: 'multiple-choice',
          options: ['<section>', '<div>', '<span>', '<aside>'],
          correctAnswer: '<section>',
          explanation: '<section> defines thematic groupings of related content on a web page, unlike a generic layout <div>.',
          points: 1,
        },
        {
          questionText: 'Which tag should be used for standalone, distributable content such as a blog post or news story?',
          type: 'multiple-choice',
          options: ['<article>', '<aside>', '<main>', '<section>'],
          correctAnswer: '<article>',
          explanation: '<article> represents a self-contained composition in a document that is independently reusable and syndicatable.',
          points: 1,
        },
        {
          questionText: 'The <aside> element is intended strictly for content tangentially related to the content around it.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'Yes, <aside> represents content like sidebars, callout boxes, or related links.',
          points: 1,
        },
        {
          questionText: 'Which attribute provides accessible alternative information for an image if a user cannot view it?',
          type: 'multiple-choice',
          options: ['alt', 'title', 'src', 'caption'],
          correctAnswer: 'alt',
          explanation: 'The alt attribute is essential for screen readers and search engines to understand image context.',
          points: 1,
        },
        {
          questionText: 'Which HTML5 element is used to enclose primary navigation links across an application?',
          type: 'multiple-choice',
          options: ['<nav>', '<menu>', '<header>', '<links>'],
          correctAnswer: '<nav>',
          explanation: 'The <nav> HTML element represents a section of a page whose purpose is to provide navigation links.',
          points: 1,
        },
        {
          questionText: 'Which element is used to group caption text together with a media item or diagram?',
          type: 'multiple-choice',
          options: ['<figure> and <figcaption>', '<picture> and <summary>', '<image> and <desc>', '<canvas> and <legend>'],
          correctAnswer: '<figure> and <figcaption>',
          explanation: '<figure> specifies self-contained content and <figcaption> adds a dedicated, accessible caption to it.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of the `<!DOCTYPE html>` declaration at the very top of an HTML document?',
          type: 'multiple-choice',
          options: ['Enforces standard rendering mode in modern browsers', 'Imports the HTML5 JavaScript runtime', 'Connects the document to an external XML schema', 'Sets the document character encoding'],
          correctAnswer: 'Enforces standard rendering mode in modern browsers',
          explanation: 'The doctype tells the browser to render the page in standards mode rather than quirks mode.',
          points: 1,
        },
        {
          questionText: 'Which meta tag configuration ensures responsive scaling across mobile device viewports?',
          type: 'multiple-choice',
          options: [
            '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
            '<meta name="screen" content="device-width, zoom=true">',
            '<meta http-equiv="responsive" content="enable">',
            '<meta name="display" content="mobile-first">',
          ],
          correctAnswer: '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
          explanation: 'This viewport meta tag instructs mobile browsers to match screen width in CSS pixels and set initial scale to 1.',
          points: 1,
        },
        {
          questionText: 'In HTML forms, which attribute prevents submission when an input field is empty?',
          type: 'multiple-choice',
          options: ['required', 'mandatory', 'validate', 'not-null'],
          correctAnswer: 'required',
          explanation: 'The required boolean attribute triggers browser client-side constraint validation before form submit.',
          points: 1,
        },
        {
          questionText: 'The <main> element can appear more than once in an HTML document provided they are not hidden.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'A document must not have more than one <main> element that does not have the hidden attribute specified.',
          points: 1,
        },
        {
          questionText: 'Which element represents text that should be treated as strongly important or urgent?',
          type: 'multiple-choice',
          options: ['<strong>', '<b>', '<mark>', '<em>'],
          correctAnswer: '<strong>',
          explanation: '<strong> conveys strong importance, seriousness, or urgency, whereas <b> is purely visual bold styling without semantic weight.',
          points: 1,
        },
        {
          questionText: 'What is the primary role of the `aria-label` attribute in HTML?',
          type: 'multiple-choice',
          options: ['Defines a string that labels an interactive element for assistive technologies', 'Styles the element with CSS hover tooltips', 'Sets a localized translation key for i18n', 'Specifies validation rules for form inputs'],
          correctAnswer: 'Defines a string that labels an interactive element for assistive technologies',
          explanation: 'aria-label provides an accessible name for an element when no visible label exists.',
          points: 1,
        },
        {
          questionText: 'Which tag is used to embed client-side vector graphics directly in an HTML document?',
          type: 'multiple-choice',
          options: ['<svg>', '<canvas>', '<raster>', '<vector>'],
          correctAnswer: '<svg>',
          explanation: '<svg> defines scalable vector graphics inline in XML format that can be styled via CSS and scripted.',
          points: 1,
        },
        {
          questionText: 'Which input type provides an accessible, native date picker on modern browsers?',
          type: 'multiple-choice',
          options: ['type="date"', 'type="calendar"', 'type="datetime"', 'type="timestamp"'],
          correctAnswer: 'type="date"',
          explanation: '<input type="date"> allows users to enter a calendar date using native browser controls.',
          points: 1,
        },
      ],
    });

    // 2. Modern CSS: Flexbox & Grid
    const quizCss = await Quiz.create({
      title: 'Modern CSS: Flexbox, Grid & Responsive Layouts',
      description: 'Master flex containers, grid alignment, CSS variables, cascade layers, and responsive techniques.',
      subject: 'CSS',
      difficulty: 'intermediate',
      teacher: teacher1._id,
      status: 'published',
      timeLimit: 20,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'css201',
      attemptsCount: 32,
      questions: [
        {
          questionText: 'In CSS Flexbox, what property aligns flex items along the cross axis?',
          type: 'multiple-choice',
          options: ['align-items', 'justify-content', 'align-content', 'flex-direction'],
          correctAnswer: 'align-items',
          explanation: 'align-items controls cross-axis alignment, whereas justify-content aligns items along the main axis.',
          codeSnippet: '.container {\n  display: flex;\n  align-items: center;\n}',
          points: 1,
        },
        {
          questionText: 'What is the default value of the `flex-direction` property?',
          type: 'multiple-choice',
          options: ['row', 'column', 'row-reverse', 'wrap'],
          correctAnswer: 'row',
          explanation: 'flex-direction defaults to "row", positioning children horizontally from left to right.',
          points: 1,
        },
        {
          questionText: 'In CSS Grid, which CSS unit represents a fraction of the available free space in the grid container?',
          type: 'multiple-choice',
          options: ['fr', 'rem', '%', 'vw'],
          correctAnswer: 'fr',
          explanation: 'The fr unit represents a fraction of leftover space inside the grid container.',
          codeSnippet: 'grid-template-columns: 1fr 2fr 1fr;',
          points: 1,
        },
        {
          questionText: 'The `box-sizing: border-box` property includes padding and border inside an element\'s total width and height.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'With border-box, padding and border do not cause an element to expand beyond its declared width/height.',
          points: 1,
        },
        {
          questionText: 'Which selector has the highest specificity score?',
          type: 'multiple-choice',
          options: ['#header', '.nav-item.active', 'header nav a', 'div p:first-child'],
          correctAnswer: '#header',
          explanation: 'An ID selector has specificity (0,1,0,0), surpassing any number of class or element selectors.',
          points: 1,
        },
        {
          questionText: 'What does the CSS `gap` property do in Flexbox and Grid?',
          type: 'multiple-choice',
          options: ['Sets space (gutters) between grid or flex items', 'Adds padding around the parent container', 'Sets the outer margin of the container', 'Forces items to wrap to a new line'],
          correctAnswer: 'Sets space (gutters) between grid or flex items',
          explanation: 'The gap property defines spacing between items without adding unwanted margins to outer edges.',
          points: 1,
        },
        {
          questionText: 'How do you access a CSS custom property (variable) named `--brand-primary`?',
          type: 'multiple-choice',
          options: ['var(--brand-primary)', '$brand-primary', 'prop(--brand-primary)', 'get(--brand-primary)'],
          correctAnswer: 'var(--brand-primary)',
          explanation: 'The var() CSS function evaluates the value of a custom property.',
          codeSnippet: 'color: var(--brand-primary, #6366f1);',
          points: 1,
        },
        {
          questionText: 'Which CSS property creates a new stacking context without modifying position or z-index?',
          type: 'multiple-choice',
          options: ['opacity: 0.99', 'display: block', 'overflow: visible', 'cursor: pointer'],
          correctAnswer: 'opacity: 0.99',
          explanation: 'An opacity value less than 1 automatically generates a new stacking context for the element.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of `object-fit: cover` on an <img> or <video> element?',
          type: 'multiple-choice',
          options: [
            'Resizes content to cover container while maintaining aspect ratio, clipping if necessary',
            'Stretches content to completely fill container ignoring aspect ratio',
            'Scales down content until entire media is visible inside box',
            'Centers content without scaling',
          ],
          correctAnswer: 'Resizes content to cover container while maintaining aspect ratio, clipping if necessary',
          explanation: 'cover preserves aspect ratio while filling the dimensions, cropping overflow.',
          points: 1,
        },
        {
          questionText: 'Which modern CSS pseudo-class matches an element if any selector in its argument list matches?',
          type: 'multiple-choice',
          options: [':is()', ':any()', ':has()', ':where()'],
          correctAnswer: ':is()',
          explanation: ':is() takes a selector list and matches any element that can be selected by one of the selectors in that list.',
          points: 1,
        },
        {
          questionText: 'The `:has()` relational pseudo-class allows styling an element based on its descendants or subsequent siblings.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: ':has() is the "parent selector" in CSS, styling an element if it contains elements matching the inner selector.',
          points: 1,
        },
        {
          questionText: 'In Flexbox, what does setting `flex: 1 1 0%` represent?',
          type: 'multiple-choice',
          options: [
            'flex-grow: 1, flex-shrink: 1, flex-basis: 0%',
            'flex-direction: 1, flex-wrap: 1, flex-order: 0%',
            'flex-align: 1, flex-justify: 1, flex-basis: 0%',
            'flex-order: 1, flex-basis: 1, flex-grow: 0%',
          ],
          correctAnswer: 'flex-grow: 1, flex-shrink: 1, flex-basis: 0%',
          explanation: 'The flex shorthand corresponds to flex-grow, flex-shrink, and flex-basis respectively.',
          points: 1,
        },
        {
          questionText: 'Which CSS media query feature detects if the user preferred a dark color scheme in their operating system?',
          type: 'multiple-choice',
          options: ['prefers-color-scheme: dark', 'device-theme: dark', 'color-mode: dark', 'system-dark-mode: true'],
          correctAnswer: 'prefers-color-scheme: dark',
          explanation: '@media (prefers-color-scheme: dark) targets system-level dark mode preferences.',
          points: 1,
        },
        {
          questionText: 'What does `position: sticky` do?',
          type: 'multiple-choice',
          options: [
            'Treats element as relative until a scroll threshold is met, then fixes it relative to its scrolling ancestor',
            'Permanently pins element to viewport coordinates',
            'Keeps element locked to the bottom of the screen',
            'Prevents parent element from scrolling',
          ],
          correctAnswer: 'Treats element as relative until a scroll threshold is met, then fixes it relative to its scrolling ancestor',
          explanation: 'Sticky positioning toggles between relative and fixed positioning depending on scroll offset.',
          points: 1,
        },
        {
          questionText: 'Which CSS function allows performing mathematical operations including mixing units (e.g. 100% - 20px)?',
          type: 'multiple-choice',
          options: ['calc()', 'math()', 'sum()', 'eval()'],
          correctAnswer: 'calc()',
          explanation: 'calc() allows dynamic math calculations mixing relative and absolute units.',
          points: 1,
        },
      ],
    });

    // 3. JavaScript ES6+ Deep Dive & Asynchronous Core
    const quizJs = await Quiz.create({
      title: 'JavaScript ES6+ Deep Dive & Asynchronous Core',
      description: 'Test your understanding of closures, the event loop, Promises, prototypes, and modern ES features.',
      subject: 'JavaScript',
      difficulty: 'advanced',
      teacher: teacher2._id,
      status: 'published',
      timeLimit: 25,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'js301',
      attemptsCount: 45,
      questions: [
        {
          questionText: 'What is the output of the following code snippet?',
          type: 'multiple-choice',
          options: ['undefined', 'ReferenceError', '2', 'NaN'],
          correctAnswer: 'undefined',
          explanation: 'Variables declared with `var` are hoisted and initialized with undefined in the creation phase.',
          codeSnippet: 'console.log(x);\nvar x = 2;',
          points: 2,
        },
        {
          questionText: 'Which array method creates a new array populated with the results of calling a provided function on every element?',
          type: 'multiple-choice',
          options: ['map()', 'filter()', 'forEach()', 'reduce()'],
          correctAnswer: 'map()',
          explanation: 'Array.prototype.map() transforms each element and returns a new array of the same length.',
          points: 1,
        },
        {
          questionText: 'What does `Promise.all()` do if any single promise rejects?',
          type: 'multiple-choice',
          options: [
            'Immediately rejects with the reason of the first promise that rejected',
            'Waits for all promises and returns only resolved ones',
            'Returns undefined',
            'Retries the failed promise once',
          ],
          correctAnswer: 'Immediately rejects with the reason of the first promise that rejected',
          explanation: 'Promise.all has fail-fast behavior: if any promise rejects, the aggregate promise rejects immediately.',
          points: 2,
        },
        {
          questionText: 'In JavaScript, `const` declarations prevent the mutation of object properties.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'const prevents reassignment of the variable identifier, but nested properties can still be modified.',
          codeSnippet: 'const user = { name: "Alice" };\nuser.name = "Bob"; // Valid!\nuser = {}; // TypeError!',
          points: 1,
        },
        {
          questionText: 'What is the return value of `typeof null` in standard JavaScript?',
          type: 'multiple-choice',
          options: ['"object"', '"null"', '"undefined"', '"boolean"'],
          correctAnswer: '"object"',
          explanation: 'typeof null === "object" is a historic bug retained for web compatibility.',
          points: 1,
        },
        {
          questionText: 'Which keyword in async functions pauses execution until a Promise resolves or rejects?',
          type: 'multiple-choice',
          options: ['await', 'defer', 'pause', 'yield'],
          correctAnswer: 'await',
          explanation: 'await pauses execution of the enclosing async function until the promise settles.',
          points: 1,
        },
        {
          questionText: 'What is a closure in JavaScript?',
          type: 'multiple-choice',
          options: [
            'A function bundled together with references to its lexical environment',
            'A function that immediately terminates execution',
            'An anonymous function that runs once inside a loop',
            'A private class constructor',
          ],
          correctAnswer: 'A function bundled together with references to its lexical environment',
          explanation: 'A closure gives an inner function access to an outer function\'s scope even after the outer function has closed.',
          points: 2,
        },
        {
          questionText: 'Which queue in the JavaScript Event Loop handles Promises and queueMicrotask callbacks?',
          type: 'multiple-choice',
          options: ['Microtask Queue', 'Macrotask / Task Queue', 'Call Stack Queue', 'Render Queue'],
          correctAnswer: 'Microtask Queue',
          explanation: 'Microtasks are processed immediately after the current call stack clears, before macrotasks (e.g. setTimeout).',
          points: 2,
        },
        {
          questionText: 'What does the nullish coalescing operator `??` check for?',
          type: 'multiple-choice',
          options: ['null or undefined only', 'Any falsy value (0, false, "", null, undefined)', 'false and 0 only', 'NaN only'],
          correctAnswer: 'null or undefined only',
          explanation: 'Unlike || which checks for any falsy value, ?? only falls back if the left-hand operand is null or undefined.',
          points: 1,
        },
        {
          questionText: 'What does `Object.freeze()` do to a JavaScript object?',
          type: 'multiple-choice',
          options: [
            'Prevents extensions and makes existing properties non-writable and non-configurable (shallow)',
            'Recursively freezes all nested child objects',
            'Converts object into an immutable JSON string',
            'Deletes all symbol properties',
          ],
          correctAnswer: 'Prevents extensions and makes existing properties non-writable and non-configurable (shallow)',
          explanation: 'Object.freeze shallowly freezes properties so they cannot be added, deleted, or modified.',
          points: 2,
        },
        {
          questionText: 'Arrow functions do not bind their own `this`, `arguments`, `super`, or `new.target`.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'Arrow functions retain the `this` value of their enclosing lexical context.',
          points: 1,
        },
        {
          questionText: 'What is the result of `0.1 + 0.2 === 0.3` in JavaScript?',
          type: 'multiple-choice',
          options: ['false', 'true', 'TypeError', 'undefined'],
          correctAnswer: 'false',
          explanation: 'Due to IEEE 754 binary floating-point representation, 0.1 + 0.2 equals 0.30000000000000004.',
          points: 2,
        },
        {
          questionText: 'Which method transforms a Map or key-value pair array into an Object?',
          type: 'multiple-choice',
          options: ['Object.fromEntries()', 'Object.entries()', 'Object.assign()', 'Object.values()'],
          correctAnswer: 'Object.fromEntries()',
          explanation: 'Object.fromEntries() converts an iterable of key-value pairs into a standard plain object.',
          points: 1,
        },
        {
          questionText: 'What happens when `JSON.stringify()` encounters a function inside an object?',
          type: 'multiple-choice',
          options: ['The function property is omitted', 'Throws a TypeError', 'Serializes function to string code', 'Serializes to null'],
          correctAnswer: 'The function property is omitted',
          explanation: 'Functions, undefined, and symbols are omitted when found in non-array objects during JSON serialization.',
          points: 1,
        },
        {
          questionText: 'What does `Promise.race()` return?',
          type: 'multiple-choice',
          options: [
            'A promise that fulfills or rejects as soon as any of the promises fulfills or rejects',
            'The promise with the fastest CPU execution',
            'Only resolved promises',
            'An array containing all promises',
          ],
          correctAnswer: 'A promise that fulfills or rejects as soon as any of the promises fulfills or rejects',
          explanation: 'Promise.race returns the outcome of whichever promise settles first.',
          points: 2,
        },
      ],
    });

    // 4. TypeScript Mastery: Generics, Narrowing & Strict Types
    const quizTs = await Quiz.create({
      title: 'TypeScript Mastery: Generics, Narrowing & Strict Types',
      description: 'Deepen your TypeScript expertise with generics, conditional types, discriminated unions, and compiler flags.',
      subject: 'TypeScript',
      difficulty: 'intermediate',
      teacher: teacher1._id,
      status: 'published',
      timeLimit: 20,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'ts401',
      attemptsCount: 36,
      questions: [
        {
          questionText: 'Which TypeScript utility type constructs a type with all properties of T set to optional?',
          type: 'multiple-choice',
          options: ['Partial<T>', 'Required<T>', 'Readonly<T>', 'Record<K, T>'],
          correctAnswer: 'Partial<T>',
          explanation: 'Partial<T> returns a type with all properties marked as optional (?).',
          points: 1,
        },
        {
          questionText: 'What is the purpose of the `unknown` type compared to `any` in TypeScript?',
          type: 'multiple-choice',
          options: [
            'unknown is type-safe; you cannot perform operations on it without type narrowing first',
            'unknown behaves identically to any with a different syntax',
            'unknown only allows null and undefined values',
            'unknown disables all TypeScript compiler warnings',
          ],
          correctAnswer: 'unknown is type-safe; you cannot perform operations on it without type narrowing first',
          explanation: 'unknown forces developers to perform runtime type checks before accessing properties or invoking methods.',
          points: 2,
        },
        {
          questionText: 'What is a "Discriminated Union" in TypeScript?',
          type: 'multiple-choice',
          options: [
            'A union of object types that share a common literal discriminant property for narrowing',
            'A union of primitive string and number types',
            'An interface that extends multiple classes',
            'A type alias that excludes undefined',
          ],
          correctAnswer: 'A union of object types that share a common literal discriminant property for narrowing',
          explanation: 'A common property (e.g. kind or type) allows the compiler to narrow down the specific type in a switch/if block.',
          points: 2,
        },
        {
          questionText: 'The `never` type represents the type of values that never occur, such as a function that always throws.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'never is the bottom type in TypeScript, used for functions that never return or unreachable code branches.',
          points: 1,
        },
        {
          questionText: 'Which utility type constructs a type by picking a set of properties Keys from Type T?',
          type: 'multiple-choice',
          options: ['Pick<T, Keys>', 'Omit<T, Keys>', 'Extract<T, U>', 'Exclude<T, U>'],
          correctAnswer: 'Pick<T, Keys>',
          explanation: 'Pick<T, K> constructs a type with chosen keys K from T.',
          points: 1,
        },
        {
          questionText: 'What does the `as const` assertion do when applied to an array or object literal?',
          type: 'multiple-choice',
          options: [
            'Infers deepest literal types and marks all properties as readonly',
            'Creates a runtime JavaScript Object.freeze call',
            'Prevents the variable from being exported',
            'Converts object into an enum',
          ],
          correctAnswer: 'Infers deepest literal types and marks all properties as readonly',
          explanation: 'as const creates readonly tuple/literal types at compile time without any runtime overhead.',
          points: 2,
        },
        {
          questionText: 'Which compiler flag enforces that functions must return a value along all possible code paths?',
          type: 'multiple-choice',
          options: ['noImplicitReturns', 'strictNullChecks', 'noImplicitAny', 'exactOptionalPropertyTypes'],
          correctAnswer: 'noImplicitReturns',
          explanation: 'noImplicitReturns reports errors when any code paths in a function with a return type do not return.',
          points: 1,
        },
        {
          questionText: 'What is the syntax for a user-defined type guard function checking if `pet` is a `Dog`?',
          type: 'multiple-choice',
          options: [
            'function isDog(pet: Animal): pet is Dog',
            'function isDog(pet: Animal): boolean as Dog',
            'function isDog(pet: Animal): Dog | Animal',
            'function isDog(pet: Animal) -> Dog',
          ],
          correctAnswer: 'function isDog(pet: Animal): pet is Dog',
          explanation: 'The type predicate `parameterName is Type` informs TypeScript of the narrowed type upon returning true.',
          points: 2,
        },
        {
          questionText: 'Interfaces in TypeScript support declaration merging, whereas type aliases cannot be merged.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'Multiple interface declarations with the same name automatically merge into a single definition.',
          points: 1,
        },
        {
          questionText: 'What does the `keyof` operator return in TypeScript?',
          type: 'multiple-choice',
          options: ['A union of known, public property names of a type', 'An array of object values', 'The length of keys in an interface', 'A JSON string of keys'],
          correctAnswer: 'A union of known, public property names of a type',
          explanation: 'keyof T produces a string or numeric literal union of keys.',
          points: 1,
        },
        {
          questionText: 'Which utility type excludes properties Keys from Type T?',
          type: 'multiple-choice',
          options: ['Omit<T, Keys>', 'Pick<T, Keys>', 'Exclude<T, U>', 'Extract<T, U>'],
          correctAnswer: 'Omit<T, Keys>',
          explanation: 'Omit<T, K> constructs a type with all properties of T except Keys.',
          points: 1,
        },
        {
          questionText: 'What is a Generic Constraint in TypeScript?',
          type: 'multiple-choice',
          options: [
            'Using the `extends` keyword to ensure a generic type parameter satisfies a particular contract',
            'Limiting the number of generics in a file',
            'Restricting a generic to string primitives only',
            'A compiler error when generics are missing',
          ],
          correctAnswer: 'Using the `extends` keyword to ensure a generic type parameter satisfies a particular contract',
          explanation: '<T extends { id: string }>() ensures T has at least an id string property.',
          points: 2,
        },
        {
          questionText: 'What does the non-null assertion operator `!` tell the TypeScript compiler?',
          type: 'multiple-choice',
          options: [
            'Asserts that an expression is not null or undefined, overriding the compiler\'s check',
            'Inverts the boolean value at compile time',
            'Throws a runtime error if value is null',
            'Converts value to a boolean',
          ],
          correctAnswer: 'Asserts that an expression is not null or undefined, overriding the compiler\'s check',
          explanation: 'postfix ! removes null and undefined from the type without runtime emission.',
          points: 1,
        },
        {
          questionText: 'What is the output type of `ReturnType<typeof myFunc>`?',
          type: 'multiple-choice',
          options: ['The return type of function myFunc', 'The parameters tuple of myFunc', 'A Promise of myFunc', 'The function constructor'],
          correctAnswer: 'The return type of function myFunc',
          explanation: 'ReturnType<T> extracts the returned type of a function type T.',
          points: 1,
        },
        {
          questionText: 'Which TypeScript flag enables all strict type checking options in tsconfig.json?',
          type: 'multiple-choice',
          options: ['"strict": true', '"typeSafety": "maximum"', '"strictAll": true', '"fullChecking": true'],
          correctAnswer: '"strict": true',
          explanation: '"strict": true enables strictNullChecks, noImplicitAny, noImplicitThis, and other guardrails.',
          points: 1,
        },
      ],
    });

    // 5. React 18 Architecture: Hooks, State, Component Lifecycle & Performance
    const quizReact = await Quiz.create({
      title: 'React 18 Architecture: Hooks, State & Component Lifecycle',
      description: 'Evaluate your React mastery across useEffect, useMemo, useCallback, reconciliation, Context, and Concurrent features.',
      subject: 'React',
      difficulty: 'intermediate',
      teacher: teacher1._id,
      status: 'published',
      timeLimit: 20,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'react501',
      attemptsCount: 42,
      questions: [
        {
          questionText: 'Why should you NOT call React Hooks inside loops, conditions, or nested functions?',
          type: 'multiple-choice',
          options: [
            'React relies on the order of hook calls to correctly associate state with component instances',
            'Hooks produce runtime memory leaks inside loops',
            'JavaScript syntax prohibits calling functions inside loops',
            'Vite and Webpack bundle sizes will double',
          ],
          correctAnswer: 'React relies on the order of hook calls to correctly associate state with component instances',
          explanation: 'React maintains an internal linked list of hooks per component, strictly indexed by call order.',
          points: 2,
        },
        {
          questionText: 'What is the primary difference between `useMemo` and `useCallback`?',
          type: 'multiple-choice',
          options: [
            'useMemo caches the result of a calculation; useCallback caches a function definition',
            'useMemo is for class components; useCallback is for functional components',
            'useCallback runs asynchronously; useMemo runs synchronously',
            'useMemo cannot take a dependency array',
          ],
          correctAnswer: 'useMemo caches the result of a calculation; useCallback caches a function definition',
          explanation: 'useCallback(fn, deps) is equivalent to useMemo(() => fn, deps).',
          points: 2,
        },
        {
          questionText: 'What triggers a React component to re-render?',
          type: 'multiple-choice',
          options: [
            'A change in the component\'s state or props, or a re-render of its parent',
            'Any mouse click on the DOM window',
            'Modifying a useRef value',
            'Invoking a regular utility helper function',
          ],
          correctAnswer: 'A change in the component\'s state or props, or a re-render of its parent',
          explanation: 'React re-renders components whenever state, props, or parent components update.',
          points: 1,
        },
        {
          questionText: 'Updating the `current` property of a `useRef` causes the component to re-render.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'useRef holds a mutable reference whose changes do not trigger a component re-render.',
          points: 1,
        },
        {
          questionText: 'What is the role of the `key` prop when rendering lists in React?',
          type: 'multiple-choice',
          options: [
            'Helps React identify which items have changed, added, or removed during Reconciliation',
            'Applies unique CSS ID selectors to DOM elements',
            'Enables database primary key foreign constraints',
            'Controls keyboard tab index navigation',
          ],
          correctAnswer: 'Helps React identify which items have changed, added, or removed during Reconciliation',
          explanation: 'Keys allow React\'s diffing algorithm to match tree items across renders efficiently.',
          points: 2,
        },
        {
          questionText: 'What is React 18 Automatic Batching?',
          type: 'multiple-choice',
          options: [
            'Multiple state updates within promises, setTimeout, and native event handlers are grouped into a single re-render',
            'Automatic compilation of TypeScript code into web bundles',
            'Batching API requests into GraphQL payloads',
            'Merging multiple CSS stylesheets',
          ],
          correctAnswer: 'Multiple state updates within promises, setTimeout, and native event handlers are grouped into a single re-render',
          explanation: 'React 18 batches all state updates regardless of where they originate for higher performance.',
          points: 2,
        },
        {
          questionText: 'When does the cleanup function in a `useEffect` run?',
          type: 'multiple-choice',
          options: [
            'Before the effect runs again, and when the component unmounts',
            'Only once when the browser tab closes',
            'Immediately before the JSX renders',
            'Simultaneously with state updates',
          ],
          correctAnswer: 'Before the effect runs again, and when the component unmounts',
          explanation: 'Effect cleanup prevents memory leaks by releasing subscriptions before re-execution and on unmount.',
          points: 1,
        },
        {
          questionText: 'Which React hook is used to dispatch actions and manage complex state logic similar to Redux?',
          type: 'multiple-choice',
          options: ['useReducer', 'useContext', 'useState', 'useTransition'],
          correctAnswer: 'useReducer',
          explanation: 'useReducer(reducer, initialArg) is suited for complex state logic with actions and reducers.',
          points: 1,
        },
        {
          questionText: 'What does the `useTransition` hook in React 18 do?',
          type: 'multiple-choice',
          options: [
            'Marks state updates as non-urgent transitions so the UI remains responsive to urgent input',
            'Applies CSS keyframe animations between route pages',
            'Animates SVG transformations',
            'Swaps between light and dark themes',
          ],
          correctAnswer: 'Marks state updates as non-urgent transitions so the UI remains responsive to urgent input',
          explanation: 'useTransition lets you prioritize urgent user interactions over heavier background rendering.',
          points: 2,
        },
        {
          questionText: 'In React Context API, what happens to consumer components when the Context Provider value changes?',
          type: 'multiple-choice',
          options: [
            'All consumer components that call useContext for that Context re-render',
            'Only the component holding the Provider re-renders',
            'Nothing re-renders until page reload',
            'React throws a context collision warning',
          ],
          correctAnswer: 'All consumer components that call useContext for that Context re-render',
          explanation: 'All consuming components re-render whenever the provider passes a new reference value.',
          points: 1,
        },
        {
          questionText: 'React components wrapped with `React.memo` will always re-render when their parent re-renders, regardless of prop changes.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'React.memo performs shallow prop comparison and skips re-rendering if props are unchanged.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of `React.Suspense`?',
          type: 'multiple-choice',
          options: [
            'Displays a fallback UI while child components are loading asynchronous code or data',
            'Catches uncaught runtime JavaScript errors like an Error Boundary',
            'Delays component unmounting by 500ms',
            'Pauses JavaScript execution until user clicks',
          ],
          correctAnswer: 'Displays a fallback UI while child components are loading asynchronous code or data',
          explanation: 'Suspense lets you declaratively specify a loading indicator while components wait for data or dynamic imports.',
          points: 2,
        },
        {
          questionText: 'Why should you avoid using list array indices as keys in React when the list can change order?',
          type: 'multiple-choice',
          options: [
            'Reordering or inserting items leads to component state confusion and unexpected rendering artifacts',
            'React will throw a fatal syntax error',
            'It slows down network requests',
            'Indices cannot be converted to strings',
          ],
          correctAnswer: 'Reordering or inserting items leads to component state confusion and unexpected rendering artifacts',
          explanation: 'Index keys tie state to position rather than identity, causing stale input states upon item reorder.',
          points: 2,
        },
        {
          questionText: 'Which hook should be used when you need to read layout from the DOM and synchronously re-render before browser paint?',
          type: 'multiple-choice',
          options: ['useLayoutEffect', 'useEffect', 'useInsertionEffect', 'useImperativeHandle'],
          correctAnswer: 'useLayoutEffect',
          explanation: 'useLayoutEffect fires synchronously after all DOM mutations but before the browser repaints screen.',
          points: 2,
        },
        {
          questionText: 'What is Prop Drilling in React applications?',
          type: 'multiple-choice',
          options: [
            'Passing props down through multiple layers of intermediate components that do not need the data themselves',
            'Drilling holes in JSON schemas',
            'Converting props into state variables',
            'Exporting props outside of the module',
          ],
          correctAnswer: 'Passing props down through multiple layers of intermediate components that do not need the data themselves',
          explanation: 'Prop drilling occurs when data is manually threaded through many component levels to reach a deeply nested child.',
          points: 1,
        },
      ],
    });

    // 6. Next.js App Router, Server Components & Full-Stack Routing
    const quizNext = await Quiz.create({
      title: 'Next.js App Router, Server Components & Full-Stack Routing',
      description: 'Test your understanding of the Next.js App Router, Server vs Client Components, Server Actions, SSR, and caching strategies.',
      subject: 'Next.js',
      difficulty: 'advanced',
      teacher: teacher2._id,
      status: 'published',
      timeLimit: 25,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'next601',
      attemptsCount: 39,
      questions: [
        {
          questionText: 'In the Next.js App Router, what is the default component type inside the `app/` directory?',
          type: 'multiple-choice',
          options: ['React Server Component (RSC)', 'React Client Component', 'Static HTML Template', 'Edge Worker Function'],
          correctAnswer: 'React Server Component (RSC)',
          explanation: 'All components inside the App Router are React Server Components by default unless marked with "use client".',
          points: 2,
        },
        {
          questionText: 'Which directive must be added at the very top of a file to declare a Client Component in Next.js?',
          type: 'multiple-choice',
          options: ['"use client"', '"client only"', '"use client-side"', '"directive: client"'],
          correctAnswer: '"use client"',
          explanation: 'The "use client" directive marks the boundary between server-only and client-hydrated code.',
          points: 1,
        },
        {
          questionText: 'Can a React Server Component directly use hooks like `useState` or `useEffect`?',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'useState, useEffect, and browser APIs are only permitted in Client Components because Server Components run on the server.',
          points: 1,
        },
        {
          questionText: 'What are Server Actions in modern Next.js?',
          type: 'multiple-choice',
          options: [
            'Asynchronous functions executed on the server, callable from form submissions or client events without writing manual API routes',
            'Server-side WebSockets listeners',
            'Cron jobs running on Vercel infrastructure',
            'Node.js cluster child processes',
          ],
          correctAnswer: 'Asynchronous functions executed on the server, callable from form submissions or client events without writing manual API routes',
          explanation: 'Server Actions enable mutations and backend logic directly from components using the "use server" directive.',
          points: 2,
        },
        {
          questionText: 'Which special file in an App Router route folder defines the shared UI skeleton for a route segment?',
          type: 'multiple-choice',
          options: ['layout.tsx', 'page.tsx', 'template.tsx', 'default.tsx'],
          correctAnswer: 'layout.tsx',
          explanation: 'layout.tsx defines shared UI across route sub-trees and maintains state across navigation.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of the `loading.tsx` file in Next.js App Router?',
          type: 'multiple-choice',
          options: [
            'Automatically wraps the page in a React Suspense Boundary with an instant loading skeleton',
            'Pre-caches image assets from CDN',
            'Displays an HTTP 404 error page',
            'Checks user authorization cookies',
          ],
          correctAnswer: 'Automatically wraps the page in a React Suspense Boundary with an instant loading skeleton',
          explanation: 'loading.tsx creates an instant loading state using React Suspense during navigation.',
          points: 2,
        },
        {
          questionText: 'How do you create a dynamic route segment for a blog post ID in the Next.js App Router?',
          type: 'multiple-choice',
          options: ['app/blog/[id]/page.tsx', 'app/blog/:id/page.tsx', 'app/blog/{id}/page.tsx', 'app/blog/_id/page.tsx'],
          correctAnswer: 'app/blog/[id]/page.tsx',
          explanation: 'Square brackets [param] define dynamic route parameters in Next.js file-system routing.',
          points: 1,
        },
        {
          questionText: 'What function is used in Next.js Server Components to revalidate cached data on demand?',
          type: 'multiple-choice',
          options: ['revalidatePath() or revalidateTag()', 'refreshCache()', 'clearServerState()', 'expireRoute()'],
          correctAnswer: 'revalidatePath() or revalidateTag()',
          explanation: 'revalidatePath and revalidateTag purge and update Next.js Data Cache entries.',
          points: 2,
        },
        {
          questionText: 'Next.js `<Image>` component automatically optimizes images, provides modern formats (WebP/AVIF), and prevents layout shifts.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'next/image handles responsive resizing, format conversion, and Cumulative Layout Shift (CLS) prevention.',
          points: 1,
        },
        {
          questionText: 'Which file is used in Next.js to handle custom HTTP requests (GET, POST, PATCH) like a standard REST API?',
          type: 'multiple-choice',
          options: ['route.ts', 'api.ts', 'server.ts', 'handler.ts'],
          correctAnswer: 'route.ts',
          explanation: 'Route Handlers are defined in route.js or route.ts files inside the app directory.',
          points: 1,
        },
        {
          questionText: 'What is the function `generateStaticParams()` used for in the App Router?',
          type: 'multiple-choice',
          options: [
            'Generates static route parameters at build time for Static Site Generation (SSG) of dynamic segments',
            'Generates database migrations',
            'Creates mock query params for unit testing',
            'Configures environment variables',
          ],
          correctAnswer: 'Generates static route parameters at build time for Static Site Generation (SSG) of dynamic segments',
          explanation: 'generateStaticParams replaces getStaticPaths from the Pages Router.',
          points: 2,
        },
        {
          questionText: 'What does the Next.js `middleware.ts` file allow you to do?',
          type: 'multiple-choice',
          options: [
            'Intercept and modify incoming requests before they reach route handlers or pages (e.g. auth checks, redirects)',
            'Directly query MongoDB Atlas from the edge',
            'Compile Tailwind CSS in the browser',
            'Automatically create database schemas',
          ],
          correctAnswer: 'Intercept and modify incoming requests before they reach route handlers or pages (e.g. auth checks, redirects)',
          explanation: 'Middleware runs before a request is completed, enabling redirects, header rewrites, and authentication guards.',
          points: 2,
        },
        {
          questionText: 'Client Components in Next.js are rendered ONLY in the browser and never rendered on the server.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'False',
          explanation: 'Client Components are still pre-rendered to HTML on the server during initial load and then hydrated in the browser.',
          points: 2,
        },
        {
          questionText: 'What does `notFound()` function imported from `next/navigation` do?',
          type: 'multiple-choice',
          options: ['Renders the closest not-found.tsx UI component and returns a 404 HTTP status', 'Redirects the user to the homepage', 'Throws an unhandled internal server error', 'Clears the browser history'],
          correctAnswer: 'Renders the closest not-found.tsx UI component and returns a 404 HTTP status',
          explanation: 'notFound() triggers the not-found boundary inside the current route segment.',
          points: 1,
        },
        {
          questionText: 'Which font loading library built into Next.js automatically downloads Google Fonts at build time with zero external network requests at runtime?',
          type: 'multiple-choice',
          options: ['next/font', 'next/typography', 'next/google-fonts', 'next/webfont'],
          correctAnswer: 'next/font',
          explanation: 'next/font automatically self-hosts fonts and inlines critical CSS with zero external network requests.',
          points: 1,
        },
      ],
    });

    // 7. Python 3 Core: Data Structures, OOP, Generators & Concurrency
    const quizPython = await Quiz.create({
      title: 'Python 3 Core: Data Structures, OOP & Advanced Features',
      description: 'Master list comprehensions, decorators, generators, dunder methods, GIL, dictionaries, and modern Python concepts.',
      subject: 'Python',
      difficulty: 'intermediate',
      teacher: teacher2._id,
      status: 'published',
      timeLimit: 20,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'py701',
      attemptsCount: 35,
      questions: [
        {
          questionText: 'What is the output of the following Python list comprehension?',
          type: 'multiple-choice',
          options: ['[0, 4, 16]', '[0, 2, 4]', '[4, 16]', '[1, 9, 25]'],
          correctAnswer: '[0, 4, 16]',
          explanation: 'range(5) produces 0, 1, 2, 3, 4. Even numbers are 0, 2, 4. Squaring them gives 0, 4, 16.',
          codeSnippet: '[x**2 for x in range(5) if x % 2 == 0]',
          points: 2,
        },
        {
          questionText: 'What is the fundamental difference between a Python List and a Python Tuple?',
          type: 'multiple-choice',
          options: [
            'Lists are mutable; Tuples are immutable',
            'Lists cannot hold mixed data types; Tuples can',
            'Tuples use square brackets; Lists use parentheses',
            'Lists are sorted automatically; Tuples are not',
          ],
          correctAnswer: 'Lists are mutable; Tuples are immutable',
          explanation: 'Tuples cannot be modified after creation, making them hashable and memory efficient.',
          points: 1,
        },
        {
          questionText: 'What is a Python Generator and what keyword is used to produce values lazily?',
          type: 'multiple-choice',
          options: [
            'A function that produces a sequence of values on the fly using the `yield` keyword',
            'A tool that converts Python to C++ using `generate`',
            'A class constructor using `return`',
            'A memory profiling tool using `next`',
          ],
          correctAnswer: 'A function that produces a sequence of values on the fly using the `yield` keyword',
          explanation: 'Generators yield values one at a time, keeping memory footprint minimal for large datasets.',
          points: 2,
        },
        {
          questionText: 'In Python, what is the Global Interpreter Lock (GIL)?',
          type: 'multiple-choice',
          options: [
            'A mutex mechanism that protects Python objects, preventing multiple native threads from executing Python bytecodes simultaneously',
            'A security sandbox that locks the file system',
            'A database connection pool lock',
            'A compile-time type constraint',
          ],
          correctAnswer: 'A mutex mechanism that protects Python objects, preventing multiple native threads from executing Python bytecodes simultaneously',
          explanation: 'The GIL ensures memory safety in CPython by restricting thread execution to one thread per CPU core.',
          points: 2,
        },
        {
          questionText: 'What does a Python decorator do?',
          type: 'multiple-choice',
          options: [
            'A callable that takes another function and extends or modifies its behavior without modifying source code',
            'Formats terminal strings with ANSI color codes',
            'Declares static types for arguments',
            'Compresses Python bytecode',
          ],
          correctAnswer: 'A callable that takes another function and extends or modifies its behavior without modifying source code',
          explanation: 'Decorators (@decorator_name) wrap functions with reusable pre/post execution logic.',
          points: 2,
        },
        {
          questionText: 'What is the output of `bool([])` and `bool({})` in Python?',
          type: 'multiple-choice',
          options: ['False and False', 'True and True', 'False and True', 'TypeError'],
          correctAnswer: 'False and False',
          explanation: 'Empty containers (lists, dicts, sets, tuples, strings) evaluate to False in boolean context.',
          points: 1,
        },
        {
          questionText: 'In Python OOP, what special dunder method is called when an object is created to initialize its attributes?',
          type: 'multiple-choice',
          options: ['__init__', '__new__', '__construct__', '__create__'],
          correctAnswer: '__init__',
          explanation: '__init__ is the initializer method called after the instance has been created.',
          points: 1,
        },
        {
          questionText: 'Python dictionaries preserve the insertion order of keys starting in Python 3.7+.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'Dictionary insertion order preservation became an official language specification in Python 3.7.',
          points: 1,
        },
        {
          questionText: 'What does `*args` and `**kwargs` represent in a function definition?',
          type: 'multiple-choice',
          options: [
            '*args captures variable positional arguments as a tuple; **kwargs captures keyword arguments as a dictionary',
            '*args specifies pointers; **kwargs specifies dereferences',
            '*args is required for recursive calls; **kwargs is for lambdas',
            '*args passes arrays; **kwargs passes classes',
          ],
          correctAnswer: '*args captures variable positional arguments as a tuple; **kwargs captures keyword arguments as a dictionary',
          explanation: '*args gathers extra positional arguments into a tuple, while **kwargs gathers keyword pairs into a dict.',
          points: 2,
        },
        {
          questionText: 'Which built-in Python module is standard for managing asynchronous I/O and coroutines?',
          type: 'multiple-choice',
          options: ['asyncio', 'threading', 'multiprocessing', 'concurrent'],
          correctAnswer: 'asyncio',
          explanation: 'asyncio provides event loop, coroutines, and tasks for asynchronous programming.',
          points: 1,
        },
        {
          questionText: 'What is the difference between `==` and `is` in Python?',
          type: 'multiple-choice',
          options: [
            '`==` checks for equality of values; `is` checks for object identity (same memory address)',
            '`==` is for numbers; `is` is for strings',
            '`is` checks value; `==` checks reference',
            'There is no difference in Python 3',
          ],
          correctAnswer: '`==` checks for equality of values; `is` checks for object identity (same memory address)',
          explanation: 'a == b checks if values match; a is b evaluates id(a) == id(b).',
          points: 1,
        },
        {
          questionText: 'What statement handles cleanup code in Python exceptions, guaranteed to run whether an exception occurred or not?',
          type: 'multiple-choice',
          options: ['finally', 'else', 'ensure', 'cleanup'],
          correctAnswer: 'finally',
          explanation: 'The finally clause always executes before leaving the try statement block.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of the `with` statement (Context Manager) in Python?',
          type: 'multiple-choice',
          options: [
            'Simplifies exception handling and ensures automatic cleanup of resources (such as closing open files)',
            'Includes external packages into current scope',
            'Binds multiple variables together',
            'Creates a temporary thread',
          ],
          correctAnswer: 'Simplifies exception handling and ensures automatic cleanup of resources (such as closing open files)',
          explanation: 'Context managers trigger __enter__ and __exit__ methods to guarantee safe resource release.',
          points: 2,
        },
        {
          questionText: 'What is a lambda function in Python?',
          type: 'multiple-choice',
          options: [
            'A small anonymous function defined using the `lambda` keyword that can take any number of arguments but only one expression',
            'A function that executes in the AWS Lambda cloud runtime',
            'A method that operates solely on mathematical matrices',
            'A decorator for class methods',
          ],
          correctAnswer: 'A small anonymous function defined using the `lambda` keyword that can take any number of arguments but only one expression',
          explanation: 'lambdas allow concise inline one-liner functions: lambda x: x * 2.',
          points: 1,
        },
        {
          questionText: 'Which function is used to pair elements from two or more iterables together into tuples?',
          type: 'multiple-choice',
          options: ['zip()', 'map()', 'pair()', 'combine()'],
          correctAnswer: 'zip()',
          explanation: 'zip(*iterables) aggregates elements from each of the iterables into an iterator of tuples.',
          points: 1,
        },
      ],
    });

    // 8. Node.js & Express: Backend Architecture, Streams & REST APIs
    const quizNode = await Quiz.create({
      title: 'Node.js & Express: Backend Architecture & REST APIs',
      description: 'Master Node.js event loop phases, Express middleware chaining, streams, buffers, JWT auth, and clustering.',
      subject: 'Node.js',
      difficulty: 'advanced',
      teacher: teacher2._id,
      status: 'published',
      timeLimit: 25,
      passingPercentage: 70,
      maxAttempts: 0,
      randomizeQuestions: true,
      randomizeAnswers: false,
      showCorrectAnswers: true,
      shareCode: 'node801',
      attemptsCount: 31,
      questions: [
        {
          questionText: 'In Express.js, what does the `next()` function call do inside middleware?',
          type: 'multiple-choice',
          options: [
            'Passes execution control to the next middleware function in the request-response cycle',
            'Terminates the HTTP request immediately',
            'Reruns the current middleware from the beginning',
            'Redirects the client to the next URL route',
          ],
          correctAnswer: 'Passes execution control to the next middleware function in the request-response cycle',
          explanation: 'If a middleware does not end the request-response cycle, it must call next() to prevent hanging requests.',
          points: 1,
        },
        {
          questionText: 'Which underlying C/C++ library handles the event loop and asynchronous I/O operations in Node.js?',
          type: 'multiple-choice',
          options: ['libuv', 'V8', 'OpenSSL', 'zlib'],
          correctAnswer: 'libuv',
          explanation: 'libuv provides the event loop, thread pool, and non-blocking I/O primitives for Node.js.',
          points: 2,
        },
        {
          questionText: 'What is the signature of an Express error-handling middleware function?',
          type: 'multiple-choice',
          options: [
            '(err, req, res, next) with 4 arguments',
            '(req, res, err) with 3 arguments',
            '(error, callback)',
            '(req, res) with try/catch',
          ],
          correctAnswer: '(err, req, res, next) with 4 arguments',
          explanation: 'Express identifies error-handling middleware specifically by checking that it accepts exactly 4 arguments.',
          points: 2,
        },
        {
          questionText: 'What are Streams in Node.js and why are they advantageous for handling large files?',
          type: 'multiple-choice',
          options: [
            'Objects that process data chunk by chunk without loading the entire dataset into memory at once',
            'Thread safe queues for database mutations',
            'Real-time WebSockets connections',
            'In-memory Redis cache buffers',
          ],
          correctAnswer: 'Objects that process data chunk by chunk without loading the entire dataset into memory at once',
          explanation: 'Streams allow reading and writing data in chunks, preventing out-of-memory errors on large files.',
          points: 2,
        },
        {
          questionText: 'What is the purpose of the `process.nextTick()` function?',
          type: 'multiple-choice',
          options: [
            'Schedules a callback to be invoked immediately after the current operation completes, before the event loop continues',
            'Schedules a timer for the next second',
            'Advances the system clock by one tick',
            'Pauses the CPU',
          ],
          correctAnswer: 'Schedules a callback to be invoked immediately after the current operation completes, before the event loop continues',
          explanation: 'process.nextTick callbacks run at the end of the current phase of the event loop, taking priority over setImmediate.',
          points: 2,
        },
        {
          questionText: 'In REST API design, which HTTP method should be used for idempotent full resource replacement?',
          type: 'multiple-choice',
          options: ['PUT', 'POST', 'PATCH', 'CONNECT'],
          correctAnswer: 'PUT',
          explanation: 'PUT replaces the entire resource idempotently, whereas PATCH applies partial modifications.',
          points: 1,
        },
        {
          questionText: 'Which HTTP response status code should be returned when an unauthenticated client attempts to access a protected route?',
          type: 'multiple-choice',
          options: ['401 Unauthorized', '403 Forbidden', '404 Not Found', '400 Bad Request'],
          correctAnswer: '401 Unauthorized',
          explanation: '401 Unauthorized indicates authentication credentials are missing or invalid; 403 indicates authenticated but forbidden.',
          points: 1,
        },
        {
          questionText: 'The `cluster` module in Node.js allows creating child processes (workers) that share the same server port.',
          type: 'true-false',
          options: ['True', 'False'],
          correctAnswer: 'True',
          explanation: 'The cluster module enables multi-core CPU utilization by spawning worker processes sharing listening sockets.',
          points: 1,
        },
        {
          questionText: 'What does `Buffer` class in Node.js represent?',
          type: 'multiple-choice',
          options: [
            'A fixed-size chunk of raw binary memory allocated outside the V8 JavaScript heap',
            'A string parser for HTML forms',
            'A database connection buffer',
            'A cache for HTTP cookies',
          ],
          correctAnswer: 'A fixed-size chunk of raw binary memory allocated outside the V8 JavaScript heap',
          explanation: 'Buffers deal with binary streams of octets directly in memory.',
          points: 2,
        },
        {
          questionText: 'What is the vulnerability known as "Event Loop Starvation"?',
          type: 'multiple-choice',
          options: [
            'When synchronous, CPU-intensive JavaScript code blocks the single thread and prevents other I/O events from executing',
            'Running out of disk memory',
            'Database deadlocks during transactions',
            'Corrupting the socket buffer',
          ],
          correctAnswer: 'When synchronous, CPU-intensive JavaScript code blocks the single thread and prevents other I/O events from executing',
          explanation: 'Heavy computation blocks the event loop, causing all concurrent requests to time out.',
          points: 2,
        },
        {
          questionText: 'Which middleware is standard in Express applications to parse incoming JSON request bodies?',
          type: 'multiple-choice',
          options: ['express.json()', 'express.bodyParser()', 'express.parseJson()', 'express.serialize()'],
          correctAnswer: 'express.json()',
          explanation: 'express.json() is built into Express 4.16+ to parse JSON payloads.',
          points: 1,
        },
        {
          questionText: 'What does the `helmet` npm package provide for Express applications?',
          type: 'multiple-choice',
          options: [
            'Sets various security-related HTTP response headers (XSS, Content Security Policy, HSTS)',
            'Encrypts MongoDB database records',
            'Provides rate limiting for brute force defense',
            'Compresses response payloads with Gzip',
          ],
          correctAnswer: 'Sets various security-related HTTP response headers (XSS, Content Security Policy, HSTS)',
          explanation: 'Helmet helps secure Express apps by setting appropriate HTTP response headers.',
          points: 1,
        },
        {
          questionText: 'Environment variables in Node.js are accessed through which global object?',
          type: 'multiple-choice',
          options: ['process.env', 'global.env', 'node.env', 'system.env'],
          correctAnswer: 'process.env',
          explanation: 'process.env holds user environment variables loaded by the system or dotenv.',
          points: 1,
        },
        {
          questionText: 'What is the purpose of the `worker_threads` module in Node.js?',
          type: 'multiple-choice',
          options: [
            'Enables running CPU-intensive operations across multiple threads sharing memory via ArrayBuffers',
            'Manages background HTTP web workers in the browser',
            'Creates automated database backup workers',
            'Watches file changes in development',
          ],
          correctAnswer: 'Enables running CPU-intensive operations across multiple threads sharing memory via ArrayBuffers',
          explanation: 'worker_threads allows executing CPU-heavy JavaScript in parallel threads.',
          points: 2,
        },
        {
          questionText: 'How can you prevent CORS (Cross-Origin Resource Sharing) errors when frontend and backend run on different domains?',
          type: 'multiple-choice',
          options: [
            'Configure the `cors` middleware with proper Access-Control-Allow-Origin headers matching the frontend URL',
            'Disable HTTPS on the server',
            'Change all GET requests into POST requests',
            'Store JWT tokens in localStorage only',
          ],
          correctAnswer: 'Configure the `cors` middleware with proper Access-Control-Allow-Origin headers matching the frontend URL',
          explanation: 'The cors middleware sends proper Access-Control-Allow-Origin and headers to permit authorized browser clients.',
          points: 1,
        },
      ],
    });

    console.log('[Seeder] Populating Global Question Bank across all subjects...');
    await QuestionBank.insertMany([
      {
        teacher: teacher1._id,
        subject: 'HTML',
        topic: 'Semantics',
        difficulty: 'beginner',
        questionText: 'What is the correct HTML element for inserting a line break?',
        type: 'multiple-choice',
        options: ['<br>', '<lb>', '<break>', '<newline>'],
        correctAnswer: '<br>',
        explanation: 'The <br> tag inserts a single line break in text flow.',
        points: 1,
      },
      {
        teacher: teacher1._id,
        subject: 'CSS',
        topic: 'Flexbox',
        difficulty: 'intermediate',
        questionText: 'Which property defines the ability for a flex item to grow if necessary?',
        type: 'multiple-choice',
        options: ['flex-grow', 'flex-shrink', 'flex-basis', 'flex-flow'],
        correctAnswer: 'flex-grow',
        explanation: 'flex-grow specifies how much of the remaining space in the flex container should be assigned to the item.',
        points: 1,
      },
      {
        teacher: teacher2._id,
        subject: 'JavaScript',
        topic: 'Closures',
        difficulty: 'advanced',
        questionText: 'A closure in JavaScript is a function bundled together with references to its surrounding lexical environment.',
        type: 'true-false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'A closure gives an inner function access to an outer function scope even after the outer function has returned.',
        points: 2,
      },
      {
        teacher: teacher2._id,
        subject: 'JavaScript',
        topic: 'DOM',
        difficulty: 'beginner',
        questionText: 'Which method adds an event listener to an HTML element in the browser DOM?',
        type: 'multiple-choice',
        options: ['addEventListener', 'attachEvent', 'bindEvent', 'listenEvent'],
        correctAnswer: 'addEventListener',
        explanation: 'element.addEventListener() sets up a function that will be called whenever the specified event is delivered to the target.',
        points: 1,
      },
      {
        teacher: teacher1._id,
        subject: 'TypeScript',
        topic: 'Types',
        difficulty: 'beginner',
        questionText: 'Which keyword is used to define an immutable alias for another type in TypeScript?',
        type: 'multiple-choice',
        options: ['type', 'alias', 'typedef', 'declare'],
        correctAnswer: 'type',
        explanation: 'The type keyword creates a new name for a type.',
        points: 1,
      },
      {
        teacher: teacher1._id,
        subject: 'React',
        topic: 'Hooks',
        difficulty: 'intermediate',
        questionText: 'Which hook returns a stateful value and a function to update it?',
        type: 'multiple-choice',
        options: ['useState', 'useEffect', 'useRef', 'useCallback'],
        correctAnswer: 'useState',
        explanation: 'useState is the primary React hook for local component state.',
        points: 1,
      },
      {
        teacher: teacher2._id,
        subject: 'Next.js',
        topic: 'Routing',
        difficulty: 'intermediate',
        questionText: 'Next.js App Router uses folders to define routes.',
        type: 'true-false',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Each folder in the app directory represents a route segment mapped to a URL path.',
        points: 1,
      },
      {
        teacher: teacher2._id,
        subject: 'Python',
        topic: 'Data Structures',
        difficulty: 'beginner',
        questionText: 'Which collection type in Python is unordered and contains only unique elements?',
        type: 'multiple-choice',
        options: ['set', 'list', 'tuple', 'dict'],
        correctAnswer: 'set',
        explanation: 'Sets store unique items with fast O(1) membership checks.',
        points: 1,
      },
      {
        teacher: teacher2._id,
        subject: 'Node.js',
        topic: 'Modules',
        difficulty: 'beginner',
        questionText: 'What is the official ES Module import syntax in modern Node.js?',
        type: 'multiple-choice',
        options: ['import module from "module"', 'const module = require("module")', 'include "module"', 'using module'],
        correctAnswer: 'import module from "module"',
        explanation: 'ECMAScript Modules (ESM) use standard import/export statements.',
        points: 1,
      },
    ]);

    console.log('[Seeder] Creating Class Groups & Assignments...');
    const cohortClass = await ClassGroup.create({
      name: 'Web Engineering Cohort 2026',
      description: 'Official university cohort covering HTML, CSS, JavaScript, React, and Python full-stack engineering.',
      subject: 'Full-Stack Web Development',
      teacher: teacher1._id,
      inviteCode: 'WEB-2026',
      students: [student1._id, student2._id, student3._id, student4._id, student5._id],
    });

    await Assignment.create({
      quiz: quizHtml._id,
      classGroup: cohortClass._id,
      teacher: teacher1._id,
      title: 'Assignment 1: Semantic Architecture Mastery',
      startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      attemptLimit: 3,
      timeLimit: 15,
      status: 'active',
    });

    await Assignment.create({
      quiz: quizReact._id,
      classGroup: cohortClass._id,
      teacher: teacher1._id,
      title: 'Assignment 2: React 18 Architecture Evaluation',
      startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      attemptLimit: 2,
      timeLimit: 20,
      status: 'active',
    });

    console.log('[Seeder] Seeding Rich Student Mastery History across Multiple Disciplines for David Miller...');
    // Seed diverse historical attempts for student 1 to populate charts across subjects
    const historicalAttempts = [
      { quiz: quizHtml, subject: 'HTML', score: 14, max: 15, pct: 93, daysAgo: 6, switches: 0 },
      { quiz: quizCss, subject: 'CSS', score: 12, max: 15, pct: 80, daysAgo: 5, switches: 1 },
      { quiz: quizJs, subject: 'JavaScript', score: 13, max: 15, pct: 87, daysAgo: 4, switches: 0 },
      { quiz: quizTs, subject: 'TypeScript', score: 13, max: 15, pct: 87, daysAgo: 3, switches: 0 },
      { quiz: quizReact, subject: 'React', score: 14, max: 15, pct: 93, daysAgo: 2, switches: 0 },
      { quiz: quizNext, subject: 'Next.js', score: 11, max: 15, pct: 73, daysAgo: 1, switches: 1 },
      { quiz: quizPython, subject: 'Python', score: 13, max: 15, pct: 87, daysAgo: 0, switches: 0 },
    ];

    for (const h of historicalAttempts) {
      await QuizAttempt.create({
        student: student1._id,
        quiz: h.quiz._id,
        quizTitle: h.quiz.title,
        subject: h.subject,
        questionsSnapshot: h.quiz.questions.map((q: any) => ({
          questionText: q.questionText,
          type: q.type,
          options: q.options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          codeSnippet: q.codeSnippet,
          points: q.points,
        })),
        answers: h.quiz.questions.map((q: any, idx: number) => ({
          questionIndex: idx,
          questionText: q.questionText,
          selectedAnswer: idx < h.score ? q.correctAnswer : q.options[0],
          correctAnswer: q.correctAnswer,
          isCorrect: idx < h.score,
          pointsEarned: idx < h.score ? q.points : 0,
          explanation: q.explanation,
        })),
        score: h.score,
        maxScore: h.max,
        percentage: h.pct,
        passed: h.pct >= 70,
        timeSpentSeconds: 450 + Math.floor(Math.random() * 200),
        tabSwitchesCount: h.switches,
        attemptNumber: 1,
        completedAt: new Date(Date.now() - h.daysAgo * 24 * 60 * 60 * 1000),
      });
    }

    // Seed notifications
    await Notification.create({
      user: student1._id,
      title: 'Welcome to QuizRoom Self-Study',
      message: 'Explore over 120+ published questions across HTML, CSS, JavaScript, TypeScript, React, Next.js, Python, and Node.js. No teacher required!',
      type: 'assignment',
      link: '/student/quizzes',
      isRead: false,
    });

    console.log('[Seeder] ==============================================');
    console.log('[Seeder] 8 Full Quizzes Seeded Successfully!');
    console.log('[Seeder] - HTML, CSS, JavaScript, TypeScript, React, Next.js, Python, Node.js');
    console.log('[Seeder] Demo Credentials:');
    console.log('[Seeder]   Teacher: teacher@example.com / password123');
    console.log('[Seeder]   Student: student@example.com / password123');
    console.log('[Seeder]   Cohort Code: WEB-2026');
    console.log('[Seeder] ==============================================');

    await mongoose.disconnect();
    console.log('[Seeder] Disconnected cleanly.');
  } catch (error) {
    console.error('[Seeder] Error during database seeding:', error);
    process.exit(1);
  }
};

if (process.argv[1]?.includes('seedDatabase')) {
  seedDatabase();
}
